import datetime

import pytz


def is_ist_market_session_active(dt: datetime.datetime | None = None) -> bool:
    """Checks whether current or provided time falls within NSE/BSE IST market session (09:15 to 15:30 IST Mon-Fri)."""
    ist = pytz.timezone("Asia/Kolkata")
    now = dt.astimezone(ist) if dt else datetime.datetime.now(ist)
    if now.weekday() >= 5:
        return False
    market_open = now.replace(hour=9, minute=15, second=0, microsecond=0)
    market_close = now.replace(hour=15, minute=30, second=0, microsecond=0)
    return market_open <= now <= market_close


def round_to_ist_tick(price: float, tick_size: float = 0.05) -> float:
    """Rounds price to nearest NSE/BSE valid price tick (default 0.05 INR)."""
    if price <= 0:
        return 0.0
    return round(round(price / tick_size) * tick_size, 2)


"""
Generate the reference half of the docs from the code (plan M12.3) into ``docs/reference/``.

    uv run --extra web python scripts/gen_docs.py           # write the files
    uv run --extra web python scripts/gen_docs.py --check   # exit 1 if any file is stale

The hand-written docs (``docs/architecture.md``, ``docs/runbooks/``) explain; these files list -
the event catalogue, settings, risk limits and reason codes, the HTTP API and stream, the
packages and the scripts - straight from the code, so they cannot drift: ``tests/test_docs.py``
fails when one is stale.
"""

import argparse
import ast
import json
import re
import sys
import types
import typing
from collections import defaultdict
from collections.abc import Callable
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).parent.parent))

from pydantic import SecretStr  # noqa: E402
from pydantic.fields import FieldInfo  # noqa: E402
from src.config.limits import RiskLimits  # noqa: E402
from src.config.settings import Settings  # noqa: E402
from src.domain.events import EVENT_TYPES  # noqa: E402
from src.domain.types import ReasonCode  # noqa: E402
from src.risk.checks.base import OPENS  # noqa: E402
from src.risk.engine import DEFAULT_CHECKS  # noqa: E402
from src.web.stream import EVENT_TOPICS, SLOT_TOPICS, topic_of  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "docs" / "reference"
OPENAPI = ROOT / "frontend" / "openapi.json"
HEADER = "<!-- Generated by scripts/gen_docs.py from the code: do not edit by hand. -->\n\n"


# -- helpers ---------------------------------------------------------------------------------------


def table(*headers: str) -> str:
    """A Markdown table's header and separator rows."""
    return "| " + " | ".join(headers) + " |\n|" + " --- |" * len(headers) + "\n"


def cell(text: object) -> str:
    """Make a value safe for one Markdown table cell."""
    return str(text).replace("|", "\\|").replace("\n", " ").strip() or "-"


def first_paragraph(doc: str | None) -> str:
    if not doc:
        return ""
    return " ".join(doc.strip().split("\n\n")[0].split())


def type_name(annotation: Any) -> str:
    """A readable type: ``str | None``, ``'dev' | 'paper'``, ``secret``, ``list[Signal]``."""
    if annotation is None or annotation is type(None):
        return "None"
    if annotation is Ellipsis:
        return "..."
    if annotation is SecretStr:
        return "secret"
    origin = typing.get_origin(annotation)
    args = typing.get_args(annotation)
    if origin is typing.Literal:
        return " | ".join(repr(a) for a in args)
    if origin in (typing.Union, types.UnionType):
        return " | ".join(type_name(a) for a in args)
    if origin is typing.Annotated:
        return type_name(args[0])
    if origin is not None:
        name = getattr(origin, "__name__", str(origin))
        return f"{name}[{', '.join(type_name(a) for a in args)}]"
    return getattr(annotation, "__name__", str(annotation).replace("typing.", ""))


def default_of(info: FieldInfo) -> str:
    if info.is_required():
        return "required"
    if info.default_factory is not None:
        return repr(info.default_factory())  # type: ignore[call-arg]
    value = info.default
    if value is None:
        return "unset"
    if isinstance(value, SecretStr):
        return "(secret)"
    if isinstance(value, Path):
        return str(value.relative_to(ROOT)) if value.is_relative_to(ROOT) else str(value)
    return repr(value)


def bounds_of(info: FieldInfo) -> str:
    out = []
    for meta in info.metadata:
        for attr, sign in (("gt", ">"), ("ge", ">="), ("lt", "<"), ("le", "<=")):
            value = getattr(meta, attr, None)
            if value is not None:
                out.append(f"{sign} {value}")
    return ", ".join(out)


# -- events ----------------------------------------------------------------------------------------


def render_events() -> str:
    lines = [HEADER, "# Event catalogue\n\n",
             "Every fact the system records is one of these payloads, appended to the event store "
             "(`src/store/`) inside an envelope `{seq, ts_utc, ist_date, type, schema_version, "
             "decision_id, cycle_id, book_id, symbol, source, payload}`. Projections (orders, "
             "fills, positions, trades, decisions, ...) are pure functions of these events. "
             f"{len(EVENT_TYPES)} types; the stream topic is where the web console receives it.\n\n",
             table("Type", "Version", "Topic", "Description")]  # fmt: skip
    for name in sorted(EVENT_TYPES):
        cls = EVENT_TYPES[name]
        lines.append(f"| [{name}](#{name.lower()}) | {cls.schema_version} | {topic_of(name)} | "
                     f"{cell(first_paragraph(cls.__doc__))} |\n")  # fmt: skip
    for name in sorted(EVENT_TYPES):
        cls = EVENT_TYPES[name]
        lines.append(f"\n## {name}\n\n")
        doc = first_paragraph(cls.__doc__)
        if doc:
            lines.append(f"{doc}\n\n")
        lines.append(table("Field", "Type", "Default"))
        for field, info in cls.model_fields.items():
            default = "" if info.is_required() else default_of(info)
            lines.append(f"| `{field}` | {cell(type_name(info.annotation))} | {cell(default)} |\n")
    return "".join(lines)


# -- settings --------------------------------------------------------------------------------------


def render_settings() -> str:
    lines = [HEADER, "# Settings\n\n",
             "`src/config/settings.py`, read from the environment or the repo's `.env` "
             "(`RAKSHAQUANT_ENV_FILE` points elsewhere, or `none` for no file). Names are "
             "case-insensitive; unknown keys are ignored, so an old `.env` still loads. Secrets "
             "are never logged or shown. Risk limits are separate: see "
             "[risk.md](risk.md).\n\n",
             table("Variable", "Type", "Default", "Description")]  # fmt: skip
    for field, info in Settings.model_fields.items():
        lines.append(f"| `{field.upper()}` | {cell(type_name(info.annotation))} | "
                     f"{cell(default_of(info))} | {cell(info.description or '')} |\n")  # fmt: skip
    return "".join(lines)


# -- risk ------------------------------------------------------------------------------------------


def _text(node: ast.expr) -> str | None:
    if isinstance(node, ast.Constant) and isinstance(node.value, str):
        return node.value
    if isinstance(node, ast.JoinedStr):
        return "".join(v.value if isinstance(v, ast.Constant) else "{...}" for v in node.values)
    return None


def _code(node: ast.expr | None) -> str | None:
    if isinstance(node, ast.Attribute) and node.attr in ReasonCode.__members__:
        return node.attr
    return None


def check_messages() -> dict[str, str]:
    """The first human message each reason code is raised with, from the risk package's code:
    ``block(R.X, "message")``, ``resize(R.X, qty, "message")`` or
    ``RiskCheckResult(code=ReasonCode.X, ..., message="...")``."""
    found: dict[str, str] = {}
    for path in sorted((ROOT / "src" / "risk").rglob("*.py")):
        for node in ast.walk(ast.parse(path.read_text(encoding="utf-8"))):
            if not isinstance(node, ast.Call):
                continue
            keywords = {k.arg: k.value for k in node.keywords if k.arg}
            code = _code(node.args[0] if node.args else keywords.get("code"))
            if code is None or code in found:
                continue
            candidates = [keywords["message"]] if "message" in keywords else node.args[1:]
            text = next((t for t in map(_text, candidates) if t), None)
            if text:
                found[code] = text
    return found


def breach_codes() -> set[str]:
    """Codes the risk monitor raises as breaches (``src/risk/state.py``)."""
    tree = ast.parse((ROOT / "src" / "risk" / "state.py").read_text(encoding="utf-8"))
    return {c for node in ast.walk(tree) if (c := _code(node if isinstance(node, ast.expr)
                                                      else None))}  # fmt: skip


def render_risk() -> str:
    lines = [HEADER, "# Risk limits and reason codes\n\n",
             "Limits: `src/config/limits.py` (`RiskLimits`), set with `RISK_<NAME>` variables; "
             "values outside the bounds fail startup (exit 2). Their hash (`limits_hash`) is "
             "recorded on every risk decision; the month run's pre-registration pins it.\n\n",
             table("Variable", "Type", "Default", "Bounds", "Description")]  # fmt: skip
    for field, info in RiskLimits.model_fields.items():
        lines.append(f"| `RISK_{field.upper()}` | {cell(type_name(info.annotation))} | "
                     f"{cell(default_of(info))} | {cell(bounds_of(info))} | "
                     f"{cell(info.description or '')} |\n")  # fmt: skip
    applies = {c.code.value: c.applies_to for c in DEFAULT_CHECKS}
    messages, breaches = check_messages(), breach_codes()
    lines.append("\n## Reason codes\n\nEvery blocked or resized order names its codes "
                 "(`RiskDecision.reasons`). *Pre-trade check*: on entries only, or on every "
                 "order including exits (exits fail open: only these few can stop one). "
                 "*Monitor breach*: also raised by the risk monitor's 60-second tick, which "
                 "trips the kill switches (see `docs/runbooks/kill-switch.md`).\n\n"
                 + table("Code", "Level", "Pre-trade check", "Monitor breach", "Message"))  # fmt: skip
    for code in ReasonCode:
        kinds = applies.get(code.value)
        target = "-" if kinds is None else ("entries" if kinds <= OPENS else "every order")
        lines.append(f"| `{code.value}` | {code.level.value} | {target} | "
                     f"{'yes' if code.value in breaches else ''} | "
                     f"{cell(messages.get(code.value, ''))} |\n")  # fmt: skip
    return "".join(lines)


# -- API -------------------------------------------------------------------------------------------


def _ref(schema: dict[str, Any] | None) -> str:
    if not schema:
        return ""
    if "$ref" in schema:
        return str(schema["$ref"]).rsplit("/", 1)[-1]
    if schema.get("type") == "array" and "items" in schema:
        return f"list[{_ref(schema['items'])}]"
    return str(schema.get("type", ""))


def render_api() -> str:
    spec = json.loads(OPENAPI.read_text(encoding="utf-8"))
    lines = [HEADER, "# HTTP API and event stream\n\n",
             "The web console's server (`src/web/server.py`), from the OpenAPI document "
             "(`frontend/openapi.json`, itself checked against the code by "
             "`tests/test_api_contract.py`). Every `/api/*` route except `/api/health` needs "
             "the per-launch token as `Authorization: Bearer`; state-changing requests must "
             "come from the console's own origin.\n\n",
             table("Method", "Path", "Query", "Body", "Response", "Description")]  # fmt: skip
    for path in sorted(spec["paths"]):
        for method, op in sorted(spec["paths"][path].items()):
            query = ", ".join(p["name"] for p in op.get("parameters", []) if p["in"] == "query")
            body = _ref(op.get("requestBody", {}).get("content", {})
                        .get("application/json", {}).get("schema"))  # fmt: skip
            ok = op.get("responses", {}).get("200", {}).get("content", {})
            response = _ref(ok.get("application/json", {}).get("schema"))
            text = first_paragraph(op.get("description") or op.get("summary") or "")
            lines.append(f"| {method.upper()} | `{path}` | {cell(query)} | {cell(body)} | "
                         f"{cell(response)} | {cell(text)} |\n")  # fmt: skip
    by_topic: dict[str, list[str]] = defaultdict(list)
    for name in sorted(EVENT_TYPES):
        by_topic[topic_of(name)].append(name)
    lines.append("\n## WebSocket stream (`/ws`)\n\nToken as the `rq.token.<token>` subprotocol "
                 "(the server answers `rq.v1`). Send `{\"subscribe\": [topics], \"since_seq\": n}`: "
                 "stored events after `n` are replayed, then new ones follow, none lost or "
                 "repeated; `events` subscribes to every event topic. Slots are latest-wins "
                 "values, not queued.\n\n" + table("Topic", "Kind", "Carries"))  # fmt: skip
    for topic in sorted(EVENT_TOPICS):
        lines.append(f"| `{topic}` | events | {cell(', '.join(by_topic[topic]))} |\n")
    for topic in sorted(SLOT_TOPICS):
        lines.append(f"| `{topic}` | slot | {'the console summary, every second' if topic == 'summary' else 'the latest quotes, at most 1 Hz'} |\n")  # fmt: skip
    return "".join(lines)


# -- packages and scripts --------------------------------------------------------------------------


def _docstring(path: Path) -> str:
    return first_paragraph(ast.get_docstring(ast.parse(path.read_text(encoding="utf-8"))))


def _imports(path: Path) -> set[str]:
    out = set()
    for node in ast.walk(ast.parse(path.read_text(encoding="utf-8"))):
        if isinstance(node, ast.ImportFrom) and node.module and node.module.startswith("src."):
            out.add(node.module.split(".")[1])
        elif isinstance(node, ast.Import):
            out |= {a.name.split(".")[1] for a in node.names if a.name.startswith("src.")}
    return out


def render_packages() -> str:
    src = ROOT / "src"
    packages = sorted(p.name for p in src.iterdir() if (p / "__init__.py").exists())
    deps: dict[str, set[str]] = {}
    for name in packages:
        found: set[str] = set()
        for path in (src / name).rglob("*.py"):
            found |= _imports(path)
        deps[name] = found - {name}
    lines = [HEADER, "# Packages\n\n",
             "The import root is `src`. Each package with its purpose (its `__init__` "
             "docstring, else its first module's), its modules, and the packages it imports.\n\n",
             "```mermaid\ngraph LR\n"]  # fmt: skip
    for name in packages:
        for dep in sorted(deps[name]):
            lines.append(f"  {name} --> {dep}\n")
    lines.append("```\n")
    for name in packages:
        modules = sorted(p for p in (src / name).rglob("*.py") if p.name != "__init__.py")
        purpose = _docstring(src / name / "__init__.py") or (
            _docstring(modules[0]) if modules else "")  # fmt: skip
        lines.append(f"\n## `src/{name}`\n\n{purpose}\n\n")
        lines.append(f"Imports: {', '.join(f'`{d}`' for d in sorted(deps[name])) or 'none'}.\n\n")
        if modules:
            lines.append(table("Module", "Purpose"))
            for path in modules:
                rel = path.relative_to(src).as_posix()
                lines.append(f"| `{rel}` | {cell(_docstring(path))} |\n")
    return "".join(lines)


def _synopsis(path: Path) -> str:
    """A PowerShell script's ``.SYNOPSIS`` (comment-based help)."""
    found = re.search(r"\.SYNOPSIS\s*\n(.*?)\n\s*\n", path.read_text(encoding="utf-8"), re.S)
    return " ".join(found.group(1).split()) if found else ""


def render_scripts() -> str:
    lines = [HEADER, "# Scripts\n\n",
             "Entry points in `scripts/`, run from the repo root with `uv run python "
             "scripts/<name>.py` (`--help` lists the options). Exit codes: 0 ok (Ctrl-C too), "
             "1 crash, 2 configuration error, 3 another instance holds this environment's "
             "state directory.\n\n" + table("Script", "Purpose")]  # fmt: skip
    for path in sorted((ROOT / "scripts").glob("*.py")):
        lines.append(f"| `{path.name}` | {cell(_docstring(path))} |\n")
    for path in sorted((ROOT / "scripts").glob("*.ps1")):
        lines.append(f"| `{path.name}` (PowerShell) | {cell(_synopsis(path))} |\n")
    return "".join(lines)


RENDERERS: dict[str, Callable[[], str]] = {
    "events.md": render_events,
    "settings.md": render_settings,
    "risk.md": render_risk,
    "api.md": render_api,
    "packages.md": render_packages,
    "scripts.md": render_scripts,
}


def render_all() -> dict[str, str]:
    return {name: render() for name, render in RENDERERS.items()}


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate docs/reference/ from the code.")
    parser.add_argument("--check", action="store_true", help="exit 1 if a file is stale")
    args = parser.parse_args()
    stale = []
    OUT.mkdir(parents=True, exist_ok=True)
    for name, text in render_all().items():
        path = OUT / name
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == text:
            continue
        stale.append(name)
        if not args.check:
            path.write_text(text, encoding="utf-8", newline="\n")
    if args.check and stale:
        print(f"stale: {', '.join(stale)} (run scripts/gen_docs.py)")
        return 1
    print(f"{'checked' if args.check else 'wrote'} docs/reference/ ({len(RENDERERS)} files"
          f"{'' if args.check or not stale else ', updated: ' + ', '.join(stale)})")  # fmt: skip
    return 0


if __name__ == "__main__":
    sys.exit(main())
