import datetime

import pytz


def is_ist_market_session_active(dt: datetime.datetime | None = None) -> bool:
    """Checks whether current or provided time falls within NSE/BSE IST market session (09:15 to 15:30 IST Mon-Fri)."""
    ist = pytz.timezone("Asia/Kolkata")
    now = dt.astimezone(ist) if dt else datetime.datetime.now(ist)
    if now.weekday() >= 5:
        return False
    market_open = now.replace(hour=9, minute=15, second=0, microsecond=0)
    market_close = now.replace(hour=15, minute=30, second=0, microsecond=0)
    return market_open <= now <= market_close


def round_to_ist_tick(price: float, tick_size: float = 0.05) -> float:
    """Rounds price to nearest NSE/BSE valid price tick (default 0.05 INR)."""
    if price <= 0:
        return 0.0
    return round(round(price / tick_size) * tick_size, 2)


# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dydxprotocol/clob/block_rate_limit_config.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ...gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n/dydxprotocol/clob/block_rate_limit_config.proto\x12\x11\x64ydxprotocol.clob\x1a\x14gogoproto/gogo.proto"\xac\x03\n\x1b\x42lockRateLimitConfiguration\x12]\n"max_short_term_orders_per_n_blocks\x18\x01 \x03(\x0b\x32).dydxprotocol.clob.MaxPerNBlocksRateLimitB\x06\x18\x01\xc8\xde\x1f\x00\x12Y\n max_stateful_orders_per_n_blocks\x18\x02 \x03(\x0b\x32).dydxprotocol.clob.MaxPerNBlocksRateLimitB\x04\xc8\xde\x1f\x00\x12j\n/max_short_term_order_cancellations_per_n_blocks\x18\x03 \x03(\x0b\x32).dydxprotocol.clob.MaxPerNBlocksRateLimitB\x06\x18\x01\xc8\xde\x1f\x00\x12g\n.max_short_term_orders_and_cancels_per_n_blocks\x18\x04 \x03(\x0b\x32).dydxprotocol.clob.MaxPerNBlocksRateLimitB\x04\xc8\xde\x1f\x00";\n\x16MaxPerNBlocksRateLimit\x12\x12\n\nnum_blocks\x18\x01 \x01(\r\x12\r\n\x05limit\x18\x02 \x01(\rB8Z6github.com/dydxprotocol/v4-chain/protocol/x/clob/typesb\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "dydxprotocol.clob.block_rate_limit_config_pb2", globals())
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._options = None
    DESCRIPTOR._serialized_options = b"Z6github.com/dydxprotocol/v4-chain/protocol/x/clob/types"
    _BLOCKRATELIMITCONFIGURATION.fields_by_name["max_short_term_orders_per_n_blocks"]._options = None
    _BLOCKRATELIMITCONFIGURATION.fields_by_name[
        "max_short_term_orders_per_n_blocks"
    ]._serialized_options = b"\030\001\310\336\037\000"
    _BLOCKRATELIMITCONFIGURATION.fields_by_name["max_stateful_orders_per_n_blocks"]._options = None
    _BLOCKRATELIMITCONFIGURATION.fields_by_name[
        "max_stateful_orders_per_n_blocks"
    ]._serialized_options = b"\310\336\037\000"
    _BLOCKRATELIMITCONFIGURATION.fields_by_name["max_short_term_order_cancellations_per_n_blocks"]._options = None
    _BLOCKRATELIMITCONFIGURATION.fields_by_name[
        "max_short_term_order_cancellations_per_n_blocks"
    ]._serialized_options = b"\030\001\310\336\037\000"
    _BLOCKRATELIMITCONFIGURATION.fields_by_name["max_short_term_orders_and_cancels_per_n_blocks"]._options = None
    _BLOCKRATELIMITCONFIGURATION.fields_by_name[
        "max_short_term_orders_and_cancels_per_n_blocks"
    ]._serialized_options = b"\310\336\037\000"
    _BLOCKRATELIMITCONFIGURATION._serialized_start = 93
    _BLOCKRATELIMITCONFIGURATION._serialized_end = 521
    _MAXPERNBLOCKSRATELIMIT._serialized_start = 523
    _MAXPERNBLOCKSRATELIMIT._serialized_end = 582
# @@protoc_insertion_point(module_scope)
