//! REST and SSE transport for AI agent endpoints, backed by the SDK's
//! [`AgentContext`](longbridge::agent::AgentContext).

use std::pin::Pin;
use std::time::Duration;

use anyhow::{Context, Result};
use async_trait::async_trait;
use futures::{Stream, StreamExt};
use longbridge::agent::{ConversationStatus, ConversationStreamEvent, GetAgentsOptions};
use longbridge::httpclient::{HttpClientError, Json, Method};
use rust_i18n::t;

use super::events::{parse_data_line, AgentEvent};

#[derive(Debug, Clone, serde::Deserialize, serde::Serialize)]
pub struct WorkspaceInfo {
    pub id: String,
    pub name: String,
    #[serde(default)]
    pub created_at: i64,
    #[serde(default)]
    pub updated_at: i64,
}

#[derive(Debug, Clone, serde::Deserialize, serde::Serialize)]
pub struct AgentInfo {
    pub uid: String,
    pub name: String,
    #[serde(default)]
    pub description: String,
    #[serde(default)]
    pub mode: String,
    #[serde(default)]
    pub is_published: bool,
    /// Filled by the caller during traversal, not present in the API payload.
    #[serde(default)]
    pub workspace_id: String,
    #[serde(default)]
    pub workspace_name: String,
}

pub struct AgentPage {
    pub agents: Vec<AgentInfo>,
    pub total: u32,
}

impl AgentPage {
    /// Convert an SDK agents page into the CLI's transport-agnostic page.
    /// Workspace fields are left empty for the caller to fill.
    fn from_sdk(resp: longbridge::agent::AgentsResponse) -> Self {
        Self {
            agents: resp
                .agents
                .into_iter()
                .map(|a| AgentInfo {
                    uid: a.uid,
                    name: a.name,
                    description: a.description,
                    mode: a.mode,
                    is_published: a.is_published,
                    workspace_id: String::new(),
                    workspace_name: String::new(),
                })
                .collect(),
            total: u32::try_from(resp.total).unwrap_or(0),
        }
    }
}

/// Agent discovery API. Implementations wrap the real endpoints; tests use a
/// mock generated by `mockall`.
// The generated `MockAgentApi` stores one field per method, all `list_`-
// prefixed, which trips `struct_field_names` under `clippy --tests`.
#[cfg_attr(test, allow(clippy::struct_field_names))]
#[cfg_attr(test, mockall::automock)]
#[async_trait]
pub trait AgentApi: Send + Sync {
    async fn list_workspaces(&self) -> Result<Vec<WorkspaceInfo>>;
    async fn list_agents(
        &self,
        workspace_id: String,
        page: u32,
        limit: u32,
        name: Option<String>,
    ) -> Result<AgentPage>;
    /// `GET /v1/ai/agents` — every published, publicly shared agent on the
    /// platform, regardless of workspace membership.
    async fn list_public_agents(
        &self,
        page: u32,
        limit: u32,
        name: Option<String>,
    ) -> Result<AgentPage>;
}

pub struct LbAgentApi {
    pub verbose: bool,
}

#[async_trait]
impl AgentApi for LbAgentApi {
    async fn list_workspaces(&self) -> Result<Vec<WorkspaceInfo>> {
        if self.verbose {
            eprintln!("* GET /v1/ai/workspaces");
        }
        // The shared limiter meters (10 req/s) and retries the 429002
        // rate-limit rejection with backoff. The op returns the raw SDK error
        // so the limiter's "429" detection can see the code; the user-facing
        // context is attached only after retries are exhausted.
        let resp = crate::openapi::global_rate_limiter()
            .execute("agent_list_workspaces", || {
                Box::pin(async { crate::openapi::agent().workspaces().await })
            })
            .await
            .context("Failed to list AI workspaces")?;
        Ok(resp
            .workspaces
            .into_iter()
            .map(|w| WorkspaceInfo {
                id: w.id,
                name: w.name,
                created_at: w.created_at,
                updated_at: w.updated_at,
            })
            .collect())
    }

    async fn list_agents(
        &self,
        workspace_id: String,
        page: u32,
        limit: u32,
        name: Option<String>,
    ) -> Result<AgentPage> {
        if self.verbose {
            eprintln!("* GET /v1/ai/workspaces/{workspace_id}/agents");
        }
        let mut opts = GetAgentsOptions::new()
            .page(i32::try_from(page).unwrap_or(i32::MAX))
            .limit(i32::try_from(limit).unwrap_or(i32::MAX));
        if let Some(n) = name {
            opts = opts.name(n);
        }
        let resp = crate::openapi::global_rate_limiter()
            .execute("agent_list_agents", || {
                let ws = workspace_id.clone();
                let opts = opts.clone();
                Box::pin(async move { crate::openapi::agent().agents(ws, Some(opts)).await })
            })
            .await
            .context("Failed to list AI agents")?;
        Ok(AgentPage::from_sdk(resp))
    }

    async fn list_public_agents(
        &self,
        page: u32,
        limit: u32,
        name: Option<String>,
    ) -> Result<AgentPage> {
        if self.verbose {
            eprintln!("* GET /v1/ai/agents");
        }
        let mut opts = GetAgentsOptions::new()
            .page(i32::try_from(page).unwrap_or(i32::MAX))
            .limit(i32::try_from(limit).unwrap_or(i32::MAX));
        if let Some(n) = name {
            opts = opts.name(n);
        }
        let resp = crate::openapi::global_rate_limiter()
            .execute("agent_list_public_agents", || {
                let opts = opts.clone();
                Box::pin(async move { crate::openapi::agent().public_agents(Some(opts)).await })
            })
            .await
            .context("Failed to list public AI agents")?;
        Ok(AgentPage::from_sdk(resp))
    }
}

/// A conversation to stream: either a fresh round or the resumption of an
/// interrupted one. Mirrors the two SDK entry points
/// ([`AgentContext::conversation_streamed`](longbridge::agent::AgentContext::conversation_streamed)
/// and
/// [`continue_conversation_streamed`](longbridge::agent::AgentContext::continue_conversation_streamed)).
#[derive(Clone)]
pub enum ConversationRequest {
    New {
        agent_uid: String,
        query: String,
        chat_uid: Option<String>,
        parent_message_id: Option<String>,
    },
    Continue {
        agent_uid: String,
        chat_uid: String,
        message_id: String,
        answers: longbridge::agent::AnswersByToolCall,
    },
}

impl ConversationRequest {
    fn agent_uid(&self) -> &str {
        match self {
            ConversationRequest::New { agent_uid, .. }
            | ConversationRequest::Continue { agent_uid, .. } => agent_uid,
        }
    }

    /// The message this request is already addressed to, if any. A resumption
    /// names one up front; a fresh round only learns it from `chat_started`.
    fn ident(&self) -> Option<(String, String)> {
        match self {
            ConversationRequest::Continue {
                chat_uid,
                message_id,
                ..
            } => Some((chat_uid.clone(), message_id.clone())),
            ConversationRequest::New { .. } => None,
        }
    }
}

/// The final run status, as the lowercase wire string the outcome layer keys
/// on (`classify_outcome` in `chat.rs`).
fn status_str(status: ConversationStatus) -> String {
    match status {
        ConversationStatus::Succeeded => "succeeded",
        ConversationStatus::Interrupted => "interrupted",
        ConversationStatus::Failed => "failed",
        ConversationStatus::Stopped => "stopped",
    }
    .to_string()
}

/// Translate one SDK stream event into the CLI's [`AgentEvent`]. Returns
/// `None` for progress-only events the CLI does not surface (heartbeats,
/// subagent/tool-delegation timelines, plan updates, …); the aggregator
/// ignored these before, so dropping them here is behaviour-preserving.
fn map_event(ev: ConversationStreamEvent) -> Option<AgentEvent> {
    Some(match ev {
        ConversationStreamEvent::ChatStarted(p) => AgentEvent::ChatStarted {
            chat_uid: p.chat_uid,
            message_id: p.message_id,
        },
        ConversationStreamEvent::Message(p) => match p.message_type.as_str() {
            "answer" => AgentEvent::AnswerDelta { text: p.text },
            // `think` and `process` carry the agent's reasoning as it runs. A
            // turn spends most of its wall clock before the first answer byte,
            // and dropping these left that whole stretch showing nothing but a
            // spinner — indistinguishable from a stalled run.
            //
            // One message is either a stage boundary (named in `stage_title`,
            // no text) or a chunk of reasoning (text, no title); a message with
            // neither repeats a stage already announced and is dropped.
            "think" | "process" => {
                if p.stage_title.is_empty() {
                    if p.text.is_empty() {
                        return None;
                    }
                    AgentEvent::ThinkingDelta { text: p.text }
                } else {
                    AgentEvent::StageStarted {
                        title: p.stage_title,
                    }
                }
            }
            _ => return None,
        },
        ConversationStreamEvent::ThinkingStarted(_) => AgentEvent::ThinkingStarted,
        ConversationStreamEvent::ThinkingFinished(_) => AgentEvent::ThinkingFinished,
        ConversationStreamEvent::NodeToolUseStarted(p) => AgentEvent::ToolUseStarted {
            tool_name: p.tool_name,
        },
        ConversationStreamEvent::NodeToolUseFinished(p) => AgentEvent::ToolUseFinished {
            tool_name: p.tool_name,
            status: p.status,
            error: p.error,
        },
        ConversationStreamEvent::WorkflowFinished(resp) => AgentEvent::WorkflowFinished {
            status: status_str(resp.status),
            // Carry the SDK's already-typed values straight through — no
            // JSON round-trip.
            references: resp.references.unwrap_or_default(),
            further_questions: resp.further_questions.unwrap_or_default(),
            elapsed_time: Some(resp.elapsed_time),
            error_message: resp.error.map(|e| e.message).unwrap_or_default(),
        },
        ConversationStreamEvent::HumanInteractionRequired(resp) => {
            AgentEvent::HumanInteractionRequired {
                interrupt: serde_json::to_value(&resp.interrupt).unwrap_or(serde_json::Value::Null),
            }
        }
        ConversationStreamEvent::ChatFinished(p) => AgentEvent::ChatFinished {
            error_message: p.error_message,
        },
        ConversationStreamEvent::ChatTitleUpdated(p) => {
            AgentEvent::ChatTitleUpdated { title: p.title }
        }
        // The SDK has no typed variant for `token_usage`, so it arrives here as
        // a raw event carrying the cumulative counts for the round.
        ConversationStreamEvent::Other { event, data } if event == "token_usage" => {
            AgentEvent::TokenUsage(crate::openapi::chats::TokenUsage::from_data(&data)?)
        }
        ConversationStreamEvent::Other { event, .. } => AgentEvent::Unknown { event },
        // Progress-only events the CLI does not display.
        ConversationStreamEvent::Ping
        | ConversationStreamEvent::WorkflowStarted(_)
        | ConversationStreamEvent::SubagentStarted(_)
        | ConversationStreamEvent::SubagentProgress(_)
        | ConversationStreamEvent::SubagentFinished(_)
        | ConversationStreamEvent::AgentToolStarted(_)
        | ConversationStreamEvent::AgentToolProgress(_)
        | ConversationStreamEvent::AgentToolFinished(_)
        | ConversationStreamEvent::QueryMasked(_)
        | ConversationStreamEvent::PlanChanged(_)
        | ConversationStreamEvent::ContextCompressStarted(_)
        | ConversationStreamEvent::ContextCompressFinished(_) => return None,
    })
}

type EventStream = Pin<Box<dyn Stream<Item = longbridge::Result<ConversationStreamEvent>> + Send>>;

/// Backoff schedule for the pre-stream 429002 handshake retry (short in tests).
#[cfg(test)]
const HANDSHAKE_BACKOFF_SECS: [f64; 3] = [0.01, 0.02, 0.04];
#[cfg(not(test))]
const HANDSHAKE_BACKOFF_SECS: [f64; 3] = [1.0, 2.0, 4.0];

/// True only for the exact 429002 rate-limit rejection. A *typed* check (not a
/// Display substring like the shared limiter's) because a false positive on
/// the streaming path would replay the conversation POST — a non-idempotent
/// duplicate agent run.
fn is_rate_limited(err: &longbridge::Error) -> bool {
    matches!(
        err,
        longbridge::Error::HttpClient(longbridge::httpclient::HttpClientError::OpenApi {
            code, ..
        }) if *code == 429_002
    )
}

/// True for the server's 403 rejection of a conversation. Its message field
/// is a bare "success", so the CLI supplies the actionable context itself.
fn is_forbidden(err: &longbridge::Error) -> bool {
    matches!(
        err,
        longbridge::Error::HttpClient(longbridge::httpclient::HttpClientError::OpenApi {
            code, ..
        }) if *code == 403
    )
}

/// One pre-stream POST handshake attempt, returning the raw SDK error so the
/// caller can classify it precisely.
// The error size is the SDK's; boxing here would strip the type the caller
// classifies on.
#[allow(clippy::result_large_err)]
async fn open_conversation_stream(
    ctx: &longbridge::agent::AgentContext,
    req: &ConversationRequest,
) -> longbridge::Result<EventStream> {
    let stream: EventStream = match req.clone() {
        ConversationRequest::New {
            agent_uid,
            query,
            chat_uid,
            parent_message_id,
        } => Box::pin(
            ctx.conversation_streamed(agent_uid, query, chat_uid, parent_message_id)
                .await?,
        ),
        ConversationRequest::Continue {
            agent_uid,
            chat_uid,
            message_id,
            answers,
        } => Box::pin(
            ctx.continue_conversation_streamed(agent_uid, chat_uid, message_id, answers)
                .await?,
        ),
    };
    Ok(stream)
}

/// No SSE frame at all for this long means the connection is gone rather than
/// the agent being slow.
///
/// A run legitimately spends minutes between *interesting* events — a long tool
/// call says nothing while it works — so silence on its own proves nothing. The
/// server's `ping` heartbeat is what makes this measurable: it arrives every few
/// seconds on a healthy connection and the loop below counts it as liveness even
/// though nothing is rendered for it. A minute without even that is the socket,
/// not the agent.
const STREAM_IDLE_SECS: u64 = 60;
const STREAM_IDLE_TIMEOUT: Duration = Duration::from_secs(STREAM_IDLE_SECS);

/// Backoff between re-attach attempts (short in tests).
#[cfg(test)]
const RECONNECT_BACKOFF_SECS: [f64; 3] = [0.01, 0.02, 0.04];
#[cfg(not(test))]
const RECONNECT_BACKOFF_SECS: [f64; 3] = [1.0, 2.0, 4.0];

/// Only bounds the reconnect handshake — getting a status back — not the
/// event-by-event reads after it, which last as long as the run does.
const RECONNECT_HANDSHAKE_TIMEOUT: Duration = Duration::from_secs(30);

/// How long to keep waiting for a run to finish when re-attaching is not
/// possible, and how often to check.
const READ_BACK_WINDOW_SECS: u64 = 600;
const READ_BACK_POLL: Duration = Duration::from_secs(5);

/// One frame of an agent SSE stream: an event to surface, or `None` for a frame
/// that carries no event but proves the connection is alive (a heartbeat, or
/// progress the CLI does not render).
///
/// Normalizing to this is what lets the conversation endpoints — parsed by the
/// SDK — and the reconnect endpoint — parsed here — share one drain loop.
type Frame = Result<Option<AgentEvent>>;
type FrameStream = Pin<Box<dyn Stream<Item = Frame> + Send>>;

fn sdk_frames(
    stream: impl Stream<Item = longbridge::Result<ConversationStreamEvent>> + Send + 'static,
) -> FrameStream {
    Box::pin(stream.map(|item| item.map(map_event).map_err(anyhow::Error::new)))
}

/// Why the drain loop stopped.
enum StreamEnd {
    /// The run reported its own outcome. Whatever the connection does
    /// afterwards is teardown, not a lost answer.
    Complete,
    /// The stream ended in an orderly way — `chat_finished` came — but never
    /// carried the run's outcome.
    ///
    /// `workflow_finished` describes the workflow that produced the message
    /// rather than the message itself, so a reconnect that replays a message
    /// which had already finished ends without one (`../longbridge-gpui` notes
    /// the same). The answer is all there; only the verdict, sources and
    /// follow-ups still have to be read back.
    EndedWithoutOutcome,
    /// The connection stopped delivering while the run was still going.
    Broken(anyhow::Error),
}

/// Drain an SSE stream into `on_event`, watching for the connection dying under
/// it.
///
/// The run lives on the server, not in this connection, so losing the
/// connection is not the same as losing the run — a stream that stops
/// delivering is reported as a break rather than as a finished turn, which is
/// what lets a caller tell "the agent answered" apart from "we stopped hearing
/// about it".
///
/// `ident` collects the `chat_uid`/`message_id` the run is writing to: what a
/// reconnect addresses, and what names the message in a break report.
async fn drain_stream(
    stream: &mut FrameStream,
    on_event: &mut (dyn FnMut(AgentEvent) + Send),
    ident: &mut Option<(String, String)>,
) -> StreamEnd {
    // Neither marker returns early — the outcome is followed by more
    // housekeeping frames (`chat_title_updated`), and on a live stream
    // `chat_finished` is itself followed by `workflow_finished`. What they
    // change is how the stream *ending* is read, below.
    let mut outcome = false;
    let mut closing = false;
    loop {
        let next = tokio::time::timeout(STREAM_IDLE_TIMEOUT, stream.next()).await;
        // Idle: not even a heartbeat for a minute.
        let Ok(item) = next else {
            return ended(outcome, closing, || {
                anyhow::anyhow!(
                    "SSE stream went silent for {STREAM_IDLE_SECS}s{}",
                    describe(ident.as_ref())
                )
            });
        };
        match item {
            Some(Ok(frame)) => {
                let Some(ev) = frame else { continue };
                // `workflow_finished` carries the run's outcome; a pause for
                // human input ends the round just as definitively.
                outcome |= matches!(
                    ev,
                    AgentEvent::WorkflowFinished { .. }
                        | AgentEvent::HumanInteractionRequired { .. }
                );
                closing |= matches!(ev, AgentEvent::ChatFinished { .. });
                if let AgentEvent::ChatStarted {
                    chat_uid,
                    message_id,
                } = &ev
                {
                    *ident = Some((chat_uid.clone(), message_id.clone()));
                }
                on_event(ev);
            }
            Some(Err(err)) => {
                return ended(outcome, closing, || {
                    err.context(format!("SSE stream error{}", describe(ident.as_ref())))
                })
            }
            // End of stream. Orderly only if the run got far enough to say so:
            // closing early was previously indistinguishable from success, so a
            // connection dropped mid-answer finalized the turn as complete and
            // silently truncated it.
            None => {
                return ended(outcome, closing, || {
                    anyhow::anyhow!(
                        "SSE stream closed before the run reported an outcome{}",
                        describe(ident.as_ref())
                    )
                })
            }
        }
    }
}

/// Classify a stream that stopped delivering, by how far the run got first.
fn ended(outcome: bool, closing: bool, cause: impl FnOnce() -> anyhow::Error) -> StreamEnd {
    if outcome {
        StreamEnd::Complete
    } else if closing {
        StreamEnd::EndedWithoutOutcome
    } else {
        StreamEnd::Broken(cause())
    }
}

/// Name the interrupted message in a break report, when the server got far
/// enough to tell us which one it is.
fn describe(ident: Option<&(String, String)>) -> String {
    match ident {
        Some((chat_uid, message_id)) => format!(" (chat {chat_uid}, message {message_id})"),
        None => String::new(),
    }
}

/// `POST /v1/ai/agents/{id}/conversations/{chat_uid}/messages/{message_id}/reconnect`
/// — re-attach to a run whose connection died, replaying the message from the
/// beginning and then continuing live.
///
/// Mirrors the endpoint the desktop client reconnects with (`../longbridge-gpui`
/// `ai_agent::api::reconnect_message`). The SDK does not wrap it, so the request
/// goes through the shared signed HTTP client the same way the chat-history
/// endpoints do, and the frames are parsed by [`parse_data_line`].
async fn reconnect_stream(
    agent_id: &str,
    chat_uid: &str,
    message_id: &str,
) -> std::result::Result<FrameStream, HttpClientError> {
    let path = format!(
        "/v1/ai/agents/{agent_id}/conversations/{chat_uid}/messages/{message_id}/reconnect"
    );
    crate::openapi::global_rate_limiter().acquire().await;
    let raw = crate::openapi::http_client()
        .request(Method::POST, path)
        .body(Json(serde_json::json!({})))
        .timeout(RECONNECT_HANDSHAKE_TIMEOUT)
        .send_events()
        .await?;
    Ok(Box::pin(raw.map(|item| {
        item.map(|sse| parse_data_line(&sse.data))
            .map_err(anyhow::Error::new)
    })))
}

/// True when the gateway has no such route, as opposed to failing to serve it.
/// Retrying cannot conjure an endpoint, so this routes straight to the fallback.
fn endpoint_missing(err: &HttpClientError) -> bool {
    matches!(err, HttpClientError::OpenApi { code, .. } if *code == 404_000)
}

/// Re-attach to a run whose connection died, and see it through to its outcome.
///
/// Re-attaching replays the message from the start, so each attempt announces
/// itself with [`AgentEvent::StreamInterrupted`] and the consumer discards what
/// the dead connection produced rather than letting the replay double it.
///
/// Resending the original request is *not* an option here: the run is still
/// going on the server, so a resend would not resume it but start a second one
/// alongside it — two answers, two sets of tool calls, both billed.
async fn reattach(
    agent_id: &str,
    chat_uid: &str,
    message_id: &str,
    cause: anyhow::Error,
    verbose: bool,
    on_event: &mut (dyn FnMut(AgentEvent) + Send),
) -> Result<()> {
    let mut cause = cause;
    // Whether the announced restart is still unspent — nothing has been
    // delivered since, so the fallback below need not announce another.
    let mut pristine = false;
    for backoff in RECONNECT_BACKOFF_SECS {
        tracing::warn!("agent SSE stream broke, re-attaching: {cause:#}");
        if verbose {
            eprintln!("* SSE stream broke ({cause:#}); reconnecting");
        }
        on_event(AgentEvent::StreamInterrupted);
        pristine = true;
        match reconnect_stream(agent_id, chat_uid, message_id).await {
            Ok(mut frames) => {
                let mut ident = Some((chat_uid.to_string(), message_id.to_string()));
                pristine = false;
                match drain_stream(&mut frames, on_event, &mut ident).await {
                    StreamEnd::Complete => return Ok(()),
                    // The usual shape for a replay of a message that had
                    // already finished: everything is there but the verdict.
                    StreamEnd::EndedWithoutOutcome => {
                        return finalize_from_history(chat_uid, message_id, on_event).await
                    }
                    StreamEnd::Broken(err) => cause = err,
                }
            }
            Err(err) if endpoint_missing(&err) => {
                tracing::info!("no reconnect endpoint here; waiting the run out instead");
                if verbose {
                    eprintln!("* no reconnect endpoint; waiting for the run to finish");
                }
                break;
            }
            Err(err) => {
                cause = anyhow::Error::new(err).context("Failed to reconnect to the run");
            }
        }
        tokio::time::sleep(Duration::from_secs_f64(backoff)).await;
    }
    read_back_answer(chat_uid, message_id, cause, !pristine, verbose, on_event).await
}

/// Wait the run out and read the finished message back from chat history.
///
/// The fallback for when re-attaching is not possible. It cannot show the answer
/// being written — the server does not persist a message's chunks until the run
/// ends, so an in-flight message reads back empty — so it trades the live view
/// for not losing the answer.
async fn read_back_answer(
    chat_uid: &str,
    message_id: &str,
    cause: anyhow::Error,
    needs_reset: bool,
    verbose: bool,
    on_event: &mut (dyn FnMut(AgentEvent) + Send),
) -> Result<()> {
    // A partial re-attach may have replayed some of the message before breaking
    // again; the full text below replaces it rather than extending it. Skipped
    // when the caller's restart is still unspent, so the reader is not told the
    // connection dropped twice over for one drop.
    if needs_reset {
        on_event(AgentEvent::StreamInterrupted);
    }
    let deadline = std::time::Instant::now() + Duration::from_secs(READ_BACK_WINDOW_SECS);
    let finished = loop {
        tokio::time::sleep(READ_BACK_POLL).await;
        match crate::openapi::chats::chat_detail(chat_uid).await {
            Ok(detail) => {
                if let Some(msg) = detail
                    .messages
                    .into_iter()
                    .find(|m| m.id.to_string() == message_id)
                {
                    if !msg.is_generating() {
                        break Some(msg);
                    }
                }
            }
            // The network may still be down. Keep trying until the window closes.
            Err(err) => tracing::debug!("history poll failed while waiting out the run: {err:#}"),
        }
        if std::time::Instant::now() >= deadline {
            break None;
        }
    };
    let Some(msg) = finished else {
        return Err(cause.context(format!(
            "the run was still going {READ_BACK_WINDOW_SECS}s after the connection dropped"
        )));
    };
    if verbose {
        eprintln!("* read the finished answer back from chat history");
    }

    let reasoning = msg.reasoning();
    if !reasoning.is_empty() {
        on_event(AgentEvent::ThinkingDelta { text: reasoning });
    }
    let text = msg.text();
    if !text.is_empty() {
        on_event(AgentEvent::AnswerDelta { text });
    }
    // The stored usage equals the stream's final frame (the server writes the
    // round's cumulative total), so history restores what the dead connection
    // never delivered — and what the restart announcement above cleared.
    if let Some(usage) = msg.token_usage.filter(|usage| !usage.is_empty()) {
        on_event(AgentEvent::TokenUsage(usage));
    }
    let status = recovered_status(msg.status);
    on_event(AgentEvent::WorkflowFinished {
        status: status.to_string(),
        references: msg.references(),
        further_questions: msg.further_questions(),
        // Only ever reported by the stream event, and that stream is gone.
        elapsed_time: None,
        // Unlike the other read-back path, no `chat_finished` was seen here to
        // carry the server's own wording, so a failed run would otherwise
        // finalize looking like a clean one.
        error_message: if status == "failed" {
            t!("Agent.RunFailed").to_string()
        } else {
            String::new()
        },
    });
    Ok(())
}

/// Emit the run's outcome for a stream that delivered the answer but ended
/// without saying how the run went (see [`StreamEnd::EndedWithoutOutcome`]).
///
/// One read of the stored message, not the polling [`read_back_answer`] does:
/// `chat_finished` already established that the run is over. The answer is left
/// alone — the stream delivered it — and only the verdict, sources and
/// follow-ups are supplied.
async fn finalize_from_history(
    chat_uid: &str,
    message_id: &str,
    on_event: &mut (dyn FnMut(AgentEvent) + Send),
) -> Result<()> {
    let mut last: Option<anyhow::Error> = None;
    for backoff in RECONNECT_BACKOFF_SECS {
        match crate::openapi::chats::chat_detail(chat_uid).await {
            Ok(detail) => {
                let Some(msg) = detail
                    .messages
                    .into_iter()
                    .find(|m| m.id.to_string() == message_id)
                else {
                    last = Some(anyhow::anyhow!(
                        "chat {chat_uid} has no message {message_id}"
                    ));
                    break;
                };
                // The frame that would have carried the round's final total is
                // exactly what the truncated stream lost; the stored value is
                // its equal, so supply it alongside the verdict.
                if let Some(usage) = msg.token_usage.filter(|usage| !usage.is_empty()) {
                    on_event(AgentEvent::TokenUsage(usage));
                }
                on_event(AgentEvent::WorkflowFinished {
                    status: recovered_status(msg.status).to_string(),
                    references: msg.references(),
                    further_questions: msg.further_questions(),
                    // Only ever reported by the stream event that never came.
                    elapsed_time: None,
                    error_message: String::new(),
                });
                return Ok(());
            }
            Err(err) => last = Some(err),
        }
        tokio::time::sleep(Duration::from_secs_f64(backoff)).await;
    }
    Err(last
        .unwrap_or_else(|| anyhow::anyhow!("could not read the run outcome back"))
        .context("The run finished but its outcome could not be read back"))
}

/// Map a persisted message status onto the run-status wire string the outcome
/// layer keys on. The read-back counterpart of [`status_str`].
fn recovered_status(status: i32) -> &'static str {
    match status {
        1 => "succeeded",
        2 => "stopped",
        5 => "interrupted",
        // 3 (exception), 4 (blocked by the guard rails), and anything this
        // client has not learned yet: no usable answer came out of the run.
        _ => "failed",
    }
}

/// Stream a conversation through the SDK's `AgentContext`, dispatching each
/// surfaced event to `on_event`, and keep it alive across a lost connection.
///
/// Every attempt is metered through the shared 10 req/s limiter, and the
/// pre-stream handshake is retried only on a typed 429002 rate limit, so a
/// misclassified error can never replay (and duplicate) the conversation POST.
///
/// Once the stream is up, a break is handled by where it happened:
///
/// - **Before the server named a message**, nothing exists yet — so nothing a
///   resend could duplicate. The request goes out again.
/// - **After it**, the run is alive on the server and a resend would start a
///   second one beside it, so the connection is re-attached to the existing run
///   instead (see [`reattach`]).
pub async fn stream_conversation(
    req: ConversationRequest,
    verbose: bool,
    on_event: &mut (dyn FnMut(AgentEvent) + Send),
) -> Result<()> {
    // No auth-mode gate here: the conversation goes through the SDK's signing
    // `HttpClient` (`AgentContext` shares `Config::create_http_client()` with the
    // quote/trade contexts), so an API-key principal signs AI requests the same
    // way it signs every other endpoint. If the server declines an API-key
    // principal, that surfaces as a typed API error rather than a client-side
    // refusal that misreports the cause.
    let ctx = crate::openapi::agent();
    let agent_uid = req.agent_uid().to_string();
    let mut ident = req.ident();

    let mut last_err = None;
    for backoff in RECONNECT_BACKOFF_SECS {
        if verbose {
            eprintln!("* POST agent conversation (SSE)");
        }
        let mut stream = sdk_frames(open_conversation_stream_retrying(ctx, &req).await?);
        match drain_stream(&mut stream, on_event, &mut ident).await {
            StreamEnd::Complete => return Ok(()),
            StreamEnd::EndedWithoutOutcome => {
                return match &ident {
                    Some((chat_uid, message_id)) => {
                        finalize_from_history(chat_uid, message_id, on_event).await
                    }
                    // `chat_finished` cannot arrive before `chat_started`.
                    None => Ok(()),
                };
            }
            StreamEnd::Broken(err) => {
                if let Some((chat_uid, message_id)) = ident.clone() {
                    return reattach(&agent_uid, &chat_uid, &message_id, err, verbose, on_event)
                        .await;
                }
                tracing::warn!("agent SSE stream broke before the run was named: {err:#}");
                if verbose {
                    eprintln!("* SSE stream broke before the run started ({err:#}); resending");
                }
                // Nothing streamed can be trusted to survive the resend.
                on_event(AgentEvent::StreamInterrupted);
                last_err = Some(err);
                tokio::time::sleep(Duration::from_secs_f64(backoff)).await;
            }
        }
    }
    Err(last_err
        .unwrap_or_else(|| anyhow::anyhow!("the AI conversation could not be started"))
        .context("Gave up starting the AI conversation"))
}

/// Turn a failed handshake into the error the CLI should print. Shared by
/// the retry loop and the attempt that follows it, so a 403 reads the same
/// either side of the backoff being exhausted.
fn handshake_error(err: longbridge::Error) -> anyhow::Error {
    if is_forbidden(&err) {
        // A fresh error, not `.context(...)`: the CLI's error printer
        // downcasts to the SDK error and would show only the server's
        // message, which for this rejection is a bare "success".
        let trace = match &err {
            longbridge::Error::HttpClient(HttpClientError::OpenApi { trace_id, .. })
                if !trace_id.is_empty() =>
            {
                format!(" (trace_id: {trace_id})")
            }
            _ => String::new(),
        };
        return anyhow::anyhow!(
            "The agent refused the conversation (HTTP 403): it is \
             unpublished or not open to your account. Only published \
             agents can chat — `longbridge agent list --format json` \
             shows `is_published` per agent{trace}"
        );
    }
    anyhow::Error::new(err).context("Failed to run the AI conversation")
}

/// The pre-stream POST handshake, retried on a typed 429002 rate limit.
async fn open_conversation_stream_retrying(
    ctx: &longbridge::agent::AgentContext,
    req: &ConversationRequest,
) -> Result<impl Stream<Item = longbridge::Result<ConversationStreamEvent>> + Send + 'static> {
    for backoff in HANDSHAKE_BACKOFF_SECS {
        crate::openapi::global_rate_limiter().acquire().await;
        match open_conversation_stream(ctx, req).await {
            Ok(s) => return Ok(s),
            Err(e) if is_rate_limited(&e) => {
                tokio::time::sleep(Duration::from_secs_f64(backoff)).await;
            }
            Err(e) => return Err(handshake_error(e)),
        }
    }
    // Backoff exhausted: one final attempt, classified the same way.
    crate::openapi::global_rate_limiter().acquire().await;
    open_conversation_stream(ctx, req)
        .await
        .map_err(handshake_error)
}

#[cfg(test)]
mod tests {
    use super::*;

    use longbridge::agent::{ChatStartedPayload, ConversationResponse, MessagePayload};

    fn stream_of(events: Vec<ConversationStreamEvent>) -> FrameStream {
        sdk_frames(futures::stream::iter(events.into_iter().map(Ok)))
    }

    fn chat_started() -> ConversationStreamEvent {
        ConversationStreamEvent::ChatStarted(ChatStartedPayload {
            chat_uid: "ct_1".into(),
            message_id: "42".into(),
            chat_id: 1,
            error: String::new(),
            error_message: String::new(),
        })
    }

    fn answer(text: &str) -> ConversationStreamEvent {
        ConversationStreamEvent::Message(MessagePayload {
            text: text.into(),
            message_type: "answer".into(),
            ..Default::default()
        })
    }

    fn workflow_finished() -> ConversationStreamEvent {
        ConversationStreamEvent::WorkflowFinished(ConversationResponse {
            chat_uid: "ct_1".into(),
            message_id: "42".into(),
            status: ConversationStatus::Succeeded,
            answer: "hi".into(),
            references: None,
            further_questions: None,
            elapsed_time: 1.0,
            interrupt: None,
            error: None,
        })
    }

    async fn drain(events: Vec<ConversationStreamEvent>) -> (StreamEnd, Vec<AgentEvent>) {
        let mut stream = stream_of(events);
        let mut seen = Vec::new();
        let mut ident = None;
        let end = drain_stream(&mut stream, &mut |ev| seen.push(ev), &mut ident).await;
        (end, seen)
    }

    /// A connection that closes mid-answer used to be indistinguishable from a
    /// run that finished: the loop simply ran out of items and returned `Ok`,
    /// so the turn was finalized as complete with a truncated answer.
    #[tokio::test]
    async fn closing_before_the_run_reports_an_outcome_is_a_break() {
        let (end, seen) = drain(vec![chat_started(), answer("half an ans")]).await;
        let StreamEnd::Broken(err) = end else {
            panic!("expected a break");
        };
        let msg = format!("{err:#}");
        assert!(msg.contains("closed before"), "unexpected message: {msg}");
        // The break names the message the run was writing, which is what a
        // reconnect has to address.
        assert!(msg.contains("ct_1") && msg.contains("42"), "{msg}");
        // Whatever did arrive is still delivered.
        assert!(matches!(seen.last(), Some(AgentEvent::AnswerDelta { .. })));
    }

    /// Once the run has reported its outcome the connection has nothing left to
    /// deliver, so closing is teardown rather than a lost answer.
    #[tokio::test]
    async fn closing_after_the_run_reports_an_outcome_is_clean() {
        let (end, _) = drain(vec![chat_started(), answer("hi"), workflow_finished()]).await;
        assert!(matches!(end, StreamEnd::Complete));
    }

    /// A pause for human input ends the round just as definitively as a
    /// finished workflow: the server is waiting on us, not the other way round.
    #[tokio::test]
    async fn pausing_for_human_input_is_not_a_break() {
        let mut interrupted = match workflow_finished() {
            ConversationStreamEvent::WorkflowFinished(resp) => resp,
            _ => unreachable!(),
        };
        interrupted.status = ConversationStatus::Interrupted;
        let (end, _) = drain(vec![
            chat_started(),
            ConversationStreamEvent::HumanInteractionRequired(interrupted),
        ])
        .await;
        assert!(matches!(end, StreamEnd::Complete));
    }

    /// Silence long enough to outlast the server's own heartbeat is a dead
    /// connection. Before this the drain loop had no read deadline at all, so a
    /// connection that stopped delivering hung the turn indefinitely.
    #[tokio::test(start_paused = true)]
    async fn silence_past_the_heartbeat_window_is_a_break() {
        let mut stream: FrameStream = Box::pin(futures::stream::pending());
        let mut ident = Some(("ct_1".to_string(), "42".to_string()));
        let end = drain_stream(&mut stream, &mut |_| {}, &mut ident).await;
        let StreamEnd::Broken(err) = end else {
            panic!("expected a break");
        };
        assert!(format!("{err:#}").contains("went silent"), "{err:#}");
    }

    /// A heartbeat renders nothing, but it proves the connection is alive, so
    /// it has to reset the idle deadline.
    #[tokio::test]
    async fn a_heartbeat_counts_as_liveness() {
        let (end, seen) = drain(vec![
            chat_started(),
            ConversationStreamEvent::Ping,
            answer("hi"),
            workflow_finished(),
        ])
        .await;
        assert!(matches!(end, StreamEnd::Complete));
        // The ping itself stays invisible.
        assert!(!seen.iter().any(|e| matches!(e, AgentEvent::Unknown { .. })));
    }

    fn chat_finished() -> ConversationStreamEvent {
        ConversationStreamEvent::ChatFinished(longbridge::agent::ChatFinishedPayload::default())
    }

    /// Replaying a message that had already finished ends at `chat_finished`
    /// with no `workflow_finished` — the answer is all there, but the verdict
    /// has to be read back rather than assumed.
    #[tokio::test]
    async fn an_orderly_close_without_an_outcome_is_not_a_break() {
        let (end, _) = drain(vec![chat_started(), answer("hi"), chat_finished()]).await;
        assert!(matches!(end, StreamEnd::EndedWithoutOutcome));
    }

    /// When the outcome does arrive it wins: `chat_finished` precedes
    /// `workflow_finished` on a live stream, so the earlier marker must not
    /// downgrade a run that went on to report itself.
    #[tokio::test]
    async fn an_outcome_after_chat_finished_still_counts_as_complete() {
        let (end, _) = drain(vec![
            chat_started(),
            answer("hi"),
            chat_finished(),
            workflow_finished(),
        ])
        .await;
        assert!(matches!(end, StreamEnd::Complete));
    }

    /// The reconnect endpoint is addressed by path, and a gateway that does not
    /// serve it says so with 404000. Retrying that cannot help, so it has to be
    /// told apart from a request that merely failed.
    #[test]
    fn endpoint_missing_matches_only_404000() {
        let absent = HttpClientError::OpenApi {
            code: 404_000,
            message: "api not found".into(),
            trace_id: "t".into(),
        };
        assert!(endpoint_missing(&absent));
        let other = HttpClientError::OpenApi {
            code: 500_000,
            message: "internal".into(),
            trace_id: "t".into(),
        };
        assert!(!endpoint_missing(&other));
    }

    /// A message read back from history reports its outcome as a status code
    /// rather than the stream's wire string.
    #[test]
    fn recovered_status_maps_every_terminal_state() {
        assert_eq!(recovered_status(1), "succeeded");
        assert_eq!(recovered_status(2), "stopped");
        assert_eq!(recovered_status(5), "interrupted");
        assert_eq!(recovered_status(3), "failed");
        assert_eq!(recovered_status(4), "failed");
        // A status this client has not learned yet is not assumed to be good.
        assert_eq!(recovered_status(99), "failed");
    }

    /// Re-attaching replays the message from the beginning, so an aggregate
    /// that kept the dead connection's partial answer would double its prefix.
    #[test]
    fn a_restart_discards_what_the_dead_connection_delivered() {
        let mut agg = crate::cli::agent::events::ChatAggregator::default();
        agg.push(&AgentEvent::AnswerDelta {
            text: "Tencent's rev".into(),
        });
        agg.push(&AgentEvent::StreamInterrupted);
        agg.push(&AgentEvent::AnswerDelta {
            text: "Tencent's revenue grew 13%.".into(),
        });
        assert_eq!(agg.answer(), "Tencent's revenue grew 13%.");
    }

    #[test]
    fn is_rate_limited_matches_only_429002() {
        use longbridge::httpclient::HttpClientError;
        let limited = longbridge::Error::HttpClient(HttpClientError::OpenApi {
            code: 429_002,
            message: "api request is limited".into(),
            trace_id: "t".into(),
        });
        assert!(is_rate_limited(&limited));
        let other = longbridge::Error::HttpClient(HttpClientError::OpenApi {
            code: 429_001,
            message: "not the rate limit code".into(),
            trace_id: "t".into(),
        });
        assert!(!is_rate_limited(&other));
    }

    #[test]
    fn status_str_maps_every_variant() {
        assert_eq!(status_str(ConversationStatus::Succeeded), "succeeded");
        assert_eq!(status_str(ConversationStatus::Interrupted), "interrupted");
        assert_eq!(status_str(ConversationStatus::Failed), "failed");
        assert_eq!(status_str(ConversationStatus::Stopped), "stopped");
    }

    #[test]
    fn workflow_finished_maps_status_and_outputs() {
        use longbridge::agent::{ConversationResponse, Reference};
        let resp = ConversationResponse {
            chat_uid: "c1".into(),
            message_id: "42".into(),
            status: ConversationStatus::Succeeded,
            answer: "hi".into(),
            references: Some(vec![Reference {
                index: 1,
                original_index: 3,
                ref_type: "NewsArticle".into(),
                id: "n1".into(),
                title: String::new(),
                url: String::new(),
                // The real nested content the footer/JSON reads from.
                content: Some(serde_json::json!({
                    "source": "Zhitong",
                    "published_at": "2026-08-10T03:45:02Z",
                })),
            }]),
            further_questions: Some(vec!["What next?".into()]),
            elapsed_time: 1.5,
            interrupt: None,
            error: None,
        };
        let Some(AgentEvent::WorkflowFinished {
            status,
            references,
            further_questions,
            elapsed_time,
            error_message,
        }) = map_event(ConversationStreamEvent::WorkflowFinished(resp))
        else {
            panic!("expected WorkflowFinished");
        };
        assert_eq!(status, "succeeded");
        assert_eq!(elapsed_time, Some(1.5));
        assert!(error_message.is_empty());
        assert_eq!(references[0].index, 1);
        // The nested `content` must survive so the References footer renders.
        assert_eq!(references[0].content.as_ref().unwrap()["source"], "Zhitong");
        assert_eq!(further_questions[0], "What next?");
    }

    #[test]
    fn human_interaction_maps_to_interrupt_value() {
        use longbridge::agent::{ConversationResponse, Interrupt, Question, QuestionOption};
        let resp = ConversationResponse {
            chat_uid: "c1".into(),
            message_id: "42".into(),
            status: ConversationStatus::Interrupted,
            answer: String::new(),
            references: None,
            further_questions: None,
            elapsed_time: 0.0,
            interrupt: Some(Interrupt {
                node_id: "n".into(),
                tool_call_id: "call_a".into(),
                questions: vec![Question {
                    question: "Which period?".into(),
                    options: vec![QuestionOption {
                        label: "1w".into(),
                        description: "1w".into(),
                    }],
                    multi_select: false,
                }],
                interactions: vec![],
                message_id: 42,
                chat_id: 1,
            }),
            error: None,
        };
        let Some(AgentEvent::HumanInteractionRequired { interrupt }) =
            map_event(ConversationStreamEvent::HumanInteractionRequired(resp))
        else {
            panic!("expected HumanInteractionRequired");
        };
        assert_eq!(interrupt["tool_call_id"], "call_a");
        assert_eq!(interrupt["questions"][0]["question"], "Which period?");
        assert_eq!(interrupt["questions"][0]["options"][0]["description"], "1w");
    }

    #[test]
    fn progress_only_events_are_dropped() {
        assert!(map_event(ConversationStreamEvent::Ping).is_none());
    }

    #[test]
    fn message_type_routes_answer_vs_process() {
        use longbridge::agent::MessagePayload;
        let answer = MessagePayload {
            text: "a".into(),
            message_type: "answer".into(),
            ..Default::default()
        };
        assert!(matches!(
            map_event(ConversationStreamEvent::Message(answer)),
            Some(AgentEvent::AnswerDelta { .. })
        ));
        let think = MessagePayload {
            text: "t".into(),
            message_type: "think".into(),
            ..Default::default()
        };
        assert!(matches!(
            map_event(ConversationStreamEvent::Message(think)),
            Some(AgentEvent::ThinkingDelta { .. })
        ));
        // A stage boundary names itself instead of carrying reasoning.
        let stage = MessagePayload {
            message_type: "process".into(),
            stage_title: "Reading filings".into(),
            ..Default::default()
        };
        assert!(matches!(
            map_event(ConversationStreamEvent::Message(stage)),
            Some(AgentEvent::StageStarted { title }) if title == "Reading filings"
        ));
        // An empty progress message repeats a stage already announced.
        let empty = MessagePayload {
            message_type: "process".into(),
            ..Default::default()
        };
        assert!(map_event(ConversationStreamEvent::Message(empty)).is_none());
    }

    #[test]
    fn agent_info_deserializes_from_api_shape() {
        let json = serde_json::json!({
            "uid": "chatbot", "name": "LongbridgeAI", "mode": "chat",
            "is_published": true, "created_at": 1, "updated_at": 2
        });
        let a: AgentInfo = serde_json::from_value(json).unwrap();
        assert_eq!(a.uid, "chatbot");
        assert!(a.is_published);
        assert_eq!(a.workspace_id, ""); // filled later by traversal
        assert_eq!(a.description, ""); // optional in API
    }

    #[test]
    fn workspace_info_deserializes() {
        let json =
            serde_json::json!({"id": "33", "name": "Longbridge", "created_at": 0, "updated_at": 0});
        let w: WorkspaceInfo = serde_json::from_value(json).unwrap();
        assert_eq!(w.id, "33");
    }
}