[mypy]
ignore_missing_imports = True
exclude = ^(build|dist|eaqts\.egg-info|\.eggs)/
disable_error_code = import-untyped, import-not-found, var-annotated, no-redef, assignment, misc, operator, union-attr, attr-defined, arg-type, call-overload, has-type, call-arg
