import datetime

import pytz


def is_ist_market_session_active(dt: datetime.datetime | None = None) -> bool:
    """Checks whether current or provided time falls within NSE/BSE IST market session (09:15 to 15:30 IST Mon-Fri)."""
    ist = pytz.timezone("Asia/Kolkata")
    now = dt.astimezone(ist) if dt else datetime.datetime.now(ist)
    if now.weekday() >= 5:
        return False
    market_open = now.replace(hour=9, minute=15, second=0, microsecond=0)
    market_close = now.replace(hour=15, minute=30, second=0, microsecond=0)
    return market_open <= now <= market_close


def round_to_ist_tick(price: float, tick_size: float = 0.05) -> float:
    """Rounds price to nearest NSE/BSE valid price tick (default 0.05 INR)."""
    if price <= 0:
        return 0.0
    return round(round(price / tick_size) * tick_size, 2)


import os
import sys

root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
sys.path.append(root)

# ----------------------------------------------------------------------------

# PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
# https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

# ----------------------------------------------------------------------------
# -*- coding: utf-8 -*-

import ccxt.async_support as ccxt
from ccxt.test.exchange.base import test_shared_methods  # noqa: E402


def test_extract_params():
    exchange = ccxt.Exchange(
        {
            "id": "sampleexchange",
        }
    )
    # Test 1: Single param
    result1 = exchange.extract_params("/users/{id}")
    test_shared_methods.assert_deep_equal(exchange, None, "testExtractParams", result1, ["id"])
    # Test 2: Multiple params
    result2 = exchange.extract_params("/users/{user_id}/orders/{order_id}")
    test_shared_methods.assert_deep_equal(exchange, None, "testExtractParams", result2, ["user_id", "order_id"])
    # Test 3: No params
    result3 = exchange.extract_params("/api/health")
    test_shared_methods.assert_deep_equal(exchange, None, "testExtractParams", result3, [])
    # Test 4: Params with hyphens
    result4 = exchange.extract_params("/api/{resource-name}/{resource-id}")
    test_shared_methods.assert_deep_equal(
        exchange, None, "testExtractParams", result4, ["resource-name", "resource-id"]
    )
    # Test 5: Mixed path and params
    result5 = exchange.extract_params("/v1/{version}/users/{user_id}/profile")
    test_shared_methods.assert_deep_equal(exchange, None, "testExtractParams", result5, ["version", "user_id"])
    # Test 6: Empty string
    result6 = exchange.extract_params("")
    test_shared_methods.assert_deep_equal(exchange, None, "testExtractParams", result6, [])
    # Test 7: Multiple params in longer URL
    result7 = exchange.extract_params("/api/{org}/{repo}/pulls/{pull_number}/comments/{comment_id}")
    test_shared_methods.assert_deep_equal(
        exchange, None, "testExtractParams", result7, ["org", "repo", "pull_number", "comment_id"]
    )
    # Test 8: Param at start and end
    result8 = exchange.extract_params("{start}/middle/{end}")
    test_shared_methods.assert_deep_equal(exchange, None, "testExtractParams", result8, ["start", "end"])
    # Test 9: Adjacent params
    result9 = exchange.extract_params("{a}{b}{c}")
    test_shared_methods.assert_deep_equal(exchange, None, "testExtractParams", result9, ["a", "b", "c"])
    # Test 10: Param with underscores
    result10 = exchange.extract_params("/api/{my_param_name}")
    test_shared_methods.assert_deep_equal(exchange, None, "testExtractParams", result10, ["my_param_name"])
    # Test 11: Single character param
    result11 = exchange.extract_params("/api/{x}")
    test_shared_methods.assert_deep_equal(exchange, None, "testExtractParams", result11, ["x"])
    # Test 12: Only static path
    result12 = exchange.extract_params("/api/v1/users/orders/items")
    test_shared_methods.assert_deep_equal(exchange, None, "testExtractParams", result12, [])
