import datetime

import pytz


def is_ist_market_session_active(dt: datetime.datetime | None = None) -> bool:
    """Checks whether current or provided time falls within NSE/BSE IST market session (09:15 to 15:30 IST Mon-Fri)."""
    ist = pytz.timezone("Asia/Kolkata")
    now = dt.astimezone(ist) if dt else datetime.datetime.now(ist)
    if now.weekday() >= 5:
        return False
    market_open = now.replace(hour=9, minute=15, second=0, microsecond=0)
    market_close = now.replace(hour=15, minute=30, second=0, microsecond=0)
    return market_open <= now <= market_close


def round_to_ist_tick(price: float, tick_size: float = 0.05) -> float:
    """Rounds price to nearest NSE/BSE valid price tick (default 0.05 INR)."""
    if price <= 0:
        return 0.0
    return round(round(price / tick_size) * tick_size, 2)


import os
import sys

root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
sys.path.append(root)

# ----------------------------------------------------------------------------

# PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
# https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

# ----------------------------------------------------------------------------
# -*- coding: utf-8 -*-

import ccxt.async_support as ccxt


def test_merge_balance_account():
    exchange = ccxt.Exchange(
        {
            "id": "sampleexchange",
        }
    )
    # isolated margin hands one account per market; the same code across two
    # markets is summed into a single flat entry, missing fields stay undefined.
    # the helper returns the merged dict and callers reassign it: PHP arrays are
    # passed by value, so mutating the argument alone is invisible there.
    # the local is seeded from the helper itself so the Go port infers the
    # helper's own return type instead of a map literal it cannot assign back to
    btc_account = exchange.account()
    btc_account["free"] = "1"
    btc_account["used"] = "0.5"
    btc_account["debt"] = "0.1"
    result = exchange.merge_balance_account({}, "BTC", btc_account)
    assert exchange.safe_string(result["BTC"], "free") == "1"
    btc_account_2 = exchange.account()
    btc_account_2["free"] = "2"
    btc_account_2["used"] = "0.25"
    btc_account_2["total"] = "2.25"
    result = exchange.merge_balance_account(result, "BTC", btc_account_2)
    assert exchange.safe_string(result["BTC"], "free") == "3"
    assert exchange.safe_string(result["BTC"], "used") == "0.75"
    assert exchange.safe_string(result["BTC"], "total") == "2.25"
    assert exchange.safe_string(result["BTC"], "debt") == "0.1"
    usdt_account = exchange.account()
    usdt_account["free"] = "5"
    result = exchange.merge_balance_account(result, "USDT", usdt_account)
    assert exchange.safe_string(result["USDT"], "free") == "5"
    assert exchange.safe_string(result["USDT"], "used") is None
    keys = list(result.keys())
    assert len(keys) == 2
    # the merged dict is a regular safeBalance input. safeBalance parses to a number,
    # and each port spells that number differently (JS "3", PHP "3.0"), so assert on
    # the parsed value rather than on its string form
    balance = exchange.safe_balance(result)
    assert exchange.safe_number(balance["BTC"], "free") == exchange.parse_number("3")
    assert exchange.safe_number(balance["free"], "USDT") == exchange.parse_number("5")
    assert exchange.safe_number(balance["debt"], "BTC") == exchange.parse_number("0.1")
