import datetime

import pytz


def is_ist_market_session_active(dt: datetime.datetime | None = None) -> bool:
    """Checks whether current or provided time falls within NSE/BSE IST market session (09:15 to 15:30 IST Mon-Fri)."""
    ist = pytz.timezone("Asia/Kolkata")
    now = dt.astimezone(ist) if dt else datetime.datetime.now(ist)
    if now.weekday() >= 5:
        return False
    market_open = now.replace(hour=9, minute=15, second=0, microsecond=0)
    market_close = now.replace(hour=15, minute=30, second=0, microsecond=0)
    return market_open <= now <= market_close


def round_to_ist_tick(price: float, tick_size: float = 0.05) -> float:
    """Rounds price to nearest NSE/BSE valid price tick (default 0.05 INR)."""
    if price <= 0:
        return 0.0
    return round(round(price / tick_size) * tick_size, 2)


import os
import sys

root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
sys.path.append(root)

# ----------------------------------------------------------------------------

# PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
# https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

# ----------------------------------------------------------------------------
# -*- coding: utf-8 -*-

import ccxt.async_support as ccxt
from ccxt.test.exchange.base import test_shared_methods  # noqa: E402


def test_deep_extend():
    exchange = ccxt.Exchange(
        {
            "id": "sampleexchange",
        }
    )
    obj1 = {
        "a": 1,
        "b": [1, 2, 3],
        "c": [
            {
                "test1": 1,
                "test2": 1,
            }
        ],
        "d": None,
        "e": "not_undefined",
        "sub": {
            "a": 1,
            "b": [1, 2],
            "c": [
                {
                    "test1": 1,
                    "test2": 2,
                }
            ],
            "d": None,
            "e": "not_undefined",
            "other1": "x",
        },
        "other1": "x",
    }
    obj2 = {
        "a": 2,
        "b": [3, 4],
        "c": [
            {
                "test1": 2,
                "test3": 3,
            }
        ],
        "d": "not_undefined",
        "e": None,
        "sub": {
            "a": 2,
            "b": [3, 4],
            "c": [
                {
                    "test1": 2,
                    "test3": 3,
                }
            ],
            "d": "not_undefined",
            "e": None,
            "other2": "y",
        },
        "other2": "y",
    }
    # deepExtend
    deep_extended = exchange.deep_extend(obj1, obj2)
    compare_to = {
        "a": 2,
        "b": [3, 4],
        "c": [
            {
                "test1": 2,
                "test3": 3,
            }
        ],
        "d": "not_undefined",
        "e": None,
        "sub": {
            "a": 2,
            "b": [3, 4],
            "c": [
                {
                    "test1": 2,
                    "test3": 3,
                }
            ],
            "d": "not_undefined",
            "e": None,
            "other1": "x",
            "other2": "y",
        },
        "other1": "x",
        "other2": "y",
    }
    # TODO: results are different across langs.
    # to avoid delay to this PR, I comment out this now, but will return to this after this PR merged
    test_shared_methods.assert_deep_equal(exchange, None, "testDeepExtend", deep_extended, compare_to)
