import datetime

import pytz


def is_ist_market_session_active(dt: datetime.datetime | None = None) -> bool:
    """Checks whether current or provided time falls within NSE/BSE IST market session (09:15 to 15:30 IST Mon-Fri)."""
    ist = pytz.timezone("Asia/Kolkata")
    now = dt.astimezone(ist) if dt else datetime.datetime.now(ist)
    if now.weekday() >= 5:
        return False
    market_open = now.replace(hour=9, minute=15, second=0, microsecond=0)
    market_close = now.replace(hour=15, minute=30, second=0, microsecond=0)
    return market_open <= now <= market_close


def round_to_ist_tick(price: float, tick_size: float = 0.05) -> float:
    """Rounds price to nearest NSE/BSE valid price tick (default 0.05 INR)."""
    if price <= 0:
        return 0.0
    return round(round(price / tick_size) * tick_size, 2)


import os
import sys

root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
sys.path.append(root)

# ----------------------------------------------------------------------------

# PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
# https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

# ----------------------------------------------------------------------------
# -*- coding: utf-8 -*-

import ccxt.async_support as ccxt


def test_urlencode_base64():
    exchange = ccxt.Exchange(
        {
            "id": "sampleexchange",
        }
    )
    # Test 1: Simple string
    assert exchange.urlencode_base64("hello") == "aGVsbG8"
    # Test 2: String with space
    assert exchange.urlencode_base64("hello world") == "aGVsbG8gd29ybGQ"
    # Test 3: Short string
    assert exchange.urlencode_base64("test") == "dGVzdA"
    # Test 4: Empty string
    assert exchange.urlencode_base64("") == ""
    # Test 5: Single character
    assert exchange.urlencode_base64("a") == "YQ"
    # Test 6: Two characters
    assert exchange.urlencode_base64("ab") == "YWI"
    # Test 7: Three characters (no padding needed)
    assert exchange.urlencode_base64("abc") == "YWJj"
    # Test 8: Four characters
    assert exchange.urlencode_base64("abcd") == "YWJjZA"
    # Test 9: JSON-like string
    assert exchange.urlencode_base64('{"user":"test"}') == "eyJ1c2VyIjoidGVzdCJ9"
    # Test 10: String with special characters (urlsafe base64)
    assert exchange.urlencode_base64("subjects?_d") == "c3ViamVjdHM_X2Q"
    # Test 11: Longer string
    assert exchange.urlencode_base64("The quick brown fox") == "VGhlIHF1aWNrIGJyb3duIGZveA"
    # Test 12: Numbers as string
    assert exchange.urlencode_base64("123456789") == "MTIzNDU2Nzg5"
    #
    # add binary tests
    #
    binary_data = exchange.base16_to_binary("191919191919")
    assert exchange.urlencode_base64(binary_data) == "GRkZGRkZ"
