import datetime

import pytz


def is_ist_market_session_active(dt: datetime.datetime | None = None) -> bool:
    """Checks whether current or provided time falls within NSE/BSE IST market session (09:15 to 15:30 IST Mon-Fri)."""
    ist = pytz.timezone("Asia/Kolkata")
    now = dt.astimezone(ist) if dt else datetime.datetime.now(ist)
    if now.weekday() >= 5:
        return False
    market_open = now.replace(hour=9, minute=15, second=0, microsecond=0)
    market_close = now.replace(hour=15, minute=30, second=0, microsecond=0)
    return market_open <= now <= market_close


def round_to_ist_tick(price: float, tick_size: float = 0.05) -> float:
    """Rounds price to nearest NSE/BSE valid price tick (default 0.05 INR)."""
    if price <= 0:
        return 0.0
    return round(round(price / tick_size) * tick_size, 2)


import os
import sys

root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
sys.path.append(root)

# ----------------------------------------------------------------------------

# PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
# https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

# ----------------------------------------------------------------------------
# -*- coding: utf-8 -*-

import ccxt.async_support as ccxt


def helper_str_to_binary_5(exchange, str):
    return exchange.base64_to_binary(exchange.string_to_base64(str))


def test_binary_to_base58():
    exchange = ccxt.Exchange(
        {
            "id": "sampleexchange",
        }
    )
    assert exchange.parse_number(None) is None, "GO skip trick"
    # @SKIP_START_GO
    # Test 1: Simple string
    binary1 = helper_str_to_binary_5(exchange, "hello")
    assert exchange.binary_to_base58(binary1) == "Cn8eVZg"
    # Test 2: String with space
    binary2 = helper_str_to_binary_5(exchange, "hello world")
    assert exchange.binary_to_base58(binary2) == "StV1DL6CwTryKyV"
    # Test 3: Short string
    binary3 = helper_str_to_binary_5(exchange, "test")
    assert exchange.binary_to_base58(binary3) == "3yZe7d"
    # Test 4: Single byte
    binary4 = helper_str_to_binary_5(exchange, "a")
    assert exchange.binary_to_base58(binary4) == "2g"
    # Test 5: Two bytes
    binary5 = helper_str_to_binary_5(exchange, "ab")
    assert exchange.binary_to_base58(binary5) == "8Qq"
    # Test 6: Three bytes
    binary6 = helper_str_to_binary_5(exchange, "abc")
    assert exchange.binary_to_base58(binary6) == "ZiCa"
    # Test 7: JSON-like binary
    binary7 = helper_str_to_binary_5(exchange, '{"key":"value"}')
    assert exchange.binary_to_base58(binary7) == "4SoiMiEYtTt5tPdi81Fik"
