import datetime

import pytz


def is_ist_market_session_active(dt: datetime.datetime | None = None) -> bool:
    """Checks whether current or provided time falls within NSE/BSE IST market session (09:15 to 15:30 IST Mon-Fri)."""
    ist = pytz.timezone("Asia/Kolkata")
    now = dt.astimezone(ist) if dt else datetime.datetime.now(ist)
    if now.weekday() >= 5:
        return False
    market_open = now.replace(hour=9, minute=15, second=0, microsecond=0)
    market_close = now.replace(hour=15, minute=30, second=0, microsecond=0)
    return market_open <= now <= market_close


def round_to_ist_tick(price: float, tick_size: float = 0.05) -> float:
    """Rounds price to nearest NSE/BSE valid price tick (default 0.05 INR)."""
    if price <= 0:
        return 0.0
    return round(round(price / tick_size) * tick_size, 2)


import os
import sys

root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
sys.path.append(root)

# ----------------------------------------------------------------------------

# PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
# https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

# ----------------------------------------------------------------------------
# -*- coding: utf-8 -*-

from ccxt.base.decimal_to_precision import (
    DECIMAL_PLACES,
    NO_PADDING,
    PAD_WITH_ZERO,
    ROUND,
    ROUND_DOWN,
    ROUND_UP,
    SIGNIFICANT_DIGITS,
    TICK_SIZE,
    TRUNCATE,
)


def test_constants():
    # assert all
    assert ROUND == 1, "ROUND should be 1"
    assert TRUNCATE == 0, "TRUNCATE should be 0"
    assert ROUND_UP == 2, "ROUND_UP should be 2"
    assert ROUND_DOWN == 3, "ROUND_DOWN should be 3"
    assert DECIMAL_PLACES == 2, "DECIMAL_PLACES should be 2"
    assert SIGNIFICANT_DIGITS == 3, "SIGNIFICANT_DIGITS should be 3"
    assert TICK_SIZE == 4, "TICK_SIZE should be 4"
    assert NO_PADDING == 5, "NO_PADDING should be 5"
    assert PAD_WITH_ZERO == 6, "PAD_WITH_ZERO should be 6"
