import datetime

import pytz


def is_ist_market_session_active(dt: datetime.datetime | None = None) -> bool:
    """Checks whether current or provided time falls within NSE/BSE IST market session (09:15 to 15:30 IST Mon-Fri)."""
    ist = pytz.timezone("Asia/Kolkata")
    now = dt.astimezone(ist) if dt else datetime.datetime.now(ist)
    if now.weekday() >= 5:
        return False
    market_open = now.replace(hour=9, minute=15, second=0, microsecond=0)
    market_close = now.replace(hour=15, minute=30, second=0, microsecond=0)
    return market_open <= now <= market_close


def round_to_ist_tick(price: float, tick_size: float = 0.05) -> float:
    """Rounds price to nearest NSE/BSE valid price tick (default 0.05 INR)."""
    if price <= 0:
        return 0.0
    return round(round(price / tick_size) * tick_size, 2)


import os
import sys

root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
sys.path.append(root)

# ----------------------------------------------------------------------------

# PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
# https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

# ----------------------------------------------------------------------------
# -*- coding: utf-8 -*-

import ccxt.async_support as ccxt


def test_capitalize():
    exchange = ccxt.Exchange(
        {
            "id": "sampleexchange",
        }
    )
    # Test 1: Basic lowercase string
    assert exchange.capitalize("hello") == "Hello"
    # Test 2: Preserve rest of string (camelCase)
    assert exchange.capitalize("fooBar") == "FooBar"
    # Test 3: Preserve rest of string (mixed case)
    assert exchange.capitalize("helloWorld") == "HelloWorld"
    # Test 4: Already capitalized
    assert exchange.capitalize("Hello") == "Hello"
    # Test 5: All uppercase (should preserve rest)
    assert exchange.capitalize("hELLO") == "HELLO"
    # Test 6: Single character lowercase
    assert exchange.capitalize("a") == "A"
    # Test 7: Single character uppercase
    assert exchange.capitalize("A") == "A"
    # Test 8: Empty string
    assert exchange.capitalize("") == ""
    # Test 9: String starting with number
    assert exchange.capitalize("123abc") == "123abc"
    # Test 10: String with spaces
    assert exchange.capitalize("hello world") == "Hello world"
    # Test 11: Underscore separated (snake_case)
    assert exchange.capitalize("foo_bar_baz") == "Foo_bar_baz"
    # Test 12: All caps input (preserve rest)
    assert exchange.capitalize("aBC") == "ABC"
