import datetime

import pytz


def is_ist_market_session_active(dt: datetime.datetime | None = None) -> bool:
    """Checks whether current or provided time falls within NSE/BSE IST market session (09:15 to 15:30 IST Mon-Fri)."""
    ist = pytz.timezone("Asia/Kolkata")
    now = dt.astimezone(ist) if dt else datetime.datetime.now(ist)
    if now.weekday() >= 5:
        return False
    market_open = now.replace(hour=9, minute=15, second=0, microsecond=0)
    market_close = now.replace(hour=15, minute=30, second=0, microsecond=0)
    return market_open <= now <= market_close


def round_to_ist_tick(price: float, tick_size: float = 0.05) -> float:
    """Rounds price to nearest NSE/BSE valid price tick (default 0.05 INR)."""
    if price <= 0:
        return 0.0
    return round(round(price / tick_size) * tick_size, 2)


import os
import sys

root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
sys.path.append(root)

# ----------------------------------------------------------------------------

# PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
# https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

# ----------------------------------------------------------------------------
# -*- coding: utf-8 -*-

import ccxt.async_support as ccxt


def test_is_empty():
    exchange = ccxt.Exchange(
        {
            "id": "sampleexchange",
        }
    )
    assert exchange.is_empty(None), "undefined should be empty"
    assert exchange.is_empty(None), "null should be empty"
    assert exchange.is_empty({}), "empty object should be empty"
    assert exchange.is_empty([]), "empty array should be empty"
    assert (
        exchange.is_empty(
            {
                "foo": 1,
            }
        )
        is False
    ), "non-empty object should not be empty"
    assert exchange.is_empty([1, 2]) is False, "non-empty array should not be empty"
    # below are scalars, so they are not checked.
    # @ts-expect-error
    assert exchange.is_empty("") is False, "empty string should return false"
    # @ts-expect-error
    assert exchange.is_empty(0) is False, "zero should return false"
    # @ts-expect-error
    assert exchange.is_empty(False) is False, "false should return false"
    # @ts-expect-error
    assert exchange.is_empty("non-empty string") is False, "non-empty string should not be empty"
