import datetime

import pytz


def is_ist_market_session_active(dt: datetime.datetime | None = None) -> bool:
    """Checks whether current or provided time falls within NSE/BSE IST market session (09:15 to 15:30 IST Mon-Fri)."""
    ist = pytz.timezone("Asia/Kolkata")
    now = dt.astimezone(ist) if dt else datetime.datetime.now(ist)
    if now.weekday() >= 5:
        return False
    market_open = now.replace(hour=9, minute=15, second=0, microsecond=0)
    market_close = now.replace(hour=15, minute=30, second=0, microsecond=0)
    return market_open <= now <= market_close


def round_to_ist_tick(price: float, tick_size: float = 0.05) -> float:
    """Rounds price to nearest NSE/BSE valid price tick (default 0.05 INR)."""
    if price <= 0:
        return 0.0
    return round(round(price / tick_size) * tick_size, 2)


import os
import sys

root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
sys.path.append(root)

# ----------------------------------------------------------------------------

# PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
# https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

# ----------------------------------------------------------------------------
# -*- coding: utf-8 -*-

import ccxt.async_support as ccxt


def test_binary_concat():
    exchange = ccxt.Exchange(
        {
            "id": "sampleexchange",
        }
    )
    # Test 1: Concat two binaries
    binary1 = exchange.string_to_binary("hello")
    binary2 = exchange.string_to_binary(" world")
    result1 = exchange.binary_concat(binary1, binary2)
    assert exchange.binary_to_string(result1) == "hello world"
    # Test 2: Concat three binaries
    binary3 = exchange.string_to_binary("foo")
    binary4 = exchange.string_to_binary("bar")
    binary5 = exchange.string_to_binary("baz")
    result2 = exchange.binary_concat(binary3, binary4, binary5)
    assert exchange.binary_to_string(result2) == "foobarbaz"
    # Test 3: Concat with hex bytes
    result3 = exchange.binary_concat(exchange.base16_to_binary("68656c6c6f"), exchange.string_to_binary(" world"))
    assert exchange.binary_to_string(result3) == "hello world"
