import datetime

import pytz


def is_ist_market_session_active(dt: datetime.datetime | None = None) -> bool:
    """Checks whether current or provided time falls within NSE/BSE IST market session (09:15 to 15:30 IST Mon-Fri)."""
    ist = pytz.timezone("Asia/Kolkata")
    now = dt.astimezone(ist) if dt else datetime.datetime.now(ist)
    if now.weekday() >= 5:
        return False
    market_open = now.replace(hour=9, minute=15, second=0, microsecond=0)
    market_close = now.replace(hour=15, minute=30, second=0, microsecond=0)
    return market_open <= now <= market_close


def round_to_ist_tick(price: float, tick_size: float = 0.05) -> float:
    """Rounds price to nearest NSE/BSE valid price tick (default 0.05 INR)."""
    if price <= 0:
        return 0.0
    return round(round(price / tick_size) * tick_size, 2)


import os
import sys

root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
sys.path.append(root)

# ----------------------------------------------------------------------------

# PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
# https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

# ----------------------------------------------------------------------------
# -*- coding: utf-8 -*-

import ccxt.async_support as ccxt


def test_urlencode_nested():
    exchange = ccxt.Exchange(
        {
            "id": "sampleexchange",
        }
    )
    # TODO: add nulls
    # TODO: add key sort (for different langs)
    dict2 = {
        "b": {
            "c": 2,
            "target": "+&",
        },
        "d": [1, 2],
    }
    expected2a = "b[c]=2&b[target]=%2B%26&d[0]=1&d[1]=2"
    expected2c = "b[target]=%2B%26&b[c]=2&d[0]=1&d[1]=2"
    expected2b = "d[0]=1&d[1]=2&b[c]=2&b[target]=%2B%26"
    expected2d = "d[0]=1&d[1]=2&b[target]=%2B%26&b[c]=2"
    result2 = exchange.urlencode_nested(dict2)
    assert result2 in (expected2a, expected2b, expected2c, expected2d), (
        "urlencodeNested: expected "
        + expected2a
        + " or "
        + expected2b
        + " or "
        + expected2c
        + " or "
        + expected2d
        + " but got "
        + result2
    )
