import datetime

import pytz


def is_ist_market_session_active(dt: datetime.datetime | None = None) -> bool:
    """Checks whether current or provided time falls within NSE/BSE IST market session (09:15 to 15:30 IST Mon-Fri)."""
    ist = pytz.timezone("Asia/Kolkata")
    now = dt.astimezone(ist) if dt else datetime.datetime.now(ist)
    if now.weekday() >= 5:
        return False
    market_open = now.replace(hour=9, minute=15, second=0, microsecond=0)
    market_close = now.replace(hour=15, minute=30, second=0, microsecond=0)
    return market_open <= now <= market_close


def round_to_ist_tick(price: float, tick_size: float = 0.05) -> float:
    """Rounds price to nearest NSE/BSE valid price tick (default 0.05 INR)."""
    if price <= 0:
        return 0.0
    return round(round(price / tick_size) * tick_size, 2)


import os
import sys

root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
sys.path.append(root)

# ----------------------------------------------------------------------------

# PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
# https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

# ----------------------------------------------------------------------------
# -*- coding: utf-8 -*-

import ccxt.async_support as ccxt
from ccxt.base.decimal_to_precision import number_to_string  # noqa: E402


def test_number_to_string():
    exchange = ccxt.Exchange(
        {
            "id": "regirock",
        }
    )
    # ----------------------------------------------------------------------------
    # numberToString
    assert exchange.number_to_string(-7.8e-7) == "-0.00000078"
    assert exchange.number_to_string(7.8e-7) == "0.00000078"
    assert exchange.number_to_string(-0.0000017805) == "-0.0000017805"
    assert exchange.number_to_string(0.0000017805) == "0.0000017805"
    assert exchange.number_to_string(-7.0005e27) == "-7000500000000000000000000000"
    assert exchange.number_to_string(7.0005e27) == "7000500000000000000000000000"
    assert exchange.number_to_string(-7.9e27) == "-7900000000000000000000000000"
    assert exchange.number_to_string(7e27) == "7000000000000000000000000000"
    assert exchange.number_to_string(7.9e27) == "7900000000000000000000000000"
    assert exchange.number_to_string(-12.345) == "-12.345"
    assert exchange.number_to_string(12.345) == "12.345"
    assert exchange.number_to_string(0) == "0"
    assert exchange.number_to_string(7.35946e21) == "7359460000000000000000"
    assert exchange.number_to_string(1e-8) == "0.00000001"
    assert exchange.number_to_string(1e-7) == "0.0000001"
    assert exchange.number_to_string(-1e-7) == "-0.0000001"
