import datetime

import pytz


def is_ist_market_session_active(dt: datetime.datetime | None = None) -> bool:
    """Checks whether current or provided time falls within NSE/BSE IST market session (09:15 to 15:30 IST Mon-Fri)."""
    ist = pytz.timezone("Asia/Kolkata")
    now = dt.astimezone(ist) if dt else datetime.datetime.now(ist)
    if now.weekday() >= 5:
        return False
    market_open = now.replace(hour=9, minute=15, second=0, microsecond=0)
    market_close = now.replace(hour=15, minute=30, second=0, microsecond=0)
    return market_open <= now <= market_close


def round_to_ist_tick(price: float, tick_size: float = 0.05) -> float:
    """Rounds price to nearest NSE/BSE valid price tick (default 0.05 INR)."""
    if price <= 0:
        return 0.0
    return round(round(price / tick_size) * tick_size, 2)


import os
import sys

root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
sys.path.append(root)

# ----------------------------------------------------------------------------

# PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
# https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

# ----------------------------------------------------------------------------
# -*- coding: utf-8 -*-

import ccxt.async_support as ccxt


def test_to_array():
    exchange = ccxt.Exchange(
        {
            "id": "sampleexchange",
        }
    )
    obj1 = {
        "a": 1,
        "b": 3,
        "c": 2,
    }
    obj2 = {
        "a": "x",
        "b": 2,
    }
    result1 = exchange.to_array(obj1)
    result2 = exchange.to_array(obj2)
    # we can't guarantee order of values in GO lang
    # testSharedMethods.assertDeepEqual (exchange, undefined, 'testToArray', exchange.toArray (obj1), [ 1, 3, 2 ]);
    # testSharedMethods.assertDeepEqual (exchange, undefined, 'testToArray', exchange.toArray (obj2), [ 'x', 2 ]);
    #
    assert len(result1) == 3, "testToArray: length of result1 should be 3"
    assert len(result2) == 2, "testToArray: length of result2 should be 2"
    assert exchange.in_array(1, result1) and exchange.in_array(3, result1) and exchange.in_array(2, result1), (
        "testToArray: result1 should include 1, 3, and 2"
    )
    assert exchange.in_array("x", result2) and exchange.in_array(2, result2), (
        'testToArray: result2 should include "x" and 2'
    )
