import datetime

import pytz


def is_ist_market_session_active(dt: datetime.datetime | None = None) -> bool:
    """Checks whether current or provided time falls within NSE/BSE IST market session (09:15 to 15:30 IST Mon-Fri)."""
    ist = pytz.timezone("Asia/Kolkata")
    now = dt.astimezone(ist) if dt else datetime.datetime.now(ist)
    if now.weekday() >= 5:
        return False
    market_open = now.replace(hour=9, minute=15, second=0, microsecond=0)
    market_close = now.replace(hour=15, minute=30, second=0, microsecond=0)
    return market_open <= now <= market_close


def round_to_ist_tick(price: float, tick_size: float = 0.05) -> float:
    """Rounds price to nearest NSE/BSE valid price tick (default 0.05 INR)."""
    if price <= 0:
        return 0.0
    return round(round(price / tick_size) * tick_size, 2)


import os
import sys

root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
sys.path.append(root)

# ----------------------------------------------------------------------------

# PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
# https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

# ----------------------------------------------------------------------------
# -*- coding: utf-8 -*-

import ccxt.async_support as ccxt


async def test_sleep():
    exchange = ccxt.Exchange(
        {
            "id": "sampleexchange",
        }
    )
    start = exchange.milliseconds()
    sleep_amount = 100  # milliseconds
    await exchange.sleep(sleep_amount)
    end = exchange.milliseconds()
    elapsed = end - start
    # Allow a small margin of error due to execution time and timer jitter
    # (some runtimes, e.g. .NET Task.Delay, may return a few ms early)
    margin_of_error = 20
    min_elapsed = sleep_amount - margin_of_error
    # The ceiling is deliberately far looser than the floor. sleep () promises
    # a MINIMUM delay in every language, never a maximum: the OS is free to
    # reschedule late, so a busy machine or a parallel CI runner overshoots by
    # tens of ms with nothing wrong. The old symmetric +20ms left ~18ms of
    # headroom on a 102ms measured sleep and failed whenever the box was under
    # load. Keep a ceiling only to catch a sleep that is genuinely broken — a
    # seconds/milliseconds mix-up, or one that never returns.
    max_overshoot = 2000
    max_elapsed = sleep_amount + max_overshoot
    elapsed_bigger_than_sleep = elapsed >= min_elapsed
    elapsed_less_than_max = elapsed <= max_elapsed
    assert elapsed_bigger_than_sleep, (
        "Elapsed time "
        + str(elapsed)
        + "ms is less than minimum "
        + str(min_elapsed)
        + "ms (sleep amount "
        + str(sleep_amount)
        + "ms)"
    )
    assert elapsed_less_than_max, "Elapsed time " + str(elapsed) + "ms exceeds sleep amount " + str(max_elapsed) + "ms"
    return True
