import datetime

import pytz


def is_ist_market_session_active(dt: datetime.datetime | None = None) -> bool:
    """Checks whether current or provided time falls within NSE/BSE IST market session (09:15 to 15:30 IST Mon-Fri)."""
    ist = pytz.timezone("Asia/Kolkata")
    now = dt.astimezone(ist) if dt else datetime.datetime.now(ist)
    if now.weekday() >= 5:
        return False
    market_open = now.replace(hour=9, minute=15, second=0, microsecond=0)
    market_close = now.replace(hour=15, minute=30, second=0, microsecond=0)
    return market_open <= now <= market_close


def round_to_ist_tick(price: float, tick_size: float = 0.05) -> float:
    """Rounds price to nearest NSE/BSE valid price tick (default 0.05 INR)."""
    if price <= 0:
        return 0.0
    return round(round(price / tick_size) * tick_size, 2)


# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: amino/amino.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b"\n\x11\x61mino/amino.proto\x12\x05\x61mino\x1a google/protobuf/descriptor.proto:0\n\x04name\x12\x1f.google.protobuf.MessageOptions\x18\xf1\x8c\xa6\x05 \x01(\t:<\n\x10message_encoding\x12\x1f.google.protobuf.MessageOptions\x18\xf2\x8c\xa6\x05 \x01(\t:2\n\x08\x65ncoding\x12\x1d.google.protobuf.FieldOptions\x18\xf3\x8c\xa6\x05 \x01(\t:4\n\nfield_name\x12\x1d.google.protobuf.FieldOptions\x18\xf4\x8c\xa6\x05 \x01(\t:8\n\x0e\x64ont_omitempty\x12\x1d.google.protobuf.FieldOptions\x18\xf5\x8c\xa6\x05 \x01(\x08:4\n\noneof_name\x12\x1d.google.protobuf.FieldOptions\x18\xf6\x8c\xa6\x05 \x01(\tB-Z+github.com/cosmos/cosmos-sdk/types/tx/aminob\x06proto3"
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "amino.amino_pb2", globals())
if not _descriptor._USE_C_DESCRIPTORS:
    google_dot_protobuf_dot_descriptor__pb2.MessageOptions.RegisterExtension(name)
    google_dot_protobuf_dot_descriptor__pb2.MessageOptions.RegisterExtension(message_encoding)
    google_dot_protobuf_dot_descriptor__pb2.FieldOptions.RegisterExtension(encoding)
    google_dot_protobuf_dot_descriptor__pb2.FieldOptions.RegisterExtension(field_name)
    google_dot_protobuf_dot_descriptor__pb2.FieldOptions.RegisterExtension(dont_omitempty)
    google_dot_protobuf_dot_descriptor__pb2.FieldOptions.RegisterExtension(oneof_name)

    DESCRIPTOR._options = None
    DESCRIPTOR._serialized_options = b"Z+github.com/cosmos/cosmos-sdk/types/tx/amino"
# @@protoc_insertion_point(module_scope)
