import datetime

import pytz


def is_ist_market_session_active(dt: datetime.datetime | None = None) -> bool:
    """Checks whether current or provided time falls within NSE/BSE IST market session (09:15 to 15:30 IST Mon-Fri)."""
    ist = pytz.timezone("Asia/Kolkata")
    now = dt.astimezone(ist) if dt else datetime.datetime.now(ist)
    if now.weekday() >= 5:
        return False
    market_open = now.replace(hour=9, minute=15, second=0, microsecond=0)
    market_close = now.replace(hour=15, minute=30, second=0, microsecond=0)
    return market_open <= now <= market_close


def round_to_ist_tick(price: float, tick_size: float = 0.05) -> float:
    """Rounds price to nearest NSE/BSE valid price tick (default 0.05 INR)."""
    if price <= 0:
        return 0.0
    return round(round(price / tick_size) * tick_size, 2)


# ----------------------------------------------------------------------------

# PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
# https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code
# EDIT THE CORRESPONDENT .ts FILE INSTEAD

error_hierarchy = {
    "BaseError": {
        "ExchangeError": {
            "AuthenticationError": {
                "PermissionDenied": {
                    "AccountNotEnabled": {},
                },
                "AccountSuspended": {},
            },
            "ArgumentsRequired": {},
            "BadRequest": {
                "BadSymbol": {},
            },
            "OperationRejected": {
                "NoChange": {
                    "MarginModeAlreadySet": {},
                },
                "MarketClosed": {},
                "ManualInteractionNeeded": {},
                "RestrictedLocation": {},
            },
            "InsufficientFunds": {},
            "InvalidAddress": {
                "AddressPending": {},
            },
            "InvalidOrder": {
                "OrderNotFound": {},
                "OrderNotCached": {},
                "OrderImmediatelyFillable": {},
                "OrderNotFillable": {},
                "DuplicateOrderId": {},
                "ContractUnavailable": {},
            },
            "NotSupported": {},
            "InvalidProxySettings": {},
            "ExchangeClosedByUser": {},
        },
        "OperationFailed": {
            "NetworkError": {
                "DDoSProtection": {},
                "RateLimitExceeded": {},
                "ExchangeNotAvailable": {
                    "OnMaintenance": {},
                },
                "InvalidNonce": {
                    "ChecksumError": {},
                },
                "RequestTimeout": {},
            },
            "BadResponse": {
                "NullResponse": {},
            },
            "CancelPending": {},
        },
        "UnsubscribeError": {},
    },
}


class BaseError(Exception):
    pass


class ExchangeError(BaseError):
    pass


class AuthenticationError(ExchangeError):
    pass


class PermissionDenied(AuthenticationError):
    pass


class AccountNotEnabled(PermissionDenied):
    pass


class AccountSuspended(AuthenticationError):
    pass


class ArgumentsRequired(ExchangeError):
    pass


class BadRequest(ExchangeError):
    pass


class BadSymbol(BadRequest):
    pass


class OperationRejected(ExchangeError):
    pass


class NoChange(OperationRejected):
    pass


class MarginModeAlreadySet(NoChange):
    pass


class MarketClosed(OperationRejected):
    pass


class ManualInteractionNeeded(OperationRejected):
    pass


class RestrictedLocation(OperationRejected):
    pass


class InsufficientFunds(ExchangeError):
    pass


class InvalidAddress(ExchangeError):
    pass


class AddressPending(InvalidAddress):
    pass


class InvalidOrder(ExchangeError):
    pass


class OrderNotFound(InvalidOrder):
    pass


class OrderNotCached(InvalidOrder):
    pass


class OrderImmediatelyFillable(InvalidOrder):
    pass


class OrderNotFillable(InvalidOrder):
    pass


class DuplicateOrderId(InvalidOrder):
    pass


class ContractUnavailable(InvalidOrder):
    pass


class NotSupported(ExchangeError):
    pass


class InvalidProxySettings(ExchangeError):
    pass


class ExchangeClosedByUser(ExchangeError):
    pass


class OperationFailed(BaseError):
    pass


class NetworkError(OperationFailed):
    pass


class DDoSProtection(NetworkError):
    pass


class RateLimitExceeded(NetworkError):
    pass


class ExchangeNotAvailable(NetworkError):
    pass


class OnMaintenance(ExchangeNotAvailable):
    pass


class InvalidNonce(NetworkError):
    pass


class ChecksumError(InvalidNonce):
    pass


class RequestTimeout(NetworkError):
    pass


class BadResponse(OperationFailed):
    pass


class NullResponse(BadResponse):
    pass


class CancelPending(OperationFailed):
    pass


class UnsubscribeError(BaseError):
    pass


__all__ = [
    "AccountNotEnabled",
    "AccountSuspended",
    "AddressPending",
    "ArgumentsRequired",
    "AuthenticationError",
    "BadRequest",
    "BadResponse",
    "BadSymbol",
    "BaseError",
    "CancelPending",
    "ChecksumError",
    "ContractUnavailable",
    "DDoSProtection",
    "DuplicateOrderId",
    "ExchangeClosedByUser",
    "ExchangeError",
    "ExchangeNotAvailable",
    "InsufficientFunds",
    "InvalidAddress",
    "InvalidNonce",
    "InvalidOrder",
    "InvalidProxySettings",
    "ManualInteractionNeeded",
    "MarginModeAlreadySet",
    "MarketClosed",
    "NetworkError",
    "NoChange",
    "NotSupported",
    "NullResponse",
    "OnMaintenance",
    "OperationFailed",
    "OperationRejected",
    "OrderImmediatelyFillable",
    "OrderNotCached",
    "OrderNotFillable",
    "OrderNotFound",
    "PermissionDenied",
    "RateLimitExceeded",
    "RequestTimeout",
    "RestrictedLocation",
    "UnsubscribeError",
    "error_hierarchy",
]
