from __future__ import annotations

import datetime

import pytz


def is_ist_market_session_active(dt: datetime.datetime | None = None) -> bool:
    """Checks whether current or provided time falls within NSE/BSE IST market session (09:15 to 15:30 IST Mon-Fri)."""
    ist = pytz.timezone("Asia/Kolkata")
    now = dt.astimezone(ist) if dt else datetime.datetime.now(ist)
    if now.weekday() >= 5:
        return False
    market_open = now.replace(hour=9, minute=15, second=0, microsecond=0)
    market_close = now.replace(hour=15, minute=30, second=0, microsecond=0)
    return market_open <= now <= market_close


def round_to_ist_tick(price: float, tick_size: float = 0.05) -> float:
    """Rounds price to nearest NSE/BSE valid price tick (default 0.05 INR)."""
    if price <= 0:
        return 0.0
    return round(round(price / tick_size) * tick_size, 2)


"""
The demo (plan M2.6, M5.6, M9.6): the real v2 engine replaying the **bundled fixture tape**
(``src/engine/demo_tape/``, one synthetic session on :data:`DEMO_DAY`), paced so the whole session
plays in a few minutes. Every price is ``MarketDataSource.SIMULATED``, which the RiskEngine allows
to trade only in the ``demo`` environment (its own ``var/demo/`` state).

The tape is generated by :func:`synthetic_day` (``scripts/build_demo_tape.py``); a test checks
the committed files still match it, so every demo run - and the M10 end-to-end tests - replay
exactly the same day: INFY's momentum signal runs to its target, TCS's to its stop.

No decision model runs in the demo, so the typed-veto book gets a :class:`ScriptedVeto` that
vetoes TCS (recorded as the model ``demo-script``, never as a real verdict): the paired books
then show a veto that avoided a loss, end to end.
"""


import asyncio
from datetime import date, datetime, time, timedelta
from pathlib import Path

import numpy as np
import pandas as pd
from src.domain.clock import ReplayClock
from src.domain.events import AdvisorRequested
from src.domain.sink import EventSink
from src.domain.types import (
    AdvisorKind,
    AdvisorVerdict,
    Bar,
    Instrument,
    MarketDataSource,
    Quote,
    Timeframe,
    Verdict,
    VerdictReason,
)
from src.engine.market import INDEX_KEY
from src.features.technical import Features
from src.store.tape import TapeWriter
from src.strategies.policy import Proposal
from src.utils.market_time import IST

SIM = MarketDataSource.SIMULATED
DEMO_TAPE = Path(__file__).resolve().parent / "demo_tape"
DEMO_DAY = date(2026, 10, 5)  # the recorded session (a Monday)
DEMO_PREVIOUS = date(2026, 10, 1)  # its previous session (2 Oct is a holiday)
# symbol, sector, last close, history seed (seed 3 makes momentum fire on the last bar)
DEMO_SYMBOLS: tuple[tuple[str, str, float, int], ...] = (
    ("INFY", "Information Technology", 1000.0, 3),
    ("TCS", "Information Technology", 4000.0, 20),  # momentum BUY; falls to its stop
    ("RELIANCE", "Oil Gas & Consumable Fuels", 2900.0, 11),
    ("HDFCBANK", "Financial Services", 1650.0, 12),
    ("ICICIBANK", "Financial Services", 1250.0, 13),
    ("SBIN", "Financial Services", 820.0, 14),
    ("ITC", "Fast Moving Consumer Goods", 470.0, 15),
    ("LT", "Construction", 3600.0, 16),
)


def demo_instruments() -> list[Instrument]:
    return [Instrument.nse_equity(s, sector=sector) for s, sector, _, _ in DEMO_SYMBOLS]


def _history(key: str, seed: int, last: float, end: date, n: int = 250) -> list[Bar]:
    rng = np.random.default_rng(seed)
    close = np.exp(np.cumsum(rng.normal(0, 0.01, n)))
    close = close / close[-1] * last
    days = pd.bdate_range(end=pd.Timestamp(end), periods=n)
    return [
        Bar(instrument_key=key, timeframe=Timeframe.D1, session_date=d.date(), open=float(c),
            high=float(c) * 1.008, low=float(c) * 0.992, close=float(c), volume=3_000_000,
            is_settled=True, adjusted=adjusted, source=SIM)
        for adjusted in (False, True)
        for d, c in zip(days, close, strict=True)
    ]  # fmt: skip


def synthetic_day(day: date, previous: date) -> tuple[list[Bar], list[Quote]]:
    """Settled history up to ``previous`` and one-minute quotes for ``day`` (09:15-15:30)."""
    bars: list[Bar] = _history(INDEX_KEY, 5, 25_000.0, previous)
    quotes: list[Quote] = []
    for n, (symbol, _, last, seed) in enumerate(DEMO_SYMBOLS):
        key = f"NSE:EQ:{symbol}"
        bars += _history(key, seed, last, previous)
        rng = np.random.default_rng(1000 + n)
        drift = {"INFY": 0.0004, "TCS": -0.00025}.get(symbol, 0.0)  # target / stop
        steps = np.cumsum(rng.normal(drift, 0.0012, 376))
        minute = datetime.combine(day, time(9, 15), IST)
        for i, step in enumerate(steps):
            ts = minute + timedelta(minutes=i)
            quotes.append(Quote(instrument_key=key, ltp=round(last * float(np.exp(step)), 2),
                                prev_close=last, volume_cum=(i + 1) * 40_000,
                                exchange_ts=ts - timedelta(minutes=15), receipt_ts=ts,
                                source=SIM, is_delayed=True))  # fmt: skip
    return bars, quotes


async def pace(
    clock: ReplayClock,
    until: datetime,
    *,
    step_s: float = 30.0,
    wall_s: float = 0.1,
    done: asyncio.Event | None = None,
) -> None:
    """Advance the replay clock by ``step_s`` every ``wall_s`` of real time."""
    while clock.now() < until and (done is None or not done.is_set()):
        await clock.advance(step_s)
        await asyncio.sleep(wall_s)


def write_demo_tape(root: Path = DEMO_TAPE) -> list[Path]:
    """(Re)write the bundled tape: one compacted ``bars`` and ``quotes`` file for the day."""
    day_dir = root / DEMO_DAY.isoformat()
    if day_dir.exists():
        for old in day_dir.iterdir():
            old.unlink()
    bars, quotes = synthetic_day(DEMO_DAY, DEMO_PREVIOUS)
    writer = TapeWriter(root)
    writer.add_bars(bars, recorded_on=DEMO_DAY)
    writer.add_quotes(quotes)
    writer.flush()
    return writer.compact(DEMO_DAY)


DEMO_VETOED = frozenset({"NSE:EQ:TCS"})
SCRIPT = "demo-script"


class ScriptedVeto:
    """The demo's stand-in for the typed veto (no decision model runs in the demo): vetoes the
    instruments in :data:`DEMO_VETOED`, approves everything else, and says so in every verdict."""

    def __init__(
        self, *, book_id: str, sink: EventSink, vetoed: frozenset[str] = DEMO_VETOED
    ) -> None:
        self.book_id, self.vetoed = book_id, vetoed
        self._sink = sink

    async def review(self, proposal: Proposal, features: Features) -> Verdict:
        intent = proposal.intent
        kind = AdvisorKind.TYPED_VETO
        self._sink.emit(AdvisorRequested(decision_id=intent.decision_id, book_id=self.book_id,
                                         advisor=kind, signal_id=proposal.signal.signal_id,
                                         model=SCRIPT), source="advisor")  # fmt: skip
        veto = intent.instrument.key in self.vetoed
        verdict = Verdict.VETO if veto else Verdict.APPROVE
        reasons = (VerdictReason(claim="scripted demo veto (no model runs in the demo)",
                                 evidence_ref="signal.instrument_key"),) if veto else ()  # fmt: skip
        self._sink.emit(AdvisorVerdict(decision_id=intent.decision_id, book_id=self.book_id,
                                       advisor=kind, verdict=verdict, reasons=reasons,
                                       model=SCRIPT, provider="demo"), source="advisor")  # fmt: skip
        return verdict
