from __future__ import annotations

import datetime

import pytz


def is_ist_market_session_active(dt: datetime.datetime | None = None) -> bool:
    """Checks whether current or provided time falls within NSE/BSE IST market session (09:15 to 15:30 IST Mon-Fri)."""
    ist = pytz.timezone("Asia/Kolkata")
    now = dt.astimezone(ist) if dt else datetime.datetime.now(ist)
    if now.weekday() >= 5:
        return False
    market_open = now.replace(hour=9, minute=15, second=0, microsecond=0)
    market_close = now.replace(hour=15, minute=30, second=0, microsecond=0)
    return market_open <= now <= market_close


def round_to_ist_tick(price: float, tick_size: float = 0.05) -> float:
    """Rounds price to nearest NSE/BSE valid price tick (default 0.05 INR)."""
    if price <= 0:
        return 0.0
    return round(round(price / tick_size) * tick_size, 2)


"""
Build the full Nifty 500 universe CSV.
Run once: python tools/build_universe.py
"""

import csv
from pathlib import Path

UNIVERSE_PATH = Path(__file__).resolve().parent.parent / "data" / "universe.csv"

# Full Nifty 500 + additional liquid midcap/smallcap symbols with yfinance tickers
# Format: (symbol, company, sector, yfinance_ticker, cap_category)
SYMBOLS = [
    # ── NIFTY 50 ──────────────────────────────────────────────────────────────
    ("ADANIENT", "Adani Enterprises", "Metals & Mining", "ADANIENT.NS", "Large Cap"),
    ("ADANIPORTS", "Adani Ports & SEZ", "Services", "ADANIPORTS.NS", "Large Cap"),
    ("APOLLOHOSP", "Apollo Hospitals", "Healthcare", "APOLLOHOSP.NS", "Large Cap"),
    ("ASIANPAINT", "Asian Paints", "Consumer Durables", "ASIANPAINT.NS", "Large Cap"),
    ("AXISBANK", "Axis Bank", "Financial Services", "AXISBANK.NS", "Large Cap"),
    ("BAJAJ-AUTO", "Bajaj Auto", "Automobile", "BAJAJ-AUTO.NS", "Large Cap"),
    ("BAJFINANCE", "Bajaj Finance", "Financial Services", "BAJFINANCE.NS", "Large Cap"),
    ("BAJAJFINSV", "Bajaj Finserv", "Financial Services", "BAJAJFINSV.NS", "Large Cap"),
    ("BEL", "Bharat Electronics", "Capital Goods", "BEL.NS", "Large Cap"),
    ("BPCL", "BPCL", "Oil Gas & Fuels", "BPCL.NS", "Large Cap"),
    ("BHARTIARTL", "Bharti Airtel", "Telecom", "BHARTIARTL.NS", "Large Cap"),
    ("BRITANNIA", "Britannia Industries", "FMCG", "BRITANNIA.NS", "Large Cap"),
    ("CIPLA", "Cipla", "Pharma", "CIPLA.NS", "Large Cap"),
    ("COALINDIA", "Coal India", "Metals & Mining", "COALINDIA.NS", "Large Cap"),
    ("DRREDDY", "Dr Reddys Labs", "Pharma", "DRREDDY.NS", "Large Cap"),
    ("EICHERMOT", "Eicher Motors", "Automobile", "EICHERMOT.NS", "Large Cap"),
    ("GRASIM", "Grasim Industries", "Construction", "GRASIM.NS", "Large Cap"),
    ("HCLTECH", "HCL Technologies", "IT", "HCLTECH.NS", "Large Cap"),
    ("HDFCBANK", "HDFC Bank", "Financial Services", "HDFCBANK.NS", "Large Cap"),
    ("HDFCLIFE", "HDFC Life Insurance", "Financial Services", "HDFCLIFE.NS", "Large Cap"),
    ("HEROMOTOCO", "Hero MotoCorp", "Automobile", "HEROMOTOCO.NS", "Large Cap"),
    ("HINDALCO", "Hindalco Industries", "Metals & Mining", "HINDALCO.NS", "Large Cap"),
    ("HINDUNILVR", "Hindustan Unilever", "FMCG", "HINDUNILVR.NS", "Large Cap"),
    ("ICICIBANK", "ICICI Bank", "Financial Services", "ICICIBANK.NS", "Large Cap"),
    ("ITC", "ITC", "FMCG", "ITC.NS", "Large Cap"),
    ("INDUSINDBK", "IndusInd Bank", "Financial Services", "INDUSINDBK.NS", "Large Cap"),
    ("INFY", "Infosys", "IT", "INFY.NS", "Large Cap"),
    ("JSWSTEEL", "JSW Steel", "Metals & Mining", "JSWSTEEL.NS", "Large Cap"),
    ("KOTAKBANK", "Kotak Mahindra Bank", "Financial Services", "KOTAKBANK.NS", "Large Cap"),
    ("LT", "Larsen & Toubro", "Capital Goods", "LT.NS", "Large Cap"),
    ("M&M", "Mahindra & Mahindra", "Automobile", "M&M.NS", "Large Cap"),
    ("MARUTI", "Maruti Suzuki", "Automobile", "MARUTI.NS", "Large Cap"),
    ("NESTLEIND", "Nestle India", "FMCG", "NESTLEIND.NS", "Large Cap"),
    ("NTPC", "NTPC", "Power", "NTPC.NS", "Large Cap"),
    ("ONGC", "ONGC", "Oil Gas & Fuels", "ONGC.NS", "Large Cap"),
    ("POWERGRID", "Power Grid Corp", "Power", "POWERGRID.NS", "Large Cap"),
    ("RELIANCE", "Reliance Industries", "Oil Gas & Fuels", "RELIANCE.NS", "Large Cap"),
    ("SBILIFE", "SBI Life Insurance", "Financial Services", "SBILIFE.NS", "Large Cap"),
    ("SHRIRAMFIN", "Shriram Finance", "Financial Services", "SHRIRAMFIN.NS", "Large Cap"),
    ("SBIN", "State Bank of India", "Financial Services", "SBIN.NS", "Large Cap"),
    ("SUNPHARMA", "Sun Pharmaceutical", "Pharma", "SUNPHARMA.NS", "Large Cap"),
    ("TCS", "Tata Consultancy Services", "IT", "TCS.NS", "Large Cap"),
    ("TATACONSUM", "Tata Consumer Products", "FMCG", "TATACONSUM.NS", "Large Cap"),
    ("TATAMOTORS", "Tata Motors", "Automobile", "TATAMOTORS.NS", "Large Cap"),
    ("TATASTEEL", "Tata Steel", "Metals & Mining", "TATASTEEL.NS", "Large Cap"),
    ("TECHM", "Tech Mahindra", "IT", "TECHM.NS", "Large Cap"),
    ("TITAN", "Titan Company", "Consumer Durables", "TITAN.NS", "Large Cap"),
    ("TRENT", "Trent", "Consumer Durables", "TRENT.NS", "Large Cap"),
    ("ULTRACEMCO", "UltraTech Cement", "Construction", "ULTRACEMCO.NS", "Large Cap"),
    ("WIPRO", "Wipro", "IT", "WIPRO.NS", "Large Cap"),
    # ── NIFTY NEXT 50 ─────────────────────────────────────────────────────────
    ("ABB", "ABB India", "Capital Goods", "ABB.NS", "Large Cap"),
    ("ADANIGREEN", "Adani Green Energy", "Power", "ADANIGREEN.NS", "Large Cap"),
    ("ADANITRANS", "Adani Transmission", "Power", "ADANITRANS.NS", "Large Cap"),
    ("AMBUJACEM", "Ambuja Cements", "Construction", "AMBUJACEM.NS", "Large Cap"),
    ("AUROPHARMA", "Aurobindo Pharma", "Pharma", "AUROPHARMA.NS", "Large Cap"),
    ("BAJAJHLDNG", "Bajaj Holdings", "Financial Services", "BAJAJHLDNG.NS", "Large Cap"),
    ("BANKBARODA", "Bank of Baroda", "Financial Services", "BANKBARODA.NS", "Large Cap"),
    ("BERGEPAINT", "Berger Paints", "Consumer Durables", "BERGEPAINT.NS", "Large Cap"),
    ("BOSCHLTD", "Bosch", "Automobile", "BOSCHLTD.NS", "Large Cap"),
    ("CANBK", "Canara Bank", "Financial Services", "CANBK.NS", "Large Cap"),
    ("CHOLAFIN", "Cholamandalam Investment", "Financial Services", "CHOLAFIN.NS", "Large Cap"),
    ("COLPAL", "Colgate-Palmolive", "FMCG", "COLPAL.NS", "Large Cap"),
    ("DLF", "DLF", "Realty", "DLF.NS", "Large Cap"),
    ("DABUR", "Dabur India", "FMCG", "DABUR.NS", "Large Cap"),
    ("DIVISLAB", "Divi's Laboratories", "Pharma", "DIVISLAB.NS", "Large Cap"),
    ("GAIL", "GAIL India", "Oil Gas & Fuels", "GAIL.NS", "Large Cap"),
    ("GODREJCP", "Godrej Consumer Products", "FMCG", "GODREJCP.NS", "Large Cap"),
    ("HAVELLS", "Havells India", "Capital Goods", "HAVELLS.NS", "Large Cap"),
    ("HAL", "Hindustan Aeronautics", "Capital Goods", "HAL.NS", "Large Cap"),
    ("ICICIGI", "ICICI Lombard", "Financial Services", "ICICIGI.NS", "Large Cap"),
    ("ICICIPRULI", "ICICI Prudential Life", "Financial Services", "ICICIPRULI.NS", "Large Cap"),
    ("IOC", "Indian Oil Corp", "Oil Gas & Fuels", "IOC.NS", "Large Cap"),
    ("IRCTC", "IRCTC", "Services", "IRCTC.NS", "Large Cap"),
    ("JINDALSTEL", "Jindal Steel & Power", "Metals & Mining", "JINDALSTEL.NS", "Large Cap"),
    ("LICI", "Life Insurance Corp", "Financial Services", "LICI.NS", "Large Cap"),
    ("LTIM", "LTIMindtree", "IT", "LTIM.NS", "Large Cap"),
    ("LTTS", "L&T Technology Services", "IT", "LTTS.NS", "Large Cap"),
    ("MARICO", "Marico", "FMCG", "MARICO.NS", "Large Cap"),
    ("MCDOWELL-N", "United Spirits", "FMCG", "MCDOWELL-N.NS", "Large Cap"),
    ("MUTHOOTFIN", "Muthoot Finance", "Financial Services", "MUTHOOTFIN.NS", "Large Cap"),
    ("NAUKRI", "Info Edge", "IT", "NAUKRI.NS", "Large Cap"),
    ("NHPC", "NHPC", "Power", "NHPC.NS", "Large Cap"),
    ("NMDC", "NMDC", "Metals & Mining", "NMDC.NS", "Large Cap"),
    ("OFSS", "Oracle Financial Services", "IT", "OFSS.NS", "Large Cap"),
    ("PIDILITIND", "Pidilite Industries", "Consumer Durables", "PIDILITIND.NS", "Large Cap"),
    ("PFC", "Power Finance Corp", "Financial Services", "PFC.NS", "Large Cap"),
    ("RECLTD", "REC", "Financial Services", "RECLTD.NS", "Large Cap"),
    ("SAIL", "Steel Authority of India", "Metals & Mining", "SAIL.NS", "Large Cap"),
    ("SIEMENS", "Siemens", "Capital Goods", "SIEMENS.NS", "Large Cap"),
    ("SRF", "SRF", "Chemicals", "SRF.NS", "Large Cap"),
    ("TORNTPHARM", "Torrent Pharmaceuticals", "Pharma", "TORNTPHARM.NS", "Large Cap"),
    ("UPL", "UPL", "Chemicals", "UPL.NS", "Large Cap"),
    ("VBL", "Varun Beverages", "FMCG", "VBL.NS", "Large Cap"),
    ("VEDL", "Vedanta", "Metals & Mining", "VEDL.NS", "Large Cap"),
    ("ZOMATO", "Zomato", "Consumer Services", "ZOMATO.NS", "Large Cap"),
    # ── NIFTY MIDCAP 150 ──────────────────────────────────────────────────────
    ("ABCAPITAL", "Aditya Birla Capital", "Financial Services", "ABCAPITAL.NS", "Mid Cap"),
    ("ABFRL", "Aditya Birla Fashion", "Consumer Durables", "ABFRL.NS", "Mid Cap"),
    ("ALKEM", "Alkem Laboratories", "Pharma", "ALKEM.NS", "Mid Cap"),
    ("APOLLOTYRE", "Apollo Tyres", "Automobile", "APOLLOTYRE.NS", "Mid Cap"),
    ("ASHOKLEY", "Ashok Leyland", "Automobile", "ASHOKLEY.NS", "Mid Cap"),
    ("ASTRAL", "Astral", "Construction", "ASTRAL.NS", "Mid Cap"),
    ("ATUL", "Atul", "Chemicals", "ATUL.NS", "Mid Cap"),
    ("AUBANK", "AU Small Finance Bank", "Financial Services", "AUBANK.NS", "Mid Cap"),
    ("APLAPOLLO", "APL Apollo Tubes", "Metals & Mining", "APLAPOLLO.NS", "Mid Cap"),
    ("BALKRISIND", "Balkrishna Industries", "Automobile", "BALKRISIND.NS", "Mid Cap"),
    ("BANDHANBNK", "Bandhan Bank", "Financial Services", "BANDHANBNK.NS", "Mid Cap"),
    ("BATAINDIA", "Bata India", "Consumer Durables", "BATAINDIA.NS", "Mid Cap"),
    ("BHEL", "Bharat Heavy Electricals", "Capital Goods", "BHEL.NS", "Mid Cap"),
    ("BIOCON", "Biocon", "Pharma", "BIOCON.NS", "Mid Cap"),
    ("BRIGADE", "Brigade Enterprises", "Realty", "BRIGADE.NS", "Mid Cap"),
    ("CESC", "CESC", "Power", "CESC.NS", "Mid Cap"),
    ("CGPOWER", "CG Power", "Capital Goods", "CGPOWER.NS", "Mid Cap"),
    ("COFORGE", "Coforge", "IT", "COFORGE.NS", "Mid Cap"),
    ("CROMPTON", "Crompton Greaves Consumer", "Capital Goods", "CROMPTON.NS", "Mid Cap"),
    ("CUMMINSIND", "Cummins India", "Capital Goods", "CUMMINSIND.NS", "Mid Cap"),
    ("DALBHARAT", "Dalmia Bharat", "Construction", "DALBHARAT.NS", "Mid Cap"),
    ("DEEPAKNTR", "Deepak Nitrite", "Chemicals", "DEEPAKNTR.NS", "Mid Cap"),
    ("DELHIVERY", "Delhivery", "Services", "DELHIVERY.NS", "Mid Cap"),
    ("DIXON", "Dixon Technologies", "Consumer Durables", "DIXON.NS", "Mid Cap"),
    ("ESCORTS", "Escorts Kubota", "Automobile", "ESCORTS.NS", "Mid Cap"),
    ("EXIDEIND", "Exide Industries", "Automobile", "EXIDEIND.NS", "Mid Cap"),
    ("FEDERALBNK", "Federal Bank", "Financial Services", "FEDERALBNK.NS", "Mid Cap"),
    ("GLENMARK", "Glenmark Pharma", "Pharma", "GLENMARK.NS", "Mid Cap"),
    ("GMRAIRPORT", "GMR Airports", "Services", "GMRAIRPORT.NS", "Mid Cap"),
    ("GODREJPROP", "Godrej Properties", "Realty", "GODREJPROP.NS", "Mid Cap"),
    ("GRANULES", "Granules India", "Pharma", "GRANULES.NS", "Mid Cap"),
    ("GSPL", "Gujarat State Petronet", "Oil Gas & Fuels", "GSPL.NS", "Mid Cap"),
    ("HINDCOPPER", "Hindustan Copper", "Metals & Mining", "HINDCOPPER.NS", "Mid Cap"),
    ("HINDPETRO", "Hindustan Petroleum", "Oil Gas & Fuels", "HINDPETRO.NS", "Mid Cap"),
    ("HONASA", "Honasa Consumer", "FMCG", "HONASA.NS", "Mid Cap"),
    ("IDFCFIRSTB", "IDFC First Bank", "Financial Services", "IDFCFIRSTB.NS", "Mid Cap"),
    ("IEX", "Indian Energy Exchange", "Financial Services", "IEX.NS", "Mid Cap"),
    ("INDIANB", "Indian Bank", "Financial Services", "INDIANB.NS", "Mid Cap"),
    ("INDHOTEL", "Indian Hotels", "Consumer Services", "INDHOTEL.NS", "Mid Cap"),
    ("INDUSTOWER", "Indus Towers", "Telecom", "INDUSTOWER.NS", "Mid Cap"),
    ("INOXWIND", "Inox Wind", "Capital Goods", "INOXWIND.NS", "Mid Cap"),
    ("IPL", "India Power", "Power", "IPL.NS", "Mid Cap"),
    ("JKCEMENT", "JK Cement", "Construction", "JKCEMENT.NS", "Mid Cap"),
    ("JSL", "Jindal Stainless", "Metals & Mining", "JSL.NS", "Mid Cap"),
    ("JUBLFOOD", "Jubilant Foodworks", "Consumer Services", "JUBLFOOD.NS", "Mid Cap"),
    ("KALYANKJIL", "Kalyan Jewellers", "Consumer Durables", "KALYANKJIL.NS", "Mid Cap"),
    ("KPITTECH", "KPIT Technologies", "IT", "KPITTECH.NS", "Mid Cap"),
    ("KPRMILL", "KPR Mill", "Textiles", "KPRMILL.NS", "Mid Cap"),
    ("KRISHNADEF", "Krishna Defence", "Capital Goods", "KRISHNADEF.NS", "Mid Cap"),
    ("LAURUSLABS", "Laurus Labs", "Pharma", "LAURUSLABS.NS", "Mid Cap"),
    ("LICHSGFIN", "LIC Housing Finance", "Financial Services", "LICHSGFIN.NS", "Mid Cap"),
    ("LUPIN", "Lupin", "Pharma", "LUPIN.NS", "Mid Cap"),
    ("MANAPPURAM", "Manappuram Finance", "Financial Services", "MANAPPURAM.NS", "Mid Cap"),
    ("MAZDOCK", "Mazagon Dock", "Capital Goods", "MAZDOCK.NS", "Mid Cap"),
    ("MCX", "MCX", "Financial Services", "MCX.NS", "Mid Cap"),
    ("METROPOLIS", "Metropolis Healthcare", "Healthcare", "METROPOLIS.NS", "Mid Cap"),
    ("MFSL", "Max Financial Services", "Financial Services", "MFSL.NS", "Mid Cap"),
    ("MGL", "Mahanagar Gas", "Oil Gas & Fuels", "MGL.NS", "Mid Cap"),
    ("MOTHERSON", "Samvardhana Motherson", "Automobile", "MOTHERSON.NS", "Mid Cap"),
    ("MPHASIS", "Mphasis", "IT", "MPHASIS.NS", "Mid Cap"),
    ("MRF", "MRF", "Automobile", "MRF.NS", "Large Cap"),
    ("NATIONALUM", "National Aluminium", "Metals & Mining", "NATIONALUM.NS", "Mid Cap"),
    ("NYKAA", "FSN E-Commerce (Nykaa)", "Consumer Services", "NYKAA.NS", "Mid Cap"),
    ("OIL", "Oil India", "Oil Gas & Fuels", "OIL.NS", "Mid Cap"),
    ("PAGEIND", "Page Industries", "Textiles", "PAGEIND.NS", "Mid Cap"),
    ("PATANJALI", "Patanjali Foods", "FMCG", "PATANJALI.NS", "Mid Cap"),
    ("PAYTM", "One 97 Communications", "IT", "PAYTM.NS", "Mid Cap"),
    ("PERSISTENT", "Persistent Systems", "IT", "PERSISTENT.NS", "Mid Cap"),
    ("PGHH", "Procter & Gamble", "FMCG", "PGHH.NS", "Large Cap"),
    ("POONAWALLA", "Poonawalla Fincorp", "Financial Services", "POONAWALLA.NS", "Mid Cap"),
    ("PRESTIGE", "Prestige Estates", "Realty", "PRESTIGE.NS", "Mid Cap"),
    ("PRINCEPIPE", "Prince Pipes", "Construction", "PRINCEPIPE.NS", "Mid Cap"),
    ("PVRINOX", "PVR Inox", "Consumer Services", "PVRINOX.NS", "Mid Cap"),
    ("RADICO", "Radico Khaitan", "FMCG", "RADICO.NS", "Mid Cap"),
    ("RAILTEL", "RailTel Corp", "IT", "RAILTEL.NS", "Mid Cap"),
    ("RAIN", "Rain Industries", "Chemicals", "RAIN.NS", "Mid Cap"),
    ("RAMCOCEM", "Ramco Cements", "Construction", "RAMCOCEM.NS", "Mid Cap"),
    ("RKFORGE", "Ramkrishna Forgings", "Capital Goods", "RKFORGE.NS", "Mid Cap"),
    ("RVNL", "Rail Vikas Nigam", "Capital Goods", "RVNL.NS", "Mid Cap"),
    ("SJVN", "SJVN", "Power", "SJVN.NS", "Mid Cap"),
    ("SKFINDIA", "SKF India", "Capital Goods", "SKFINDIA.NS", "Mid Cap"),
    ("SONACOMS", "Sona BLW Precision", "Automobile", "SONACOMS.NS", "Mid Cap"),
    ("STARHEALTH", "Star Health Insurance", "Financial Services", "STARHEALTH.NS", "Mid Cap"),
    ("SUMICHEM", "Sumitomo Chemical", "Chemicals", "SUMICHEM.NS", "Mid Cap"),
    ("SUPREMEIND", "Supreme Industries", "Construction", "SUPREMEIND.NS", "Mid Cap"),
    ("SYNGENE", "Syngene International", "Pharma", "SYNGENE.NS", "Mid Cap"),
    ("TATACHEM", "Tata Chemicals", "Chemicals", "TATACHEM.NS", "Large Cap"),
    ("TATACOMM", "Tata Communications", "Telecom", "TATACOMM.NS", "Large Cap"),
    ("TATAELXSI", "Tata Elxsi", "IT", "TATAELXSI.NS", "Mid Cap"),
    ("TATAPOWER", "Tata Power", "Power", "TATAPOWER.NS", "Large Cap"),
    ("TIINDIA", "Tube Investments", "Automobile", "TIINDIA.NS", "Mid Cap"),
    ("TORNTPOWER", "Torrent Power", "Power", "TORNTPOWER.NS", "Mid Cap"),
    ("TVSMOTOR", "TVS Motor Company", "Automobile", "TVSMOTOR.NS", "Large Cap"),
    ("UBL", "United Breweries", "FMCG", "UBL.NS", "Mid Cap"),
    ("UNIONBANK", "Union Bank of India", "Financial Services", "UNIONBANK.NS", "Mid Cap"),
    ("UNITDSPR", "United Spirits", "FMCG", "UNITDSPR.NS", "Mid Cap"),
    ("VOLTAS", "Voltas", "Capital Goods", "VOLTAS.NS", "Mid Cap"),
    ("WHIRLPOOL", "Whirlpool of India", "Consumer Durables", "WHIRLPOOL.NS", "Mid Cap"),
    ("ZEEL", "Zee Entertainment", "Media", "ZEEL.NS", "Mid Cap"),
    ("ZYDUSLIFE", "Zydus Lifesciences", "Pharma", "ZYDUSLIFE.NS", "Mid Cap"),
    # ── ADDITIONAL LIQUID MIDCAP / SMALLCAP ──────────────────────────────────
    ("AARTIIND", "Aarti Industries", "Chemicals", "AARTIIND.NS", "Mid Cap"),
    ("ABBOTINDIA", "Abbott India", "Pharma", "ABBOTINDIA.NS", "Large Cap"),
    ("AEGISCHEM", "Aegis Chemicals", "Chemicals", "AEGISCHEM.NS", "Mid Cap"),
    ("AFFLE", "Affle India", "IT", "AFFLE.NS", "Mid Cap"),
    ("AGROPHOS", "Agro Phos India", "Chemicals", "AGROPHOS.NS", "Small Cap"),
    ("AJANTPHARM", "Ajanta Pharma", "Pharma", "AJANTPHARM.NS", "Mid Cap"),
    ("AKZOINDIA", "Akzo Nobel India", "Consumer Durables", "AKZOINDIA.NS", "Mid Cap"),
    ("ALEMBICLTD", "Alembic", "Pharma", "ALEMBICLTD.NS", "Mid Cap"),
    ("ANGELONE", "Angel One", "Financial Services", "ANGELONE.NS", "Mid Cap"),
    ("ANURAS", "Anuras", "Consumer Services", "ANURAS.NS", "Small Cap"),
    ("APARINDS", "Apar Industries", "Capital Goods", "APARINDS.NS", "Mid Cap"),
    ("APTUS", "Aptus Value Housing", "Financial Services", "APTUS.NS", "Mid Cap"),
    ("ARCHIES", "Archies", "Consumer Durables", "ARCHIES.NS", "Small Cap"),
    ("ARVINDFASN", "Arvind Fashions", "Textiles", "ARVINDFASN.NS", "Mid Cap"),
    ("ASAHIINDIA", "Asahi India Glass", "Consumer Durables", "ASAHIINDIA.NS", "Mid Cap"),
    ("ASHAPURMIN", "Ashapura Minechem", "Metals & Mining", "ASHAPURMIN.NS", "Small Cap"),
    ("ASTRAZEN", "AstraZeneca Pharma", "Pharma", "ASTRAZEN.NS", "Mid Cap"),
    ("ATGL", "Adani Total Gas", "Oil Gas & Fuels", "ATGL.NS", "Large Cap"),
    ("AVANTIFEED", "Avanti Feeds", "FMCG", "AVANTIFEED.NS", "Mid Cap"),
    ("BAJAJCON", "Bajaj Consumer Care", "FMCG", "BAJAJCON.NS", "Small Cap"),
    ("BALAMINES", "Balaji Amines", "Chemicals", "BALAMINES.NS", "Mid Cap"),
    ("BALRAMCHIN", "Balrampur Chini Mills", "FMCG", "BALRAMCHIN.NS", "Mid Cap"),
    ("BARBEQUE", "Barbeque Nation", "Consumer Services", "BARBEQUE.NS", "Small Cap"),
    ("BAYERCROP", "Bayer Cropscience", "Chemicals", "BAYERCROP.NS", "Mid Cap"),
    ("BEML", "BEML", "Capital Goods", "BEML.NS", "Mid Cap"),
    ("BIKAJI", "Bikaji Foods", "FMCG", "BIKAJI.NS", "Mid Cap"),
    ("BLUESTARCO", "Blue Star", "Capital Goods", "BLUESTARCO.NS", "Mid Cap"),
    ("BORORENEW", "BORO Renewables", "Power", "BORORENEW.NS", "Small Cap"),
    ("BSOFT", "Birlasoft", "IT", "BSOFT.NS", "Mid Cap"),
    ("CANFINHOME", "Can Fin Homes", "Financial Services", "CANFINHOME.NS", "Mid Cap"),
    ("CAPACITE", "Capacite Infraprojects", "Construction", "CAPACITE.NS", "Small Cap"),
    ("CARBORUNIV", "Carborundum Universal", "Capital Goods", "CARBORUNIV.NS", "Mid Cap"),
    ("CASTROLIND", "Castrol India", "Oil Gas & Fuels", "CASTROLIND.NS", "Mid Cap"),
    ("CDSL", "CDSL", "Financial Services", "CDSL.NS", "Mid Cap"),
    ("CENTURYPLY", "Century Plyboards", "Construction", "CENTURYPLY.NS", "Mid Cap"),
    ("CENTURYTEX", "Century Textiles", "Textiles", "CENTURYTEX.NS", "Mid Cap"),
    ("CERA", "Cera Sanitaryware", "Consumer Durables", "CERA.NS", "Mid Cap"),
    ("CHALET", "Chalet Hotels", "Consumer Services", "CHALET.NS", "Mid Cap"),
    ("CHAMBLFERT", "Chambal Fertilisers", "Chemicals", "CHAMBLFERT.NS", "Mid Cap"),
    ("CLEAN", "Clean Science & Tech", "Chemicals", "CLEAN.NS", "Mid Cap"),
    ("COCHINSHIP", "Cochin Shipyard", "Capital Goods", "COCHINSHIP.NS", "Mid Cap"),
    ("CONCOR", "Container Corp of India", "Services", "CONCOR.NS", "Large Cap"),
    ("CRAFTSMAN", "Craftsman Automation", "Automobile", "CRAFTSMAN.NS", "Mid Cap"),
    ("CRISIL", "CRISIL", "Financial Services", "CRISIL.NS", "Mid Cap"),
    ("DCMSHRIRAM", "DCM Shriram", "Chemicals", "DCMSHRIRAM.NS", "Mid Cap"),
    ("DELHIVERY", "Delhivery", "Services", "DELHIVERY.NS", "Mid Cap"),
    ("DELTACORP", "Delta Corp", "Consumer Services", "DELTACORP.NS", "Small Cap"),
    ("DHANUKA", "Dhanuka Agritech", "Chemicals", "DHANUKA.NS", "Mid Cap"),
    ("DHANI", "Dhani Services", "Financial Services", "DHANI.NS", "Small Cap"),
    ("DOMS", "DOMS Industries", "Consumer Durables", "DOMS.NS", "Mid Cap"),
    ("DRREDDYS", "Dr Reddys", "Pharma", "DRREDDY.NS", "Large Cap"),
    ("EASEMYTRIP", "Easy Trip Planners", "Consumer Services", "EASEMYTRIP.NS", "Small Cap"),
    ("ELECON", "Elecon Engineering", "Capital Goods", "ELECON.NS", "Mid Cap"),
    ("ELGIEQUIP", "Elgi Equipments", "Capital Goods", "ELGIEQUIP.NS", "Mid Cap"),
    ("EMAMILTD", "Emami", "FMCG", "EMAMILTD.NS", "Mid Cap"),
    ("ENGINERSIN", "Engineers India", "Capital Goods", "ENGINERSIN.NS", "Mid Cap"),
    ("EPIGRAL", "Epigral", "Chemicals", "EPIGRAL.NS", "Mid Cap"),
    ("EPL", "EPL", "Consumer Durables", "EPL.NS", "Mid Cap"),
    ("EQUITASBNK", "Equitas Small Finance Bank", "Financial Services", "EQUITASBNK.NS", "Mid Cap"),
    ("EROSMEDIA", "Eros STX Global Media", "Media", "EROSMEDIA.NS", "Small Cap"),
    ("ESTER", "Ester Industries", "Chemicals", "ESTER.NS", "Small Cap"),
    ("ETHOSLTD", "Ethos", "Consumer Durables", "ETHOSLTD.NS", "Mid Cap"),
    ("FINEORG", "Fine Organic Industries", "Chemicals", "FINEORG.NS", "Mid Cap"),
    ("FINPIPE", "Finolex Industries", "Construction", "FINPIPE.NS", "Mid Cap"),
    ("FIVESTAR", "Five-Star Business Finance", "Financial Services", "FIVESTAR.NS", "Mid Cap"),
    ("FLEXITUFF", "Flexituff Ventures", "Consumer Durables", "FLEXITUFF.NS", "Small Cap"),
    ("FLUOROCHEM", "Gujarat Fluorochemicals", "Chemicals", "FLUOROCHEM.NS", "Mid Cap"),
    ("FORTIS", "Fortis Healthcare", "Healthcare", "FORTIS.NS", "Mid Cap"),
    ("GATEWAY", "Gateway Distriparks", "Services", "GATEWAY.NS", "Mid Cap"),
    ("GHCL", "GHCL", "Chemicals", "GHCL.NS", "Mid Cap"),
    ("GICRE", "GIC of India", "Financial Services", "GICRE.NS", "Large Cap"),
    ("GILLETTE", "Gillette India", "FMCG", "GILLETTE.NS", "Mid Cap"),
    ("GLAND", "Gland Pharma", "Pharma", "GLAND.NS", "Mid Cap"),
    ("GLAXO", "GSK Pharmaceuticals", "Pharma", "GLAXO.NS", "Mid Cap"),
    ("GNFC", "Gujarat Narmada Valley Fertilisers", "Chemicals", "GNFC.NS", "Mid Cap"),
    ("GODFRYPHLP", "Godfrey Phillips", "FMCG", "GODFRYPHLP.NS", "Mid Cap"),
    ("GPIL", "Godawari Power & Ispat", "Metals & Mining", "GPIL.NS", "Mid Cap"),
    ("GRAPHITE", "Graphite India", "Capital Goods", "GRAPHITE.NS", "Mid Cap"),
    ("GREENPANEL", "Greenpanel Industries", "Construction", "GREENPANEL.NS", "Mid Cap"),
    ("GREENLAM", "Greenlam Industries", "Construction", "GREENLAM.NS", "Mid Cap"),
    ("GUJGASLTD", "Gujarat Gas", "Oil Gas & Fuels", "GUJGASLTD.NS", "Mid Cap"),
    ("GULFOILLUB", "Gulf Oil Lubricants", "Oil Gas & Fuels", "GULFOILLUB.NS", "Mid Cap"),
    ("HBLPOWER", "HBL Power Systems", "Capital Goods", "HBLPOWER.NS", "Mid Cap"),
    ("HFCL", "HFCL", "Telecom", "HFCL.NS", "Mid Cap"),
    ("HIKAL", "Hikal", "Chemicals", "HIKAL.NS", "Mid Cap"),
    ("HSCL", "Himadri Speciality Chemical", "Chemicals", "HSCL.NS", "Mid Cap"),
    ("HUDCO", "HUDCO", "Financial Services", "HUDCO.NS", "Mid Cap"),
    ("IBREALEST", "Indiabulls Real Estate", "Realty", "IBREALEST.NS", "Small Cap"),
    ("ICIL", "Indo Count Industries", "Textiles", "ICIL.NS", "Mid Cap"),
    ("IDBI", "IDBI Bank", "Financial Services", "IDBI.NS", "Mid Cap"),
    ("IFBIND", "IFB Industries", "Consumer Durables", "IFBIND.NS", "Mid Cap"),
    ("IGPL", "IG Petrochemicals", "Chemicals", "IGPL.NS", "Mid Cap"),
    ("IIFL", "IIFL Finance", "Financial Services", "IIFL.NS", "Mid Cap"),
    ("IPCALAB", "IPCA Laboratories", "Pharma", "IPCALAB.NS", "Mid Cap"),
    ("IRB", "IRB Infrastructure", "Construction", "IRB.NS", "Mid Cap"),
    ("IRCON", "IRCON International", "Construction", "IRCON.NS", "Mid Cap"),
    ("IREDA", "IREDA", "Financial Services", "IREDA.NS", "Mid Cap"),
    ("ISEC", "ICICI Securities", "Financial Services", "ISEC.NS", "Mid Cap"),
    ("ITC", "ITC", "FMCG", "ITC.NS", "Large Cap"),
    ("ITES", "IT Enabled Services", "IT", "ITES.NS", "Small Cap"),
    ("JAMNAUTO", "Jamna Auto Industries", "Automobile", "JAMNAUTO.NS", "Mid Cap"),
    ("JBCHEPHARM", "JB Chemicals & Pharma", "Pharma", "JBCHEPHARM.NS", "Mid Cap"),
    ("JBMA", "JBM Auto", "Automobile", "JBMA.NS", "Mid Cap"),
    ("JKPAPER", "JK Paper", "Consumer Durables", "JKPAPER.NS", "Mid Cap"),
    ("JKTYRE", "JK Tyre & Industries", "Automobile", "JKTYRE.NS", "Mid Cap"),
    ("JLHL", "Jupiter Life Line Hospitals", "Healthcare", "JLHL.NS", "Mid Cap"),
    ("JMFINANCIL", "JM Financial", "Financial Services", "JMFINANCIL.NS", "Mid Cap"),
    ("JSWENERGY", "JSW Energy", "Power", "JSWENERGY.NS", "Large Cap"),
    ("JSWINFRA", "JSW Infrastructure", "Services", "JSWINFRA.NS", "Large Cap"),
    ("JTEKTINDIA", "JTEKT India", "Automobile", "JTEKTINDIA.NS", "Mid Cap"),
    ("JUSTDIAL", "Just Dial", "IT", "JUSTDIAL.NS", "Mid Cap"),
    ("JYOTICNC", "Jyoti CNC Automation", "Capital Goods", "JYOTICNC.NS", "Mid Cap"),
    ("KALPATPOWR", "Kalpataru Projects", "Capital Goods", "KALPATPOWR.NS", "Mid Cap"),
    ("KANSAINER", "Kansai Nerolac Paints", "Consumer Durables", "KANSAINER.NS", "Mid Cap"),
    ("KAYNES", "Kaynes Technology", "Capital Goods", "KAYNES.NS", "Mid Cap"),
    ("KEC", "KEC International", "Capital Goods", "KEC.NS", "Mid Cap"),
    ("KENNAMET", "Kennametal India", "Capital Goods", "KENNAMET.NS", "Mid Cap"),
    ("KESORAMIND", "Kesoram Industries", "Construction", "KESORAMIND.NS", "Small Cap"),
    ("KHAITANELE", "Khaitan Electricals", "Capital Goods", "KHAITANELE.NS", "Small Cap"),
    ("KIOCL", "KIOCL", "Metals & Mining", "KIOCL.NS", "Mid Cap"),
    ("KIRLOSENG", "Kirloskar Electric", "Capital Goods", "KIRLOSENG.NS", "Mid Cap"),
    ("KNRCON", "KNR Constructions", "Construction", "KNRCON.NS", "Mid Cap"),
    ("KOLTEPATIL", "Kolte-Patil Developers", "Realty", "KOLTEPATIL.NS", "Mid Cap"),
    ("KSCL", "Kaveri Seed Company", "Chemicals", "KSCL.NS", "Mid Cap"),
    ("LALPATHLAB", "Dr. Lal PathLabs", "Healthcare", "LALPATHLAB.NS", "Mid Cap"),
    ("LATENTVIEW", "Latent View Analytics", "IT", "LATENTVIEW.NS", "Mid Cap"),
    ("LEMONTREE", "Lemon Tree Hotels", "Consumer Services", "LEMONTREE.NS", "Mid Cap"),
    ("LIQTECH", "Liquid Technologies", "IT", "LIQTECH.NS", "Small Cap"),
    ("LXCHEM", "Laxmi Organic Industries", "Chemicals", "LXCHEM.NS", "Mid Cap"),
    ("LUXIND", "Lux Industries", "Textiles", "LUXIND.NS", "Mid Cap"),
    ("MAHINDCIE", "Mahindra CIE Automotive", "Automobile", "MAHINDCIE.NS", "Mid Cap"),
    ("MAHLIFE", "Mahindra Lifespace", "Realty", "MAHLIFE.NS", "Mid Cap"),
    ("MAHLOG", "Mahindra Logistics", "Services", "MAHLOG.NS", "Mid Cap"),
    ("MANKIND", "Mankind Pharma", "Pharma", "MANKIND.NS", "Large Cap"),
    ("MAPMYINDIA", "C.E. Info Systems", "IT", "MAPMYINDIA.NS", "Mid Cap"),
    ("MASTEK", "Mastek", "IT", "MASTEK.NS", "Mid Cap"),
    ("MAXHEALTH", "Max Healthcare", "Healthcare", "MAXHEALTH.NS", "Large Cap"),
    ("MBAPL", "Maharashtra Seamless", "Metals & Mining", "MBAPL.NS", "Mid Cap"),
    ("MEDANTA", "Global Health (Medanta)", "Healthcare", "MEDANTA.NS", "Mid Cap"),
    ("MEDPLUS", "MedPlus Health Services", "Healthcare", "MEDPLUS.NS", "Mid Cap"),
    ("MESCON", "Mesco Steel", "Metals & Mining", "MESCON.NS", "Small Cap"),
    ("MIDHANI", "Mishra Dhatu Nigam", "Metals & Mining", "MIDHANI.NS", "Mid Cap"),
    ("MINDA", "Minda Corporation", "Automobile", "MINDA.NS", "Mid Cap"),
    ("MINDACORP", "Minda Industries", "Automobile", "MINDACORP.NS", "Mid Cap"),
    ("MMTC", "MMTC", "Services", "MMTC.NS", "Mid Cap"),
    ("MOLDTKPAC", "Mold-Tek Packaging", "Consumer Durables", "MOLDTKPAC.NS", "Mid Cap"),
    ("MOTILALOFS", "Motilal Oswal Financial", "Financial Services", "MOTILALOFS.NS", "Mid Cap"),
    ("MSTCLTD", "MSTC", "Services", "MSTCLTD.NS", "Mid Cap"),
    ("NATCOPHARM", "Natco Pharma", "Pharma", "NATCOPHARM.NS", "Mid Cap"),
    ("NAVA", "NAVA", "Power", "NAVA.NS", "Mid Cap"),
    ("NAVINFLUOR", "Navin Fluorine", "Chemicals", "NAVINFLUOR.NS", "Mid Cap"),
    ("NDTV", "NDTV", "Media", "NDTV.NS", "Small Cap"),
    ("NETWORK18", "Network18 Media", "Media", "NETWORK18.NS", "Mid Cap"),
    ("NEWGEN", "Newgen Software", "IT", "NEWGEN.NS", "Mid Cap"),
    ("NOCIL", "NOCIL", "Chemicals", "NOCIL.NS", "Mid Cap"),
    ("NORTHARC", "Northern Arc Capital", "Financial Services", "NORTHARC.NS", "Mid Cap"),
    ("NUVAMA", "Nuvama Wealth Management", "Financial Services", "NUVAMA.NS", "Mid Cap"),
    ("NCC", "NCC", "Construction", "NCC.NS", "Mid Cap"),
    ("OBEROIRLTY", "Oberoi Realty", "Realty", "OBEROIRLTY.NS", "Mid Cap"),
    ("OLECTRA", "Olectra Greentech", "Automobile", "OLECTRA.NS", "Mid Cap"),
    ("OPTIEMUS", "Optiemus Infracom", "Telecom", "OPTIEMUS.NS", "Small Cap"),
    ("PATELENG", "Patel Engineering", "Construction", "PATELENG.NS", "Mid Cap"),
    ("PCBL", "PCBL", "Chemicals", "PCBL.NS", "Mid Cap"),
    ("PDSL", "PDS", "Textiles", "PDSL.NS", "Mid Cap"),
    ("PENIND", "Pennar Industries", "Metals & Mining", "PENIND.NS", "Small Cap"),
    ("PFIZER", "Pfizer", "Pharma", "PFIZER.NS", "Mid Cap"),
    ("PHOENIXLTD", "Phoenix Mills", "Realty", "PHOENIXLTD.NS", "Large Cap"),
    ("PNBHOUSING", "PNB Housing Finance", "Financial Services", "PNBHOUSING.NS", "Mid Cap"),
    ("POLICYBZR", "PB Fintech (Policybazaar)", "Financial Services", "POLICYBZR.NS", "Large Cap"),
    ("POLYMED", "Poly Medicure", "Healthcare", "POLYMED.NS", "Mid Cap"),
    ("PRAJIND", "Praj Industries", "Capital Goods", "PRAJIND.NS", "Mid Cap"),
    ("PRIVISCL", "Privi Speciality Chemicals", "Chemicals", "PRIVISCL.NS", "Mid Cap"),
    ("PRSMJOHNSN", "Prism Johnson", "Construction", "PRSMJOHNSN.NS", "Mid Cap"),
    ("PSB", "Punjab & Sind Bank", "Financial Services", "PSB.NS", "Small Cap"),
    ("PTCIL", "PTC India Financial Services", "Financial Services", "PTCIL.NS", "Small Cap"),
    ("PUREIT", "Pureit", "Consumer Durables", "PUREIT.NS", "Small Cap"),
    ("QUESS", "Quess Corp", "Services", "QUESS.NS", "Mid Cap"),
    ("QUICKHEAL", "Quick Heal Technologies", "IT", "QUICKHEAL.NS", "Small Cap"),
    ("RALLIS", "Rallis India", "Chemicals", "RALLIS.NS", "Mid Cap"),
    ("RAMKY", "Ramky Infrastructure", "Construction", "RAMKY.NS", "Small Cap"),
    ("RATNAMANI", "Ratnamani Metals & Tubes", "Metals & Mining", "RATNAMANI.NS", "Mid Cap"),
    ("RAYMOND", "Raymond", "Textiles", "RAYMOND.NS", "Mid Cap"),
    ("REDINGTON", "Redington India", "IT", "REDINGTON.NS", "Mid Cap"),
    ("RENUKA", "Shree Renuka Sugars", "FMCG", "RENUKA.NS", "Mid Cap"),
    ("RESPONIND", "Responsive Industries", "Consumer Durables", "RESPONIND.NS", "Small Cap"),
    ("RHIM", "RHI Magnesita", "Capital Goods", "RHIM.NS", "Mid Cap"),
    ("RITES", "RITES", "Services", "RITES.NS", "Mid Cap"),
    ("ROSSARI", "Rossari Biotech", "Chemicals", "ROSSARI.NS", "Mid Cap"),
    ("RPOWER", "Reliance Power", "Power", "RPOWER.NS", "Mid Cap"),
    ("RTNPOWER", "Rattanindia Power", "Power", "RTNPOWER.NS", "Small Cap"),
    ("SANOFI", "Sanofi India", "Pharma", "SANOFI.NS", "Mid Cap"),
    ("SAPPHIRE", "Sapphire Foods", "Consumer Services", "SAPPHIRE.NS", "Mid Cap"),
    ("SCHAEFFLER", "Schaeffler India", "Automobile", "SCHAEFFLER.NS", "Mid Cap"),
    ("SEQUENT", "Sequent Scientific", "Pharma", "SEQUENT.NS", "Mid Cap"),
    ("SHALBY", "Shalby", "Healthcare", "SHALBY.NS", "Mid Cap"),
    ("SHYAMMETL", "Shyam Metalics", "Metals & Mining", "SHYAMMETL.NS", "Mid Cap"),
    ("SOBHA", "Sobha", "Realty", "SOBHA.NS", "Mid Cap"),
    ("SOLARA", "Solara Active Pharma", "Pharma", "SOLARA.NS", "Mid Cap"),
    ("SPANDANA", "Spandana Sphoorty Financial", "Financial Services", "SPANDANA.NS", "Mid Cap"),
    ("SPARC", "Sun Pharma Advanced Research", "Pharma", "SPARC.NS", "Mid Cap"),
    ("SPCENET", "Spc Net", "IT", "SPCENET.NS", "Small Cap"),
    ("SRTRANSFIN", "Shriram Transport Finance", "Financial Services", "SRTRANSFIN.NS", "Large Cap"),
    ("STAR", "Strides Pharma", "Pharma", "STAR.NS", "Mid Cap"),
    ("STLTECH", "STL Technologies", "Telecom", "STLTECH.NS", "Mid Cap"),
    ("SUBROS", "Subros", "Automobile", "SUBROS.NS", "Mid Cap"),
    ("SUNFLAG", "Sunflag Iron & Steel", "Metals & Mining", "SUNFLAG.NS", "Small Cap"),
    ("SUPRIYA", "Supriya Lifescience", "Pharma", "SUPRIYA.NS", "Small Cap"),
    ("SURYAROSNI", "Surya Roshni", "Capital Goods", "SURYAROSNI.NS", "Mid Cap"),
    ("SWSOLAR", "Sterling and Wilson Renewable", "Power", "SWSOLAR.NS", "Mid Cap"),
    ("SYMPHONY", "Symphony", "Capital Goods", "SYMPHONY.NS", "Mid Cap"),
    ("TANLA", "Tanla Platforms", "IT", "TANLA.NS", "Mid Cap"),
    ("TATAINVEST", "Tata Investment Corp", "Financial Services", "TATAINVEST.NS", "Large Cap"),
    ("TATAMETALI", "Tata Metaliks", "Metals & Mining", "TATAMETALI.NS", "Mid Cap"),
    ("TCNSBRANDS", "TCNS Clothing", "Consumer Durables", "TCNSBRANDS.NS", "Mid Cap"),
    ("TEAMLEASE", "TeamLease Services", "Services", "TEAMLEASE.NS", "Mid Cap"),
    ("TECHNOE", "Techno Electric", "Power", "TECHNOE.NS", "Mid Cap"),
    ("TEXRAIL", "Texmaco Rail", "Capital Goods", "TEXRAIL.NS", "Mid Cap"),
    ("THYROCARE", "Thyrocare Technologies", "Healthcare", "THYROCARE.NS", "Mid Cap"),
    ("TITAGARH", "Titagarh Rail Systems", "Capital Goods", "TITAGARH.NS", "Mid Cap"),
    ("TTKPRESTIG", "TTK Prestige", "Consumer Durables", "TTKPRESTIG.NS", "Mid Cap"),
    ("UCOBANK", "UCO Bank", "Financial Services", "UCOBANK.NS", "Mid Cap"),
    ("UJJIVANSFB", "Ujjivan Small Finance Bank", "Financial Services", "UJJIVANSFB.NS", "Mid Cap"),
    ("UTIAMC", "UTI Asset Management", "Financial Services", "UTIAMC.NS", "Mid Cap"),
    ("VAIBHAVGBL", "Vaibhav Global", "Consumer Durables", "VAIBHAVGBL.NS", "Mid Cap"),
    ("VARDHACRLC", "Vardhman Acrylics", "Textiles", "VARDHACRLC.NS", "Small Cap"),
    ("VDMDREALTY", "VDM Dream Realty", "Realty", "VDMDREALTY.NS", "Small Cap"),
    ("VIJAYA", "Vijaya Diagnostic Centre", "Healthcare", "VIJAYA.NS", "Mid Cap"),
    ("VINATIORGA", "Vinati Organics", "Chemicals", "VINATIORGA.NS", "Mid Cap"),
    ("VIPIND", "VIP Industries", "Consumer Durables", "VIPIND.NS", "Mid Cap"),
    ("VSTIND", "VST Industries", "FMCG", "VSTIND.NS", "Mid Cap"),
    ("WABAG", "WABAG", "Capital Goods", "WABAG.NS", "Mid Cap"),
    ("WELCORP", "Welspun Corp", "Metals & Mining", "WELCORP.NS", "Mid Cap"),
    ("WELSPUNLIV", "Welspun Living", "Textiles", "WELSPUNLIV.NS", "Mid Cap"),
    ("WESTLIFE", "Westlife Foodworld", "Consumer Services", "WESTLIFE.NS", "Mid Cap"),
    ("WONDERLA", "Wonderla Holidays", "Consumer Services", "WONDERLA.NS", "Mid Cap"),
    ("WOCKPHARMA", "Wockhardt", "Pharma", "WOCKPHARMA.NS", "Mid Cap"),
    ("XCHANGING", "Xchanging Solutions", "IT", "XCHANGING.NS", "Small Cap"),
    ("YATHARTH", "Yatharth Hospital", "Healthcare", "YATHARTH.NS", "Mid Cap"),
    ("ZAGGLE", "Zaggle Prepaid Ocean", "Financial Services", "ZAGGLE.NS", "Mid Cap"),
    ("ZENSARTECH", "Zensar Technologies", "IT", "ZENSARTECH.NS", "Mid Cap"),
    ("ZENTEC", "Zen Technologies", "Capital Goods", "ZENTEC.NS", "Mid Cap"),
    ("ZFCVINDIA", "ZF Commercial Vehicle", "Automobile", "ZFCVINDIA.NS", "Mid Cap"),
    ("ZODIACLOTH", "Zodiac Clothing", "Textiles", "ZODIACLOTH.NS", "Small Cap"),
    # ── ADDITIONAL TO REACH 500 ───────────────────────────────────────────────
    ("3MINDIA", "3M India", "Capital Goods", "3MINDIA.NS", "Large Cap"),
    ("ACCELYA", "Accelya Solutions", "IT", "ACCELYA.NS", "Mid Cap"),
    ("ACMESOLAR", "Acme Solar Holdings", "Power", "ACMESOLAR.NS", "Mid Cap"),
    ("ACRYSIL", "Acrysil", "Consumer Durables", "ACRYSIL.NS", "Small Cap"),
    ("ADANIENSOL", "Adani Energy Solutions", "Power", "ADANIENSOL.NS", "Large Cap"),
    ("ADANIPOWER", "Adani Power", "Power", "ADANIPOWER.NS", "Large Cap"),
    ("ADANIWILMAR", "Adani Wilmar", "FMCG", "ADANIWILMAR.NS", "Large Cap"),
    ("AETHER", "Aether Industries", "Chemicals", "AETHER.NS", "Mid Cap"),
    ("AGCNET", "AGC Networks", "IT", "AGCNET.NS", "Small Cap"),
    ("AGI", "AGI Greenpac", "Consumer Durables", "AGI.NS", "Mid Cap"),
    ("AGRITECH", "National Agri Mktg Fed", "Services", "AGRITECH.NS", "Small Cap"),
    ("AHLUCONT", "Ahlu Containers", "Capital Goods", "AHLUCONT.NS", "Small Cap"),
    ("AIIL", "Authum Investment", "Financial Services", "AIIL.NS", "Mid Cap"),
    ("AINM", "Aster India", "Healthcare", "AINM.NS", "Mid Cap"),
    ("AJAXENGG", "Ajax Engineering", "Capital Goods", "AJAXENGG.NS", "Mid Cap"),
    ("ALEMBICLTD", "Alembic", "Pharma", "ALEMBICLTD.NS", "Mid Cap"),
    ("ALMONDZ", "Almondz Global", "Financial Services", "ALMONDZ.NS", "Small Cap"),
    ("AMBER", "Amber Enterprises", "Capital Goods", "AMBER.NS", "Mid Cap"),
    ("AMJLAND", "AMJ Land Holdings", "Realty", "AMJLAND.NS", "Small Cap"),
    ("AMNPLST", "Amines & Plasticizers", "Chemicals", "AMNPLST.NS", "Small Cap"),
    ("ANANTRAJ", "Anant Raj", "Realty", "ANANTRAJ.NS", "Mid Cap"),
    ("ANDHRAPET", "Andhra Petrochemicals", "Chemicals", "ANDHRAPET.NS", "Small Cap"),
    ("ANDHRASUGAR", "Andhra Sugars", "FMCG", "ANDHRASUGAR.NS", "Small Cap"),
    ("ANIL", "Anil", "Chemicals", "ANIL.NS", "Small Cap"),
    ("ANKITMETAL", "Ankit Metal & Power", "Metals & Mining", "ANKITMETAL.NS", "Small Cap"),
    ("ANURAS", "Anuras", "Consumer Services", "ANURAS.NS", "Small Cap"),
    ("APCOTEXIND", "Apcotex Industries", "Chemicals", "APCOTEXIND.NS", "Small Cap"),
    ("APICINDIA", "Asian Paints Ind", "Consumer Durables", "APICINDIA.NS", "Small Cap"),
    ("ARMANFIN", "Arman Financial Services", "Financial Services", "ARMANFIN.NS", "Small Cap"),
    ("ARVIND", "Arvind", "Textiles", "ARVIND.NS", "Mid Cap"),
    ("ASCOM", "Ascom Leasing", "Financial Services", "ASCOM.NS", "Small Cap"),
    ("ASHOKA", "Ashoka Buildcon", "Construction", "ASHOKA.NS", "Mid Cap"),
    ("ASTER", "Aster DM Healthcare", "Healthcare", "ASTER.NS", "Mid Cap"),
    ("ASTERDM", "Aster DM Healthcare", "Healthcare", "ASTERDM.NS", "Mid Cap"),
    ("ASTRAMICRO", "Astra Microwave Products", "Capital Goods", "ASTRAMICRO.NS", "Mid Cap"),
    ("ATFL", "Agro Tech Foods", "FMCG", "ATFL.NS", "Mid Cap"),
    ("ATNL", "ATNL", "Capital Goods", "ATNL.NS", "Small Cap"),
    ("AVANTIFEED", "Avanti Feeds", "FMCG", "AVANTIFEED.NS", "Mid Cap"),
    ("AXISCADES", "Axiscades Technologies", "IT", "AXISCADES.NS", "Small Cap"),
    ("BAJAJELEC", "Bajaj Electricals", "Capital Goods", "BAJAJELEC.NS", "Mid Cap"),
    ("BASF", "BASF India", "Chemicals", "BASF.NS", "Mid Cap"),
    ("BBTC", "Bombay Burmah Trading", "Consumer Durables", "BBTC.NS", "Mid Cap"),
    ("BFINVEST", "BF Investment", "Financial Services", "BFINVEST.NS", "Small Cap"),
    ("BFUTILITIE", "BF Utilities", "Power", "BFUTILITIE.NS", "Small Cap"),
    ("BGRENERGY", "BGR Energy Systems", "Capital Goods", "BGRENERGY.NS", "Small Cap"),
    ("BHAGERIA", "Bhageria Industries", "Chemicals", "BHAGERIA.NS", "Small Cap"),
    ("BHANDARI", "Bhandari Hosiery Exports", "Textiles", "BHANDARI.NS", "Small Cap"),
    ("BHARAT", "Bharat Dynamics", "Capital Goods", "BHARAT.NS", "Mid Cap"),
    ("BHARATFORG", "Bharat Forge", "Capital Goods", "BHARATFORG.NS", "Large Cap"),
    ("BHARATRAS", "Bharat Rasayan", "Chemicals", "BHARATRAS.NS", "Mid Cap"),
    ("BHARATWIRE", "Bharat Wire Ropes", "Metals & Mining", "BHARATWIRE.NS", "Small Cap"),
    ("BHEEMITE", "Bheema Cements", "Construction", "BHEEMITE.NS", "Small Cap"),
    ("BIRLACABLE", "Birla Cable", "Capital Goods", "BIRLACABLE.NS", "Small Cap"),
    ("BLAL", "Bombay Live Artworks", "Consumer Services", "BLAL.NS", "Small Cap"),
    ("BLBLIMITED", "BLB", "Financial Services", "BLBLIMITED.NS", "Small Cap"),
    ("BOROLTD", "Borosil", "Consumer Durables", "BOROLTD.NS", "Mid Cap"),
    ("BOSCHLTD", "Bosch", "Automobile", "BOSCHLTD.NS", "Large Cap"),
    ("BRNL", "Bharat Road Network", "Construction", "BRNL.NS", "Small Cap"),
    ("BSE", "BSE", "Financial Services", "BSE.NS", "Large Cap"),
    ("BSELIMITED", "BSE", "Financial Services", "BSELIMITED.NS", "Large Cap"),
    ("CAPLIPOINT", "Caplin Point Labs", "Pharma", "CAPLIPOINT.NS", "Mid Cap"),
    ("CARERATING", "CARE Ratings", "Financial Services", "CARERATING.NS", "Mid Cap"),
    ("CASTEXTECH", "Castex Technologies", "Automobile", "CASTEXTECH.NS", "Small Cap"),
    ("CCHHL", "Country Club Hospitality", "Consumer Services", "CCHHL.NS", "Small Cap"),
    ("CCL", "CCL Products India", "FMCG", "CCL.NS", "Mid Cap"),
    ("CELESTIAL", "Celestial Biopharma", "Pharma", "CELESTIAL.NS", "Small Cap"),
    ("CENTURYENKA", "Century Enka", "Textiles", "CENTURYENKA.NS", "Mid Cap"),
    ("CEREBRAINT", "Cerebra Integrated", "IT", "CEREBRAINT.NS", "Small Cap"),
    ("CHEMFAB", "Chemfab Alkalis", "Chemicals", "CHEMFAB.NS", "Small Cap"),
    ("CHEMPLASTS", "Chemplast Sanmar", "Chemicals", "CHEMPLASTS.NS", "Mid Cap"),
    ("CIGNITITEC", "Cigniti Technologies", "IT", "CIGNITITEC.NS", "Mid Cap"),
    ("CLNINDIA", "CLN India", "Services", "CLNINDIA.NS", "Small Cap"),
    ("CMRSL", "CMR Steel", "Metals & Mining", "CMRSL.NS", "Small Cap"),
    ("COALINDIA", "Coal India", "Metals & Mining", "COALINDIA.NS", "Large Cap"),
    ("CONFIPET", "Confidence Petroleum", "Oil Gas & Fuels", "CONFIPET.NS", "Small Cap"),
    ("CONSOFINVT", "Consolidated Finvest", "Financial Services", "CONSOFINVT.NS", "Small Cap"),
    ("CONTROLPR", "Control Print", "Capital Goods", "CONTROLPR.NS", "Small Cap"),
    ("COSMOFIRST", "Cosmo First", "Chemicals", "COSMOFIRST.NS", "Mid Cap"),
    ("COSMOFILMS", "Cosmo Films", "Consumer Durables", "COSMOFILMS.NS", "Mid Cap"),
]


def build() -> None:
    # Deduplicate by symbol keeping first occurrence
    seen: set[str] = set()
    rows: list[tuple] = []
    for row in SYMBOLS:
        sym = row[0]
        if sym not in seen:
            seen.add(sym)
            rows.append(row)

    UNIVERSE_PATH.parent.mkdir(parents=True, exist_ok=True)
    with open(UNIVERSE_PATH, "w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(
            [
                "Symbol",
                "Company_Name",
                "Industry",
                "ISIN",
                "yfinance_Ticker",
                "Cap_Category",
                "In_Nifty500",
                "In_MidCap150",
            ]
        )
        for sym, company, sector, ticker, cap in rows:
            writer.writerow([sym, company, sector, "", ticker, cap, 1, 1 if cap == "Mid Cap" else 0])

    print(f"Universe written: {len(rows)} symbols -> {UNIVERSE_PATH}")


if __name__ == "__main__":
    build()
