import datetime

import pytz


def is_ist_market_session_active(dt: datetime.datetime | None = None) -> bool:
    """Checks whether current or provided time falls within NSE/BSE IST market session (09:15 to 15:30 IST Mon-Fri)."""
    ist = pytz.timezone("Asia/Kolkata")
    now = dt.astimezone(ist) if dt else datetime.datetime.now(ist)
    if now.weekday() >= 5:
        return False
    market_open = now.replace(hour=9, minute=15, second=0, microsecond=0)
    market_close = now.replace(hour=15, minute=30, second=0, microsecond=0)
    return market_open <= now <= market_close


def round_to_ist_tick(price: float, tick_size: float = 0.05) -> float:
    """Rounds price to nearest NSE/BSE valid price tick (default 0.05 INR)."""
    if price <= 0:
        return 0.0
    return round(round(price / tick_size) * tick_size, 2)


# ----------------------------------------------------------------------------
# PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
# https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code
# -----------------------------------------------------------------------------

from ccxt.test.exchange.base.test_account import test_account  # noqa: E402
from ccxt.test.exchange.base.test_balance import test_balance  # noqa: E402
from ccxt.test.exchange.base.test_borrow_interest import test_borrow_interest  # noqa: E402
from ccxt.test.exchange.base.test_borrow_rate import test_borrow_rate  # noqa: E402
from ccxt.test.exchange.base.test_currency import test_currency  # noqa: E402
from ccxt.test.exchange.base.test_deposit_withdrawal import test_deposit_withdrawal  # noqa: E402
from ccxt.test.exchange.base.test_funding_rate_history import test_funding_rate_history  # noqa: E402
from ccxt.test.exchange.base.test_last_price import test_last_price  # noqa: E402
from ccxt.test.exchange.base.test_ledger_entry import test_ledger_entry  # noqa: E402
from ccxt.test.exchange.base.test_leverage_tier import test_leverage_tier  # noqa: E402
from ccxt.test.exchange.base.test_liquidation import test_liquidation  # noqa: E402
from ccxt.test.exchange.base.test_margin_mode import test_margin_mode  # noqa: E402
from ccxt.test.exchange.base.test_margin_modification import test_margin_modification  # noqa: E402
from ccxt.test.exchange.base.test_market import test_market  # noqa: E402
from ccxt.test.exchange.base.test_ohlcv import test_ohlcv  # noqa: E402
from ccxt.test.exchange.base.test_open_interest import test_open_interest  # noqa: E402
from ccxt.test.exchange.base.test_order import test_order  # noqa: E402
from ccxt.test.exchange.base.test_order_book import test_order_book  # noqa: E402
from ccxt.test.exchange.base.test_position import test_position  # noqa: E402
from ccxt.test.exchange.base.test_status import test_status  # noqa: E402
from ccxt.test.exchange.base.test_ticker import test_ticker  # noqa: E402
from ccxt.test.exchange.base.test_trade import test_trade  # noqa: E402
from ccxt.test.exchange.base.test_trading_fee import test_trading_fee  # noqa: E402
from ccxt.test.exchange.base.test_transfer import test_transfer  # noqa: E402
