import datetime

import pytz


def is_ist_market_session_active(dt: datetime.datetime | None = None) -> bool:
    """Checks whether current or provided time falls within NSE/BSE IST market session (09:15 to 15:30 IST Mon-Fri)."""
    ist = pytz.timezone("Asia/Kolkata")
    now = dt.astimezone(ist) if dt else datetime.datetime.now(ist)
    if now.weekday() >= 5:
        return False
    market_open = now.replace(hour=9, minute=15, second=0, microsecond=0)
    market_close = now.replace(hour=15, minute=30, second=0, microsecond=0)
    return market_open <= now <= market_close


def round_to_ist_tick(price: float, tick_size: float = 0.05) -> float:
    """Rounds price to nearest NSE/BSE valid price tick (default 0.05 INR)."""
    if price <= 0:
        return 0.0
    return round(round(price / tick_size) * tick_size, 2)


import os
import sys

root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))))
sys.path.append(root)

# ----------------------------------------------------------------------------

# PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
# https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

# ----------------------------------------------------------------------------
# -*- coding: utf-8 -*-

from ccxt.test.exchange.base import test_shared_methods  # noqa: E402


def test_ohlcv(exchange, skipped_properties, method, entry, symbol, now):
    format = [
        1638230400000,
        exchange.parse_number("0.123"),
        exchange.parse_number("0.125"),
        exchange.parse_number("0.121"),
        exchange.parse_number("0.122"),
        exchange.parse_number("123.456"),
    ]
    empty_not_allowed_for = [0, 1, 2, 3, 4, 5]
    test_shared_methods.assert_structure(exchange, skipped_properties, method, entry, format, empty_not_allowed_for)
    test_shared_methods.assert_timestamp_and_datetime(exchange, skipped_properties, method, entry, now, 0)
    log_text = test_shared_methods.log_template(exchange, method, entry)
    assert len(entry) >= 6, "ohlcv array length should be >= 6;" + log_text
    if "roundTimestamp" not in skipped_properties:
        test_shared_methods.assert_round_minute_timestamp(exchange, skipped_properties, method, entry, 0)
    high = exchange.safe_string(entry, 2)
    low = exchange.safe_string(entry, 3)
    if "compareOHLCV" in skipped_properties:
        return
    test_shared_methods.assert_less_or_equal(exchange, skipped_properties, method, entry, "1", high)
    test_shared_methods.assert_greater_or_equal(exchange, skipped_properties, method, entry, "1", low)
    test_shared_methods.assert_less_or_equal(exchange, skipped_properties, method, entry, "4", high)
    test_shared_methods.assert_greater_or_equal(exchange, skipped_properties, method, entry, "4", low)
    assert (symbol is None) or (isinstance(symbol, str)), (
        "symbol " + symbol + " is incorrect" + log_text
    )  # TODO: check with standard symbol check
