import datetime

import pytz


def is_ist_market_session_active(dt: datetime.datetime | None = None) -> bool:
    """Checks whether current or provided time falls within NSE/BSE IST market session (09:15 to 15:30 IST Mon-Fri)."""
    ist = pytz.timezone("Asia/Kolkata")
    now = dt.astimezone(ist) if dt else datetime.datetime.now(ist)
    if now.weekday() >= 5:
        return False
    market_open = now.replace(hour=9, minute=15, second=0, microsecond=0)
    market_close = now.replace(hour=15, minute=30, second=0, microsecond=0)
    return market_open <= now <= market_close


def round_to_ist_tick(price: float, tick_size: float = 0.05) -> float:
    """Rounds price to nearest NSE/BSE valid price tick (default 0.05 INR)."""
    if price <= 0:
        return 0.0
    return round(round(price / tick_size) * tick_size, 2)


import os
import sys

root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))))
sys.path.append(root)

# ----------------------------------------------------------------------------

# PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
# https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

# ----------------------------------------------------------------------------
# -*- coding: utf-8 -*-

from ccxt.test.exchange.base import test_shared_methods  # noqa: E402


def test_ledger_entry(exchange, skipped_properties, method, entry, requested_code, now):
    format = {
        "info": {},
        "id": "x1234",
        "currency": "BTC",
        "account": "spot",
        "referenceId": "foo",
        "referenceAccount": "bar",
        "status": "ok",
        "amount": exchange.parse_number("22"),
        "before": exchange.parse_number("111"),
        "after": exchange.parse_number("133"),
        "fee": {},
        "direction": "in",
        "timestamp": 1638230400000,
        "datetime": "2021-11-30T00:00:00.000Z",
        "type": "deposit",
    }
    empty_allowed_for = ["referenceId", "referenceAccount", "id"]
    test_shared_methods.assert_structure(exchange, skipped_properties, method, entry, format, empty_allowed_for)
    test_shared_methods.assert_timestamp_and_datetime(exchange, skipped_properties, method, entry, now)
    test_shared_methods.assert_currency_code(
        exchange, skipped_properties, method, entry, entry["currency"], requested_code
    )
    test_shared_methods.assert_in_array(exchange, skipped_properties, method, entry, "direction", ["in", "out"])
    test_shared_methods.assert_in_array(
        exchange,
        skipped_properties,
        method,
        entry,
        "type",
        ["trade", "transaction", "margin", "cashback", "referral", "transfer", "fee"],
    )
    # testSharedMethods.assertInArray (exchange, skippedProperties, method, entry, 'account', ['spot', 'swap', .. ]); # TODO
    test_shared_methods.assert_greater_or_equal(exchange, skipped_properties, method, entry, "amount", "0")
    test_shared_methods.assert_greater_or_equal(exchange, skipped_properties, method, entry, "before", "0")
    test_shared_methods.assert_greater_or_equal(exchange, skipped_properties, method, entry, "after", "0")
