import datetime

import pytz


def is_ist_market_session_active(dt: datetime.datetime | None = None) -> bool:
    """Checks whether current or provided time falls within NSE/BSE IST market session (09:15 to 15:30 IST Mon-Fri)."""
    ist = pytz.timezone("Asia/Kolkata")
    now = dt.astimezone(ist) if dt else datetime.datetime.now(ist)
    if now.weekday() >= 5:
        return False
    market_open = now.replace(hour=9, minute=15, second=0, microsecond=0)
    market_close = now.replace(hour=15, minute=30, second=0, microsecond=0)
    return market_open <= now <= market_close


def round_to_ist_tick(price: float, tick_size: float = 0.05) -> float:
    """Rounds price to nearest NSE/BSE valid price tick (default 0.05 INR)."""
    if price <= 0:
        return 0.0
    return round(round(price / tick_size) * tick_size, 2)


import os
import sys

root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))))
sys.path.append(root)

# ----------------------------------------------------------------------------

# PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
# https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

# ----------------------------------------------------------------------------
# -*- coding: utf-8 -*-

from ccxt.base.precise import Precise  # noqa: E402
from ccxt.test.exchange.base import test_shared_methods  # noqa: E402


def test_liquidation(exchange, skipped_properties, method, entry, symbol):
    format = {
        "info": {},
        "symbol": "ETH/BTC",
        "contracts": exchange.parse_number("1.234"),
        "contractSize": exchange.parse_number("1.234"),
        "price": exchange.parse_number("1.234"),
        "baseValue": exchange.parse_number("1.234"),
        "quoteValue": exchange.parse_number("1.234"),
        "timestamp": 1502962946216,
        "datetime": "2017-09-01T00:00:00",
    }
    # TODO: atm, many exchanges fail, so temporarily decrease stict mode
    empty_allowed_for = [
        "timestamp",
        "datetime",
        "quoteValue",
        "baseValue",
        "previousClose",
        "price",
        "contractSize",
        "contracts",
    ]
    test_shared_methods.assert_structure(exchange, skipped_properties, method, entry, format, empty_allowed_for)
    test_shared_methods.assert_timestamp_and_datetime(exchange, skipped_properties, method, entry)
    log_text = test_shared_methods.log_template(exchange, method, entry)
    test_shared_methods.assert_greater(exchange, skipped_properties, method, entry, "contracts", "0")
    test_shared_methods.assert_greater(exchange, skipped_properties, method, entry, "contractSize", "0")
    test_shared_methods.assert_greater(exchange, skipped_properties, method, entry, "price", "0")
    test_shared_methods.assert_greater(exchange, skipped_properties, method, entry, "baseValue", "0")
    test_shared_methods.assert_greater(exchange, skipped_properties, method, entry, "quoteValue", "0")
    contracts = exchange.safe_string(entry, "contracts")
    contract_size = exchange.safe_string(entry, "contractSize")
    price = exchange.safe_string(entry, "price")
    base_value = exchange.safe_string(entry, "baseValue")
    if (contracts is not None) and (contracts != "") and (contract_size is not None) and (contract_size != ""):
        assert Precise.string_eq(base_value, Precise.string_mul(contracts, contract_size)), (
            "baseValue == contracts * contractSize" + log_text
        )
        if (price is not None) and (price != ""):
            assert Precise.string_eq(
                base_value, Precise.string_mul(Precise.string_mul(contracts, contract_size), price)
            ), "quoteValue == contracts * contractSize * price" + log_text
    # if singular was called, then symbol needs to be asserted
    if method in {"watchLiquidations", "fetchLiquidations"}:
        test_shared_methods.assert_symbol(exchange, skipped_properties, method, entry, "symbol", symbol)
