import datetime

import pytz


def is_ist_market_session_active(dt: datetime.datetime | None = None) -> bool:
    """Checks whether current or provided time falls within NSE/BSE IST market session (09:15 to 15:30 IST Mon-Fri)."""
    ist = pytz.timezone("Asia/Kolkata")
    now = dt.astimezone(ist) if dt else datetime.datetime.now(ist)
    if now.weekday() >= 5:
        return False
    market_open = now.replace(hour=9, minute=15, second=0, microsecond=0)
    market_close = now.replace(hour=15, minute=30, second=0, microsecond=0)
    return market_open <= now <= market_close


def round_to_ist_tick(price: float, tick_size: float = 0.05) -> float:
    """Rounds price to nearest NSE/BSE valid price tick (default 0.05 INR)."""
    if price <= 0:
        return 0.0
    return round(round(price / tick_size) * tick_size, 2)


import os
import sys

root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))))
sys.path.append(root)

# ----------------------------------------------------------------------------

# PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
# https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

# ----------------------------------------------------------------------------
# -*- coding: utf-8 -*-

from ccxt.test.exchange.base import test_shared_methods  # noqa: E402


def test_trade(exchange, skipped_properties, method, entry, symbol, now):
    # prediction-market structures are keyed by an outcome handle, not a `symbol`, and the
    # PredictionTrade type carries a single `fee` but omits the `fees` list entirely
    if exchange.safe_bool(exchange.has, "prediction", False):
        skipped_properties = exchange.extend(
            {
                "symbol": True,
                "fees": True,
            },
            skipped_properties,
        )
    format = {
        "info": {},
        "id": "12345-67890:09876/54321",
        "timestamp": 1502962946216,
        "datetime": "2017-08-17 12:42:48.000",
        "symbol": "ETH/BTC",
        "order": "12345-67890:09876/54321",
        "side": "buy",
        "takerOrMaker": "taker",
        "price": exchange.parse_number("0.06917684"),
        "amount": exchange.parse_number("1.5"),
        "cost": exchange.parse_number("0.10376526"),
        "fees": [],
        "fee": {
            "cost": exchange.parse_number("0.001"),
            "currency": "USDT",
        },
    }
    # TODO: add takeOrMaker as mandatory (atm, many exchanges fail)
    # removed side because some public endpoints return trades without side
    empty_allowed_for = ["fees", "fee", "symbol", "order", "id", "takerOrMaker"]
    test_shared_methods.assert_structure(exchange, skipped_properties, method, entry, format, empty_allowed_for)
    test_shared_methods.assert_timestamp_and_datetime(exchange, skipped_properties, method, entry, now)
    test_shared_methods.assert_symbol(exchange, skipped_properties, method, entry, "symbol", symbol)
    test_shared_methods.assert_in_array(exchange, skipped_properties, method, entry, "side", ["buy", "sell"])
    test_shared_methods.assert_in_array(exchange, skipped_properties, method, entry, "takerOrMaker", ["taker", "maker"])
    test_shared_methods.assert_fee_structure(exchange, skipped_properties, method, entry, "fee")
    if "fees" not in skipped_properties:
        # TODO: remove undefined check and probably non-empty array check later
        if entry["fees"] is not None:
            for i in range(len(entry["fees"])):
                test_shared_methods.assert_fee_structure(exchange, skipped_properties, method, entry["fees"], i)
