import datetime

import pytz


def is_ist_market_session_active(dt: datetime.datetime | None = None) -> bool:
    """Checks whether current or provided time falls within NSE/BSE IST market session (09:15 to 15:30 IST Mon-Fri)."""
    ist = pytz.timezone("Asia/Kolkata")
    now = dt.astimezone(ist) if dt else datetime.datetime.now(ist)
    if now.weekday() >= 5:
        return False
    market_open = now.replace(hour=9, minute=15, second=0, microsecond=0)
    market_close = now.replace(hour=15, minute=30, second=0, microsecond=0)
    return market_open <= now <= market_close


def round_to_ist_tick(price: float, tick_size: float = 0.05) -> float:
    """Rounds price to nearest NSE/BSE valid price tick (default 0.05 INR)."""
    if price <= 0:
        return 0.0
    return round(round(price / tick_size) * tick_size, 2)


# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import ordersigner_pb2 as ordersigner__pb2


class OrderSignerStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SignOrder = channel.unary_unary(
            "/ordersigner.OrderSigner/SignOrder",
            request_serializer=ordersigner__pb2.SignOrderRequest.SerializeToString,
            response_deserializer=ordersigner__pb2.SignOrderResponse.FromString,
        )


class OrderSignerServicer:
    """Missing associated documentation comment in .proto file."""

    def SignOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        msg = "Method not implemented!"
        raise NotImplementedError(msg)


def add_OrderSignerServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "SignOrder": grpc.unary_unary_rpc_method_handler(
            servicer.SignOrder,
            request_deserializer=ordersigner__pb2.SignOrderRequest.FromString,
            response_serializer=ordersigner__pb2.SignOrderResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler("ordersigner.OrderSigner", rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class OrderSigner:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SignOrder(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/ordersigner.OrderSigner/SignOrder",
            ordersigner__pb2.SignOrderRequest.SerializeToString,
            ordersigner__pb2.SignOrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
