use anyhow::Result;
use async_trait::async_trait;
use longbridge::quote::{
    AdjustType, CalcIndex, Candlestick, CapitalDistributionResponse, CapitalFlowLine,
    HistoryMarketTemperatureResponse, IssuerInfo, MarketTemperature, MarketTradingDays,
    MarketTradingSession, OptionQuote, ParticipantInfo, Period, RequestUpdateWatchlistGroup,
    Security, SecurityBrokers, SecurityCalcIndex, SecurityDepth, SecurityQuote, SecurityStaticInfo,
    StrikePriceInfo, Subscription, Trade, WarrantInfo, WarrantQuote, WatchlistGroup,
};
use longbridge::trade::{
    AccountBalance, CashFlow, EstimateMaxPurchaseQuantityOptions,
    EstimateMaxPurchaseQuantityResponse, Execution, FundPositionsResponse, GetCashFlowOptions,
    GetHistoryExecutionsOptions, GetHistoryOrdersOptions, GetTodayExecutionsOptions,
    GetTodayOrdersOptions, MarginRatio, Order, OrderDetail, ReplaceOrderOptions,
    StockPositionsResponse, SubmitOrderOptions, SubmitOrderResponse,
};
use longbridge::{quote::IntradayLine, Market};
use time::Date;

/// Quote API trait for CLI commands. Implementations wrap the real SDK context;
/// tests use a mock generated by `mockall`.
#[cfg_attr(test, mockall::automock)]
#[async_trait]
pub trait QuoteApi: Send + Sync {
    async fn quote(&self, symbols: Vec<String>) -> Result<Vec<SecurityQuote>>;
    async fn depth(&self, symbol: String) -> Result<SecurityDepth>;
    async fn brokers(&self, symbol: String) -> Result<SecurityBrokers>;
    async fn trades(&self, symbol: String, count: usize) -> Result<Vec<Trade>>;
    async fn intraday(&self, symbol: String) -> Result<Vec<IntradayLine>>;
    async fn candlesticks(
        &self,
        symbol: String,
        period: Period,
        count: usize,
        adjust: AdjustType,
    ) -> Result<Vec<Candlestick>>;
    async fn history_candlesticks_by_date(
        &self,
        symbol: String,
        period: Period,
        adjust: AdjustType,
        start: Option<Date>,
        end: Option<Date>,
    ) -> Result<Vec<Candlestick>>;
    async fn history_candlesticks_by_offset(
        &self,
        symbol: String,
        period: Period,
        adjust: AdjustType,
        count: usize,
    ) -> Result<Vec<Candlestick>>;
    async fn static_info(&self, symbols: Vec<String>) -> Result<Vec<SecurityStaticInfo>>;
    /// US crypto overview (`.BKKT` symbols); returns raw JSON since its shape
    /// differs entirely from `static_info`.
    async fn us_crypto_overview(&self, symbol: String) -> Result<serde_json::Value>;
    async fn calc_indexes(
        &self,
        symbols: Vec<String>,
        indexes: Vec<CalcIndex>,
    ) -> Result<Vec<SecurityCalcIndex>>;
    async fn capital_flow(&self, symbol: String) -> Result<Vec<CapitalFlowLine>>;
    async fn capital_distribution(&self, symbol: String) -> Result<CapitalDistributionResponse>;
    async fn market_temperature(&self, market: Market) -> Result<MarketTemperature>;
    async fn history_market_temperature(
        &self,
        market: Market,
        start: Date,
        end: Date,
    ) -> Result<HistoryMarketTemperatureResponse>;
    async fn trading_session(&self) -> Result<Vec<MarketTradingSession>>;
    async fn trading_days(
        &self,
        market: Market,
        begin: Date,
        end: Date,
    ) -> Result<MarketTradingDays>;
    async fn security_list(&self, market: Market) -> Result<Vec<Security>>;
    async fn participants(&self) -> Result<Vec<ParticipantInfo>>;
    async fn subscriptions(&self) -> Result<Vec<Subscription>>;
    async fn option_quote(&self, symbols: Vec<String>) -> Result<Vec<OptionQuote>>;
    async fn option_chain_expiry_date_list(&self, symbol: String) -> Result<Vec<Date>>;
    async fn option_chain_info_by_date(
        &self,
        symbol: String,
        expiry_date: Date,
    ) -> Result<Vec<StrikePriceInfo>>;
    async fn warrant_quote(&self, symbols: Vec<String>) -> Result<Vec<WarrantQuote>>;
    async fn warrant_list(&self, symbol: String) -> Result<Vec<WarrantInfo>>;
    async fn warrant_issuers(&self) -> Result<Vec<IssuerInfo>>;
    async fn watchlist(&self) -> Result<Vec<WatchlistGroup>>;
    async fn create_watchlist_group(&self, name: String) -> Result<i64>;
    async fn delete_watchlist_group(&self, id: i64) -> Result<()>;
    async fn update_watchlist_group(&self, req: RequestUpdateWatchlistGroup) -> Result<()>;
}

/// Trade API trait for CLI commands.
#[cfg_attr(test, mockall::automock)]
#[async_trait]
pub trait TradeApi: Send + Sync {
    async fn today_orders(&self, opts: GetTodayOrdersOptions) -> Result<Vec<Order>>;
    async fn history_orders(&self, opts: GetHistoryOrdersOptions) -> Result<Vec<Order>>;
    async fn order_detail(&self, order_id: String) -> Result<OrderDetail>;
    async fn today_executions(&self, opts: GetTodayExecutionsOptions) -> Result<Vec<Execution>>;
    async fn history_executions(&self, opts: GetHistoryExecutionsOptions)
        -> Result<Vec<Execution>>;
    async fn submit_order(&self, opts: SubmitOrderOptions) -> Result<SubmitOrderResponse>;
    async fn cancel_order(&self, order_id: String) -> Result<()>;
    async fn replace_order(&self, opts: ReplaceOrderOptions) -> Result<()>;
    async fn account_balance(&self, currency: Option<String>) -> Result<Vec<AccountBalance>>;
    async fn cash_flow(&self, opts: GetCashFlowOptions) -> Result<Vec<CashFlow>>;
    async fn stock_positions(&self) -> Result<StockPositionsResponse>;
    async fn fund_positions(&self) -> Result<FundPositionsResponse>;
    async fn margin_ratio(&self, symbol: String) -> Result<MarginRatio>;
    async fn estimate_max_purchase_quantity(
        &self,
        opts: EstimateMaxPurchaseQuantityOptions,
    ) -> Result<EstimateMaxPurchaseQuantityResponse>;
}

// ──── Production implementations ────────────────────────────────────────────

/// Production `QuoteApi` backed by the global longbridge `QuoteContext`.
pub struct LbQuoteApi {
    ctx: &'static longbridge::quote::QuoteContext,
}

impl LbQuoteApi {
    pub fn new(ctx: &'static longbridge::quote::QuoteContext) -> Self {
        Self { ctx }
    }
}

#[async_trait]
impl QuoteApi for LbQuoteApi {
    async fn quote(&self, symbols: Vec<String>) -> Result<Vec<SecurityQuote>> {
        Ok(self.ctx.quote(symbols).await?)
    }

    async fn depth(&self, symbol: String) -> Result<SecurityDepth> {
        Ok(self.ctx.depth(symbol).await?)
    }

    async fn brokers(&self, symbol: String) -> Result<SecurityBrokers> {
        Ok(self.ctx.brokers(symbol).await?)
    }

    async fn trades(&self, symbol: String, count: usize) -> Result<Vec<Trade>> {
        Ok(self.ctx.trades(symbol, count).await?)
    }

    async fn intraday(&self, symbol: String) -> Result<Vec<IntradayLine>> {
        use longbridge::quote::TradeSessions;
        Ok(self.ctx.intraday(symbol, TradeSessions::Intraday).await?)
    }

    async fn candlesticks(
        &self,
        symbol: String,
        period: Period,
        count: usize,
        adjust: AdjustType,
    ) -> Result<Vec<Candlestick>> {
        use longbridge::quote::TradeSessions;
        Ok(self
            .ctx
            .candlesticks(symbol, period, count, adjust, TradeSessions::Intraday)
            .await?)
    }

    async fn history_candlesticks_by_date(
        &self,
        symbol: String,
        period: Period,
        adjust: AdjustType,
        start: Option<Date>,
        end: Option<Date>,
    ) -> Result<Vec<Candlestick>> {
        use longbridge::quote::TradeSessions;
        Ok(self
            .ctx
            .history_candlesticks_by_date(
                symbol,
                period,
                adjust,
                start,
                end,
                TradeSessions::Intraday,
            )
            .await?)
    }

    async fn history_candlesticks_by_offset(
        &self,
        symbol: String,
        period: Period,
        adjust: AdjustType,
        count: usize,
    ) -> Result<Vec<Candlestick>> {
        use longbridge::quote::TradeSessions;
        Ok(self
            .ctx
            .history_candlesticks_by_offset(
                symbol,
                period,
                adjust,
                false,
                None,
                count,
                TradeSessions::Intraday,
            )
            .await?)
    }

    async fn static_info(&self, symbols: Vec<String>) -> Result<Vec<SecurityStaticInfo>> {
        Ok(self.ctx.static_info(symbols).await?)
    }

    async fn us_crypto_overview(&self, symbol: String) -> Result<serde_json::Value> {
        Ok(serde_json::to_value(
            self.ctx.us_crypto_overview(symbol).await?,
        )?)
    }

    async fn calc_indexes(
        &self,
        symbols: Vec<String>,
        indexes: Vec<CalcIndex>,
    ) -> Result<Vec<SecurityCalcIndex>> {
        Ok(self.ctx.calc_indexes(symbols, indexes).await?)
    }

    async fn capital_flow(&self, symbol: String) -> Result<Vec<CapitalFlowLine>> {
        Ok(self.ctx.capital_flow(symbol).await?)
    }

    async fn capital_distribution(&self, symbol: String) -> Result<CapitalDistributionResponse> {
        Ok(self.ctx.capital_distribution(symbol).await?)
    }

    async fn market_temperature(&self, market: Market) -> Result<MarketTemperature> {
        Ok(self.ctx.market_temperature(market).await?)
    }

    async fn history_market_temperature(
        &self,
        market: Market,
        start: Date,
        end: Date,
    ) -> Result<HistoryMarketTemperatureResponse> {
        Ok(self
            .ctx
            .history_market_temperature(market, start, end)
            .await?)
    }

    async fn trading_session(&self) -> Result<Vec<MarketTradingSession>> {
        Ok(self.ctx.trading_session().await?)
    }

    async fn trading_days(
        &self,
        market: Market,
        begin: Date,
        end: Date,
    ) -> Result<MarketTradingDays> {
        Ok(self.ctx.trading_days(market, begin, end).await?)
    }

    async fn security_list(&self, market: Market) -> Result<Vec<Security>> {
        Ok(self.ctx.security_list(market, None).await?)
    }

    async fn participants(&self) -> Result<Vec<ParticipantInfo>> {
        Ok(self.ctx.participants().await?)
    }

    async fn subscriptions(&self) -> Result<Vec<Subscription>> {
        Ok(self.ctx.subscriptions().await?)
    }

    async fn option_quote(&self, symbols: Vec<String>) -> Result<Vec<OptionQuote>> {
        Ok(self.ctx.option_quote(symbols).await?)
    }

    async fn option_chain_expiry_date_list(&self, symbol: String) -> Result<Vec<Date>> {
        Ok(self.ctx.option_chain_expiry_date_list(symbol).await?)
    }

    async fn option_chain_info_by_date(
        &self,
        symbol: String,
        expiry_date: Date,
    ) -> Result<Vec<StrikePriceInfo>> {
        Ok(self
            .ctx
            .option_chain_info_by_date(symbol, expiry_date)
            .await?)
    }

    async fn warrant_quote(&self, symbols: Vec<String>) -> Result<Vec<WarrantQuote>> {
        Ok(self.ctx.warrant_quote(symbols).await?)
    }

    async fn warrant_list(&self, symbol: String) -> Result<Vec<WarrantInfo>> {
        use longbridge::quote::{SortOrderType, WarrantSortBy};
        Ok(self
            .ctx
            .warrant_list(
                symbol,
                WarrantSortBy::LastDone,
                SortOrderType::Descending,
                None,
                None,
                None,
                None,
                None,
            )
            .await?)
    }

    async fn warrant_issuers(&self) -> Result<Vec<IssuerInfo>> {
        Ok(self.ctx.warrant_issuers().await?)
    }

    async fn watchlist(&self) -> Result<Vec<WatchlistGroup>> {
        Ok(self.ctx.watchlist().await?)
    }

    async fn create_watchlist_group(&self, name: String) -> Result<i64> {
        use longbridge::quote::RequestCreateWatchlistGroup;
        Ok(self
            .ctx
            .create_watchlist_group(RequestCreateWatchlistGroup::new(name))
            .await?)
    }

    async fn delete_watchlist_group(&self, id: i64) -> Result<()> {
        Ok(self.ctx.delete_watchlist_group(id, false).await?)
    }

    async fn update_watchlist_group(&self, req: RequestUpdateWatchlistGroup) -> Result<()> {
        Ok(self.ctx.update_watchlist_group(req).await?)
    }
}

/// Production `TradeApi` backed by the global longbridge `TradeContext`.
pub struct LbTradeApi {
    ctx: &'static longbridge::trade::TradeContext,
}

impl LbTradeApi {
    pub fn new(ctx: &'static longbridge::trade::TradeContext) -> Self {
        Self { ctx }
    }
}

#[async_trait]
impl TradeApi for LbTradeApi {
    async fn today_orders(&self, opts: GetTodayOrdersOptions) -> Result<Vec<Order>> {
        Ok(self.ctx.today_orders(opts).await?)
    }

    async fn history_orders(&self, opts: GetHistoryOrdersOptions) -> Result<Vec<Order>> {
        Ok(self.ctx.history_orders(opts).await?)
    }

    async fn order_detail(&self, order_id: String) -> Result<OrderDetail> {
        Ok(self.ctx.order_detail(order_id).await?)
    }

    async fn today_executions(&self, opts: GetTodayExecutionsOptions) -> Result<Vec<Execution>> {
        Ok(self.ctx.today_executions(opts).await?)
    }

    async fn history_executions(
        &self,
        opts: GetHistoryExecutionsOptions,
    ) -> Result<Vec<Execution>> {
        Ok(self.ctx.history_executions(opts).await?)
    }

    async fn submit_order(&self, opts: SubmitOrderOptions) -> Result<SubmitOrderResponse> {
        Ok(self.ctx.submit_order(opts).await?)
    }

    async fn cancel_order(&self, order_id: String) -> Result<()> {
        Ok(self.ctx.cancel_order(order_id).await?)
    }

    async fn replace_order(&self, opts: ReplaceOrderOptions) -> Result<()> {
        Ok(self.ctx.replace_order(opts).await?)
    }

    async fn account_balance(&self, currency: Option<String>) -> Result<Vec<AccountBalance>> {
        Ok(self.ctx.account_balance(currency.as_deref()).await?)
    }

    async fn cash_flow(&self, opts: GetCashFlowOptions) -> Result<Vec<CashFlow>> {
        Ok(self.ctx.cash_flow(opts).await?)
    }

    async fn stock_positions(&self) -> Result<StockPositionsResponse> {
        Ok(self.ctx.stock_positions(None).await?)
    }

    async fn fund_positions(&self) -> Result<FundPositionsResponse> {
        Ok(self.ctx.fund_positions(None).await?)
    }

    async fn margin_ratio(&self, symbol: String) -> Result<MarginRatio> {
        Ok(self.ctx.margin_ratio(symbol).await?)
    }

    async fn estimate_max_purchase_quantity(
        &self,
        opts: EstimateMaxPurchaseQuantityOptions,
    ) -> Result<EstimateMaxPurchaseQuantityResponse> {
        Ok(self.ctx.estimate_max_purchase_quantity(opts).await?)
    }
}

// ── HTTP helpers ─────────────────────────────────────────────────────────────

pub async fn http_get(
    path: &str,
    params: &[(&str, &str)],
    verbose: bool,
) -> Result<serde_json::Value> {
    http_get_dc(path, params, None, verbose).await
}

/// [`http_get`], but restricting the request to a single data center via the
/// SDK's `dc_restrict` API. Region-limited commands declare their region here; the
/// SDK short-circuits a mismatched session with a unified error.
pub async fn http_get_dc(
    path: &str,
    params: &[(&str, &str)],
    dc_restrict: Option<longbridge::DcRegion>,
    verbose: bool,
) -> Result<serde_json::Value> {
    use longbridge::httpclient::Json;
    use reqwest::Method;

    if verbose {
        let qs = params
            .iter()
            .map(|(k, v)| format!("{k}={v}"))
            .collect::<Vec<_>>()
            .join("&");
        eprintln!("* GET {path}?{qs}");
    }
    let client = crate::openapi::http_client();
    let params: Vec<(&str, &str)> = params.to_vec();
    let mut builder = client.request(Method::GET, path).query_params(params);
    if let Some(region) = dc_restrict {
        builder = builder.dc_restrict(region);
    }
    let resp = builder
        .response::<Json<serde_json::Value>>()
        .send()
        .await
        .map_err(anyhow::Error::from)?;
    let mut v = resp.0;
    super::output::strip_private_fields(&mut v);
    Ok(v)
}

pub async fn http_post(
    path: &str,
    body: serde_json::Value,
    verbose: bool,
) -> Result<serde_json::Value> {
    http_post_dc(path, body, None, verbose).await
}

/// [`http_post`], but restricting the request to a single data center via the
/// SDK's `dc_restrict` API.
pub async fn http_post_dc(
    path: &str,
    body: serde_json::Value,
    dc_restrict: Option<longbridge::DcRegion>,
    verbose: bool,
) -> Result<serde_json::Value> {
    use longbridge::httpclient::Json;
    use reqwest::Method;

    if verbose {
        eprintln!("* POST {path}");
        eprintln!(
            "* Body: {}",
            serde_json::to_string_pretty(&body).unwrap_or_default()
        );
    }
    let client = crate::openapi::http_client();
    let mut builder = client.request(Method::POST, path).body(Json(body));
    if let Some(region) = dc_restrict {
        builder = builder.dc_restrict(region);
    }
    let resp = builder
        .response::<Json<serde_json::Value>>()
        .send()
        .await
        .map_err(anyhow::Error::from)?;
    let mut v = resp.0;
    super::output::strip_private_fields(&mut v);
    Ok(v)
}

pub async fn http_delete(
    path: &str,
    body: serde_json::Value,
    verbose: bool,
) -> Result<serde_json::Value> {
    use longbridge::httpclient::Json;
    use reqwest::Method;

    if verbose {
        eprintln!("* DELETE {path}");
        eprintln!(
            "* Body: {}",
            serde_json::to_string_pretty(&body).unwrap_or_default()
        );
    }
    let client = crate::openapi::http_client();
    let resp = client
        .request(Method::DELETE, path)
        .body(Json(body))
        .response::<Json<serde_json::Value>>()
        .send()
        .await
        .map_err(anyhow::Error::from)?;
    let mut v = resp.0;
    super::output::strip_private_fields(&mut v);
    Ok(v)
}

pub async fn http_put(
    path: &str,
    body: serde_json::Value,
    verbose: bool,
) -> Result<serde_json::Value> {
    use longbridge::httpclient::Json;
    use reqwest::Method;

    if verbose {
        eprintln!("* PUT {path}");
        eprintln!(
            "* Body: {}",
            serde_json::to_string_pretty(&body).unwrap_or_default()
        );
    }
    let client = crate::openapi::http_client();
    let resp = client
        .request(Method::PUT, path)
        .body(Json(body))
        .response::<Json<serde_json::Value>>()
        .send()
        .await
        .map_err(anyhow::Error::from)?;
    let mut v = resp.0;
    super::output::strip_private_fields(&mut v);
    Ok(v)
}