"""
Institutional Integration Suite.
Consolidates advanced machine learning, data science, databases, natural language processing,
advanced quantitative mathematics modules, options & derivatives engines, hedge fund swarms,
extended market connectors, quantitative portfolio analytics, and alpha strategy libraries.
"""

from typing import Any

from . import aat_strategies, itip_signal_store, vibe_quantlib
from .aat_analyst import MacroAnalyst, SMCAnalyst, VolatilityAnalyst
from .advanced_math import calculate_markov_regime_switching_probability, evaluate_black_scholes_option_pricing
from .ai_trader_scoring_engine import (
    AgentScoreResult,
    AITraderChallengeScoringEngine,
    AITraderSignalQualityEvaluator,
    SignalQualityMetrics,
)
from .alpha_strategies_library import AlphaStrategyLibrary
from .apex_trading_engine import (
    ApexGreeksResult,
    ApexLSTMPricePrediction,
    ApexRiskLimitCheck,
    ApexTradingAISignalEngine,
    ApexTradingRiskEngine,
    ApexVaRResult,
)
from .arkorisk_guard import PROP_FIRM_DATABASE, ArkoRiskGuard, DrawdownTaxonomy, MarketType, RiskProfilePreset
from .awesome_llm_agents import DataAnalystAgent, DeepResearchAgent, InvestmentAgent
from .awesome_llm_finance_team import MultiAgentFinanceTeamOrchestrator
from .backtesting_py_suite import (
    BacktestTradeSignal,
    SignalStrategy,
    TrailingStrategy,
    barssince,
    cross,
    crossover,
    resample_apply,
)
from .backtrader_engine import (
    BacktraderAnalyzerEngine,
    BacktraderPerformanceMetrics,
    BacktraderSizerEngine,
    BacktraderSizerResult,
)
from .batch3_quant_strategies import (
    EngulfingAtExtremeStrategy,
    OvernightDriftStrategy,
    PivotReactionZoneStrategy,
    QuantSignal,
    VolatilityExpansionStrategy,
    VWAPFadeStrategy,
)
from .bayesian_consensus import BayesianConsensusEngine, global_bayesian_consensus
from .binance_trade_bot_engine import AltcoinRatio, BridgeCoinScoutEngine, BridgeJumpDecision
from .brain_self_healer import QuantumSelfHealer
from .calculus_quant_engine import GeometricExitEngine, MarketEntropyMonitor, calculate_hma
from .comprehensive_suite import (
    integrate_airflow,
    integrate_akshare,
    integrate_altair,
    integrate_arrow,
    integrate_autots,
    integrate_backtrader,
    integrate_beautifulsoup,
    integrate_bert,
    integrate_bokeh,
    integrate_boto3,
    integrate_catboost,
    integrate_ccxt,
    integrate_chromadb,
    integrate_click,
    integrate_cupy,
    integrate_darts,
    integrate_dask,
    integrate_datatable,
    integrate_django,
    integrate_duckdb,
    integrate_edgartools,
    integrate_faiss,
    integrate_fastapi,
    integrate_flask,
    integrate_folium,
    integrate_gensim,
    integrate_geopandas,
    integrate_github,
    integrate_gpio,
    integrate_great_expectations,
    integrate_hadoop,
    integrate_jax,
    integrate_jupyter,
    integrate_kafka,
    integrate_kats,
    integrate_keras,
    integrate_kivy,
    integrate_koalas,
    integrate_langchain,
    integrate_langextract,
    integrate_langgraph,
    integrate_lifelines,
    integrate_lightgbm,
    integrate_litellm,
    integrate_llamaindex,
    integrate_loguru,
    integrate_matplotlib,
    integrate_modin,
    integrate_neo4j,
    integrate_networkx,
    integrate_nltk,
    integrate_numpy,
    integrate_octoparse,
    integrate_openai,
    integrate_opencv,
    integrate_pandas,
    integrate_pandera,
    integrate_paramiko,
    integrate_peewee,
    integrate_pinecone,
    integrate_pingouin,
    integrate_plotly,
    integrate_pmdarima,
    integrate_polars,
    integrate_polyglot,
    integrate_prophet,
    integrate_pycryptodome,
    integrate_pydantic,
    integrate_pyfolio,
    integrate_pygal,
    integrate_pygame,
    integrate_pymc3,
    integrate_pyo3,
    integrate_pyscript,
    integrate_pyserial,
    integrate_pyspark,
    integrate_pystan,
    integrate_pytest,
    integrate_pytorch,
    integrate_quantlib,
    integrate_ray,
    integrate_requests,
    integrate_rich,
    integrate_robyn,
    integrate_rq,
    integrate_ruff,
    integrate_rust_wrapped_python,
    integrate_scikit_learn,
    integrate_scipy,
    integrate_scrapy,
    integrate_seaborn,
    integrate_selenium,
    integrate_sentence_transformers,
    integrate_sktime,
    integrate_spacy,
    integrate_sqlalchemy,
    integrate_statsmodels,
    integrate_sympy,
    integrate_talib,
    integrate_tensorflow,
    integrate_textblob,
    integrate_textual,
    integrate_theano,
    integrate_tinydb,
    integrate_tkinter,
    integrate_transformers,
    integrate_tsfresh,
    integrate_typer,
    integrate_vaex,
    integrate_xgboost,
    integrate_yfinance,
    integrate_zipline,
)
from .crypto_trader_v2_engine import (
    CryptoTraderV2Engine,
    OBIScalperState,
    OBISignalType,
    OrderBookDepthPayload,
    OrderBookLevel,
    SentimentResult,
)
from .data_science import calculate_portfolio_weights, perform_statistical_pingouin_test
from .databases import insert_vector_embedding, propagate_graph_breakout_warnings, query_high_speed_analytical_duckdb
from .dxtrade_broker_adapter import (
    DXTradeAccountSummary,
    DXTradeBrokerAdapter,
    DXTradeOrderRequest,
    DXTradeOrderResponse,
)
from .ea_scalper_xauusd_engine import AMDCycleTracker, FootprintPocAnalyzer, MarketGapCooldownGuard
from .extended_market_connectors import ExtendedDataConnectors
from .finagent_hedgefund_swarm import HedgeFundSwarmOrchestrator
from .finterion_adapter import (
    FinterionOrderExecutor,
    FinterionOrderRequest,
    FinterionOrderResponse,
    FinterionPingHook,
    FinterionPortfolio,
    FinterionPortfolioProvider,
    FinterionPosition,
)
from .freqtrade_protection_engine import FreqtradeProtectionEngine, LockSide, PairLock, ProtectionCheckResult
from .ftmo_journal_analyzer import FTMOJournalAnalyzer
from .ftmo_risk_guard import FTMOQualificationAuditor, FTMORiskGuardEngine
from .ftmo_temporal_matcher import FewShotTemporalMatcher
from .ftmo_tradingbot_core import (
    CombinedExposureCapGuard,
    ConsensusSizingModulator,
    FTMODynamicStopEngine,
    ScaleOnProfitEngine,
)
from .go_gateway import start_go_concurrency_websocket_relay
from .hummingbot_suite import (
    ArbitrageOpportunity,
    AvellanedaQuote,
    AvellanedaStoikovMarketMakingEngine,
    CrossExchangeArbitrageEngine,
    PureMarketMakingInventorySkewEngine,
    SkewedSpreads,
)
from .ict_system_v2_engine import (
    ICTSignalResult,
    ICTSystemV2Engine,
    MarketBias,
    PDAResult,
    PDAZone,
    SMTDivergenceResult,
    StructureType,
)
from .indian_instrument_scheduler import IndianInstrumentScheduler, global_indian_scheduler
from .indian_market_state_machine import (
    IndianMarketState,
    IndianMarketStateMachine,
    global_indian_state_machine,
    round_to_indian_tick_size,
)
from .jesse_metrics_and_quant_suite import (
    JesseMetricsEngine,
    JessePerformanceReport,
    JesseQuantStrategyLibrary,
    QuantStrategySignal,
)
from .kit_bot_engine import (
    KitAutopilotDecision,
    KitAutopilotManager,
    KitAutopilotMode,
    KitParsedSignal,
    KitPineScriptGenerator,
    KitSocialSignalParser,
)
from .kronos_model import KronosFoundationModel, KronosTokenizer
from .lean_framework_engine import (
    LeanMaximumDrawdownPercentPortfolio,
    LeanPortfolioTarget,
    PairCorrelationResult,
    PearsonCorrelationPairsTradingAlphaModel,
)
from .machine_learning import evaluate_deep_rl_policy_action, generate_multi_model_ensemble_prediction
from .meta_edge_quant import (
    EmpiricalSlippageTracker,
    calculate_edge_score,
    calculate_kelly_fraction,
    calculate_probabilistic_sharpe_ratio,
)
from .ml4t_trading_engine import (
    EigenportfolioDecomposition,
    EigenportfolioResult,
    PurgedWalkForwardCV,
    WalkForwardSplit,
)
from .mql_colab_engine import CandlestickAIClassifier, LatencyArbitrage, SLTPEngine
from .mt5bot_engine import MT5BotVolumeNormalizer, RelativePricePredictionEvaluator
from .natural_language import extract_advanced_nlp_sentiments
from .nautilus_trader_engine import NautilusFixedRiskSizer, NautilusOrderRoutingGuard
from .neoethos_autoresearch import (
    NeoethosAutoResearchEngine,
    NeoethosReplayStats,
    ResearchHypothesisResult,
    ResearchObjectiveConfig,
)
from .nexquant_engine import NexQuantFactorModel, NexQuantPortfolioOptimizer
from .nofx_ai_terminal_engine import (
    NoFxAction,
    NoFxAiModelManager,
    NoFxClampedOrder,
    NoFxMarketDirectionBoard,
    NoFxModelDecision,
    NoFxRiskRuntimeDisposer,
    global_nofx_direction_board,
    global_nofx_disposer,
    global_nofx_model_manager,
)
from .openalgo_engine import OpenAlgoIndianExchangeRouter, OpenAlgoSessionSquareOffManager, OpenAlgoSmartOrderSplitter
from .openbull_analytics import calculate_max_pain, calculate_synthetic_future_price
from .options_derivatives_engine import GammaExposureAnalyzer, OptionsPricingEngine, OptionStrategySimulator
from .prop_firm_calendar_feed import PropFirmCalendarFeedManager, PropFirmTradingEvent
from .prop_firm_elite_tracker import PropFirmEliteMultiAccountAggregator, SignalPulseLogSyncParser
from .prop_firm_monte_carlo_ev import PropChallengeConfig, PropFirmMonteCarloEVEngine, SimulationResult
from .prop_firm_tracker import PropFirmChallengeTracker
from .prop_guard_equity_armor import PropGuardEquityArmorEngine
from .prop_guardian_safety import PROP_FIRMS_DATABASE, PropGuardianMasterFilters
from .propfirm_risk_guard_engine import (
    ConsistencyConfig,
    CutoffConfig,
    DailyLossConfig,
    NewsWindow,
    PropFirmRiskGuardEngine,
    RiskSeverity,
    RiskTick,
    TrailingDDConfig,
)
from .pytrader_gym_suite import DepthAnalysisResult, GymStepResult, PyTraderDepthAnalyzer, TradingGymRLAdapter
from .qma_quant_strategy import QMAQuantStrategy, calculate_ttm_squeeze, detect_rsi_failure_swing
from .quant_backtest_pro_engine import (
    Candle,
    HighPrecisionOrderMatchingEngine,
    MultiAssetMathEngine,
    OrderType,
    PendingOrder,
    Position,
    PositionSide,
    PositionStatus,
    SymbolConfig,
)
from .quant_portfolio_analytics import PortfolioOptimizationEngine, QuantPerformanceMetrics
from .quantdinger_engine import (
    FactorScoreResult,
    GridLevel,
    GridMode,
    GridState,
    QuantDingerFactorResearchEngine,
    QuantDingerGridEngine,
)
from .quantum_quantum_engine import QuantumAutoEngine
from .rc_news_feeder import NewsBlackoutCheck, NewsEvent, NewsImpact, RCNewsFeederEngine
from .rust_bridge import execute_high_speed_rust_order_send
from .sebi_broker_adapter import (
    VALID_INDIAN_EXCHANGES,
    VALID_INDIAN_PRODUCT_TAGS,
    AngelOneAdapter,
    DhanHQAdapter,
    FivePaisaAdapter,
    ICICIDirectAdapter,
    IIFLXTSAdapter,
    KiteConnectAdapter,
    KotakNeoAdapter,
    MotilalOswalAdapter,
    SEBIBrokerAdapter,
    SEBIOrderRequest,
    SEBIOrderResponse,
    UnifiedIndianBrokerClientAdapter,
    UpstoxAdapter,
    round_to_indian_quantity,
    validate_indian_product_tag,
)
from .solana_dex_risk_guard import DEXPoolMetrics, DEXRiskCheckResult, SolanaDEXRiskGuard
from .sovereign_intelligence import SovereignIntelligencePlugin
from .stocksharp_risk_engine import RiskAction, RiskRuleViolation, StockSharpRiskManager
from .superalgos_trading_engine import (
    EpisodeMetrics,
    StageType,
    SuperalgosPosition,
    SuperalgosTradingStagesEngine,
    TriggerStatus,
)
from .systematic_trading_carver import CarverDiversificationResult, CarverForecastScalarResult, PySystemTradeEngine
from .trading_agents_cn_suite import (
    ChinaMarketAnalystAgent,
    ChinaMarketReport,
    DataCompletenessChecker,
    DataCompletenessReport,
    EnhancedNewsFilterEngine,
    FilteredNewsArticle,
)
from .trading_agents_suite import (
    AgentRole,
    BearResearcherAgent,
    BullResearcherAgent,
    DebateRound,
    RiskDebaterAgent,
    TradingAgentsDecision,
    TradingAgentsOrchestrator,
)
from .trading_seatbelt_engine import CooldownStatus, SeatbeltStatus, TradingSeatbeltEngine
from .web_api import fetch_yfinance_external_rates, push_telemetry_to_kafka_queue
from .zipline_finance_engine import (
    CommissionResult,
    RiskControlCheck,
    SlippageResult,
    ZiplineCommissionModel,
    ZiplineRiskControlEngine,
    ZiplineSlippageModel,
)
from .zipline_finance_engine import OrderSide as ZiplineOrderSide

__all__ = [
    "PROP_FIRMS_DATABASE",
    "PROP_FIRM_DATABASE",
    "AITraderChallengeScoringEngine",
    "AITraderSignalQualityEvaluator",
    "AMDCycleTracker",
    "AgentRole",
    "AgentScoreResult",
    "AlphaStrategyLibrary",
    "AltcoinRatio",
    "AngelOneAdapter",
    "ApexGreeksResult",
    "ApexLSTMPricePrediction",
    "ApexRiskLimitCheck",
    "ApexTradingAISignalEngine",
    "ApexTradingRiskEngine",
    "ApexVaRResult",
    "ArbitrageOpportunity",
    "ArkoRiskGuard",
    "AvellanedaQuote",
    "AvellanedaStoikovMarketMakingEngine",
    "BacktestTradeSignal",
    "BacktraderAnalyzerEngine",
    "BacktraderPerformanceMetrics",
    "BacktraderSizerEngine",
    "BacktraderSizerResult",
    "BayesianConsensusEngine",
    "BearResearcherAgent",
    "BridgeCoinScoutEngine",
    "BridgeJumpDecision",
    "BullResearcherAgent",
    "Candle",
    "CandlestickAIClassifier",
    "CarverDiversificationResult",
    "CarverForecastScalarResult",
    "ChinaMarketAnalystAgent",
    "ChinaMarketReport",
    "CombinedExposureCapGuard",
    "CommissionResult",
    "ConsensusSizingModulator",
    "ConsistencyConfig",
    "CooldownStatus",
    "CrossExchangeArbitrageEngine",
    "CryptoTraderV2Engine",
    "CutoffConfig",
    "DEXPoolMetrics",
    "DEXRiskCheckResult",
    "DXTradeAccountSummary",
    "DXTradeBrokerAdapter",
    "DXTradeOrderRequest",
    "DXTradeOrderResponse",
    "DailyLossConfig",
    "DataAnalystAgent",
    "DataCompletenessChecker",
    "DataCompletenessReport",
    "DebateRound",
    "DeepResearchAgent",
    "DepthAnalysisResult",
    "DrawdownTaxonomy",
    "EmpiricalSlippageTracker",
    "EngulfingAtExtremeStrategy",
    "EnhancedNewsFilterEngine",
    "EpisodeMetrics",
    "ExtendedDataConnectors",
    "FTMODynamicStopEngine",
    "FTMOJournalAnalyzer",
    "FTMOQualificationAuditor",
    "FTMORiskGuardEngine",
    "FactorScoreResult",
    "FewShotTemporalMatcher",
    "FilteredNewsArticle",
    "FinterionOrderExecutor",
    "FinterionOrderRequest",
    "FinterionOrderResponse",
    "FinterionPingHook",
    "FinterionPortfolio",
    "FinterionPortfolioProvider",
    "FinterionPosition",
    "FivePaisaAdapter",
    "FootprintPocAnalyzer",
    "FreqtradeProtectionEngine",
    "GammaExposureAnalyzer",
    "GeometricExitEngine",
    "GridLevel",
    "GridMode",
    "GridState",
    "GymStepResult",
    "HedgeFundSwarmOrchestrator",
    "HighPrecisionOrderMatchingEngine",
    "ICICIDirectAdapter",
    "ICTSignalResult",
    "ICTSystemV2Engine",
    "IIFLXTSAdapter",
    "IndianInstrumentScheduler",
    "IndianMarketState",
    "IndianMarketStateMachine",
    "InvestmentAgent",
    "JesseMetricsEngine",
    "JessePerformanceReport",
    "JesseQuantStrategyLibrary",
    "KitAutopilotDecision",
    "KitAutopilotManager",
    "KitAutopilotMode",
    "KitParsedSignal",
    "KitPineScriptGenerator",
    "KitSocialSignalParser",
    "KotakNeoAdapter",
    "KronosFoundationModel",
    "KronosTokenizer",
    "LatencyArbitrage",
    "LeanMaximumDrawdownPercentPortfolio",
    "LeanPortfolioTarget",
    "LockSide",
    "MT5BotVolumeNormalizer",
    "MacroAnalyst",
    "MarketBias",
    "MarketEntropyMonitor",
    "MarketGapCooldownGuard",
    "MarketType",
    "MotilalOswalAdapter",
    "MultiAgentFinanceTeamOrchestrator",
    "MultiAssetMathEngine",
    "NautilusFixedRiskSizer",
    "NautilusOrderRoutingGuard",
    "NeoethosAutoResearchEngine",
    "NeoethosReplayStats",
    "NewsBlackoutCheck",
    "NewsEvent",
    "NewsImpact",
    "NewsWindow",
    "NexQuantFactorModel",
    "NexQuantPortfolioOptimizer",
    "NoFxAction",
    "NoFxAiModelManager",
    "NoFxClampedOrder",
    "NoFxMarketDirectionBoard",
    "NoFxModelDecision",
    "NoFxRiskRuntimeDisposer",
    "OBIScalperState",
    "OBISignalType",
    "OpenAlgoIndianExchangeRouter",
    "OpenAlgoSessionSquareOffManager",
    "OpenAlgoSmartOrderSplitter",
    "OptionStrategySimulator",
    "OptionsPricingEngine",
    "OrderBookDepthPayload",
    "OrderBookLevel",
    "OrderType",
    "OvernightDriftStrategy",
    "PDAResult",
    "PDAZone",
    "PairCorrelationResult",
    "PairLock",
    "PearsonCorrelationPairsTradingAlphaModel",
    "PendingOrder",
    "PivotReactionZoneStrategy",
    "PortfolioOptimizationEngine",
    "Position",
    "PositionSide",
    "PositionStatus",
    "PropChallengeConfig",
    "PropFirmCalendarFeedManager",
    "PropFirmChallengeTracker",
    "PropFirmEliteMultiAccountAggregator",
    "PropFirmMonteCarloEVEngine",
    "PropFirmRiskGuardEngine",
    "PropFirmTradingEvent",
    "PropGuardEquityArmorEngine",
    "PropGuardianMasterFilters",
    "ProtectionCheckResult",
    "PureMarketMakingInventorySkewEngine",
    "PySystemTradeEngine",
    "PyTraderDepthAnalyzer",
    "QMAQuantStrategy",
    "QuantDingerFactorResearchEngine",
    "QuantDingerGridEngine",
    "QuantPerformanceMetrics",
    "QuantSignal",
    "QuantStrategySignal",
    "QuantumAutoEngine",
    "QuantumSelfHealer",
    "RCNewsFeederEngine",
    "RelativePricePredictionEvaluator",
    "ResearchHypothesisResult",
    "ResearchObjectiveConfig",
    "RiskAction",
    "RiskControlCheck",
    "RiskDebaterAgent",
    "RiskProfilePreset",
    "RiskRuleViolation",
    "RiskSeverity",
    "RiskTick",
    "SLTPEngine",
    "SMCAnalyst",
    "SMTDivergenceResult",
    "ScaleOnProfitEngine",
    "SeatbeltStatus",
    "SentimentResult",
    "SignalPulseLogSyncParser",
    "SignalQualityMetrics",
    "SignalStrategy",
    "SimulationResult",
    "SkewedSpreads",
    "SlippageResult",
    "SolanaDEXRiskGuard",
    "SovereignIntelligencePlugin",
    "StageType",
    "StockSharpRiskManager",
    "StructureType",
    "SuperalgosPosition",
    "SuperalgosTradingStagesEngine",
    "SymbolConfig",
    "TradingAgentsDecision",
    "TradingAgentsOrchestrator",
    "TradingGymRLAdapter",
    "TradingSeatbeltEngine",
    "TrailingDDConfig",
    "TrailingStrategy",
    "TriggerStatus",
    "UnifiedIndianBrokerClientAdapter",
    "UpstoxAdapter",
    "VWAPFadeStrategy",
    "VolatilityAnalyst",
    "VolatilityExpansionStrategy",
    "ZiplineCommissionModel",
    "ZiplineOrderSide",
    "ZiplineRiskControlEngine",
    "ZiplineSlippageModel",
    "aat_strategies",
    "barssince",
    "calculate_edge_score",
    "calculate_hma",
    "calculate_kelly_fraction",
    "calculate_markov_regime_switching_probability",
    "calculate_max_pain",
    "calculate_portfolio_weights",
    "calculate_probabilistic_sharpe_ratio",
    "calculate_synthetic_future_price",
    "calculate_ttm_squeeze",
    "cross",
    "crossover",
    "detect_rsi_failure_swing",
    "evaluate_black_scholes_option_pricing",
    "evaluate_deep_rl_policy_action",
    "execute_high_speed_rust_order_send",
    "extract_advanced_nlp_sentiments",
    "fetch_yfinance_external_rates",
    "generate_multi_model_ensemble_prediction",
    "global_bayesian_consensus",
    "global_indian_scheduler",
    "global_indian_state_machine",
    "global_nofx_direction_board",
    "global_nofx_disposer",
    "global_nofx_model_manager",
    "insert_vector_embedding",
    "integrate_pandas",
    "itip_signal_store",
    "perform_statistical_pingouin_test",
    "propagate_graph_breakout_warnings",
    "push_telemetry_to_kafka_queue",
    "query_high_speed_analytical_duckdb",
    "resample_apply",
    "round_to_indian_quantity",
    "round_to_indian_tick_size",
    "start_go_concurrency_websocket_relay",
    "vibe_quantlib",
]
