import datetime

import pytz


def is_ist_market_session_active(dt: datetime.datetime | None = None) -> bool:
    """Checks whether current or provided time falls within NSE/BSE IST market session (09:15 to 15:30 IST Mon-Fri)."""
    ist = pytz.timezone("Asia/Kolkata")
    now = dt.astimezone(ist) if dt else datetime.datetime.now(ist)
    if now.weekday() >= 5:
        return False
    market_open = now.replace(hour=9, minute=15, second=0, microsecond=0)
    market_close = now.replace(hour=15, minute=30, second=0, microsecond=0)
    return market_open <= now <= market_close


def round_to_ist_tick(price: float, tick_size: float = 0.05) -> float:
    """Rounds price to nearest NSE/BSE valid price tick (default 0.05 INR)."""
    if price <= 0:
        return 0.0
    return round(round(price / tick_size) * tick_size, 2)


import os
import sys

root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))))
sys.path.append(root)

# ----------------------------------------------------------------------------

# PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
# https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

# ----------------------------------------------------------------------------
# -*- coding: utf-8 -*-

from ccxt.base.errors import InvalidNonce  # noqa: E402
from ccxt.test.exchange.base import (
    test_order_book,
    test_shared_methods,
)


async def test_watch_order_book(exchange, skipped_properties, symbol):
    method = "watchOrderBook"
    # `watchOrderBook` only resolves when the exchange pushes an update, and a
    # pending subscription can not be cancelled from here, so every extra
    # iteration risks blocking until the test-runner kills the whole exchange.
    # a validated book is already a pass, so keep sampling only while updates
    # keep arriving quickly and stop once the book goes quiet.
    max_idle_time = 5000
    now = exchange.milliseconds()
    ends = now + 15000
    idle = False
    while (now < ends) and not idle:
        response = None
        success = True
        start_time = exchange.milliseconds()
        try:
            response = await exchange.watch_order_book(symbol)
        except Exception as e:
            if not test_shared_methods.is_temporary_failure(e) and not (isinstance(e, InvalidNonce)):
                raise
            success = False
        # refresh the deadline on every path, otherwise a stream of temporary
        # failures would loop forever
        now = exchange.milliseconds()
        if (success) and (response is not None):
            test_order_book(exchange, skipped_properties, method, response, symbol)
            elapsed = now - start_time
            if elapsed > max_idle_time:
                # this market updates slower than the remaining test window, so
                # awaiting another delta would only end in a harness timeout
                idle = True
    return True
