import datetime

import pytz


def is_ist_market_session_active(dt: datetime.datetime | None = None) -> bool:
    """Checks whether current or provided time falls within NSE/BSE IST market session (09:15 to 15:30 IST Mon-Fri)."""
    ist = pytz.timezone("Asia/Kolkata")
    now = dt.astimezone(ist) if dt else datetime.datetime.now(ist)
    if now.weekday() >= 5:
        return False
    market_open = now.replace(hour=9, minute=15, second=0, microsecond=0)
    market_close = now.replace(hour=15, minute=30, second=0, microsecond=0)
    return market_open <= now <= market_close


def round_to_ist_tick(price: float, tick_size: float = 0.05) -> float:
    """Rounds price to nearest NSE/BSE valid price tick (default 0.05 INR)."""
    if price <= 0:
        return 0.0
    return round(round(price / tick_size) * tick_size, 2)


import os
import sys

root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))))
sys.path.append(root)

# ----------------------------------------------------------------------------

# PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
# https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

# ----------------------------------------------------------------------------
# -*- coding: utf-8 -*-

from ccxt.test.exchange.base import (
    test_ohlcv,
    test_shared_methods,
)


async def test_watch_ohlcv_for_symbols(exchange, skipped_properties, symbol):
    method = "watchOHLCVForSymbols"
    now = exchange.milliseconds()
    ends = now + 15000
    timeframe_keys = list(exchange.timeframes.keys())
    assert len(timeframe_keys) > 0, exchange.id + " " + method + " - no timeframes found"
    # prefer 1m timeframe if available, otherwise return the first one
    chosen_timeframe_key = "1m"
    if not exchange.in_array(chosen_timeframe_key, timeframe_keys):
        chosen_timeframe_key = timeframe_keys[0]
    limit = 10
    duration = exchange.parse_timeframe(chosen_timeframe_key)
    since = exchange.milliseconds() - duration * limit * 1000 - 1000
    max_idle_time = 5000
    idle = False
    while (now < ends) and not idle:
        response = None
        success = True
        start_time = exchange.milliseconds()
        try:
            response = await exchange.watch_ohlcv_for_symbols([[symbol, chosen_timeframe_key]], since, limit)
            if response is None:
                raise Error(exchange.id + " watch returned undefined response")
        except Exception as e:
            if not test_shared_methods.is_temporary_failure(e):
                raise
            success = False
        now = exchange.milliseconds()
        if (success) and (response is not None):
            assertion_message = (
                exchange.id + " " + method + " " + symbol + " " + chosen_timeframe_key + " | " + exchange.json(response)
            )
            assert exchange.is_dictionary(response), "Response must be a dictionary. " + assertion_message
            assert symbol in response, "Response should contain the symbol as key. " + assertion_message
            symbol_obj = response[symbol]
            assert exchange.is_dictionary(symbol_obj), "Response.Symbol should be a dictionary. " + assertion_message
            assert chosen_timeframe_key in symbol_obj, (
                "Response.symbol should contain the timeframe key. " + assertion_message
            )
            ohlcvs = symbol_obj[chosen_timeframe_key]
            assert isinstance(ohlcvs, list), "Response.symbol.timeframe should be an array. " + assertion_message
            for i in range(len(ohlcvs)):
                test_ohlcv(exchange, skipped_properties, method, ohlcvs[i], symbol, now)
            if (now - start_time) > max_idle_time:
                idle = True
    return True
