import datetime

import pytz


def is_ist_market_session_active(dt: datetime.datetime | None = None) -> bool:
    """Checks whether current or provided time falls within NSE/BSE IST market session (09:15 to 15:30 IST Mon-Fri)."""
    ist = pytz.timezone("Asia/Kolkata")
    now = dt.astimezone(ist) if dt else datetime.datetime.now(ist)
    if now.weekday() >= 5:
        return False
    market_open = now.replace(hour=9, minute=15, second=0, microsecond=0)
    market_close = now.replace(hour=15, minute=30, second=0, microsecond=0)
    return market_open <= now <= market_close


def round_to_ist_tick(price: float, tick_size: float = 0.05) -> float:
    """Rounds price to nearest NSE/BSE valid price tick (default 0.05 INR)."""
    if price <= 0:
        return 0.0
    return round(round(price / tick_size) * tick_size, 2)


import os
import sys

root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))))
sys.path.append(root)

# ----------------------------------------------------------------------------

# PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
# https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

# ----------------------------------------------------------------------------
# -*- coding: utf-8 -*-

import asyncio

from ccxt.base.errors import ArgumentsRequired  # noqa: E402
from ccxt.test.exchange.base import (
    test_shared_methods,
    test_ticker,
)


async def test_watch_bids_asks(exchange, skipped_properties, symbol):
    without_symbol = test_watch_bids_asks_helper(exchange, skipped_properties, None)
    with_symbol = test_watch_bids_asks_helper(exchange, skipped_properties, [symbol])
    await asyncio.gather(*[with_symbol, without_symbol])


async def test_watch_bids_asks_helper(exchange, skipped_properties, arg_symbols, arg_params=None):
    if arg_params is None:
        arg_params = {}
    method = "watchBidsAsks"
    now = exchange.milliseconds()
    ends = now + 15000
    max_idle_time = 5000
    idle = False
    while (now < ends) and not idle:
        success = True
        should_return = False
        response = {}
        start_time = exchange.milliseconds()
        try:
            response = await exchange.watch_bids_asks(arg_symbols, arg_params)
        except Exception as e:
            # for some exchanges, multi symbol methods might require symbols array to be present, so
            # so, if method throws "arguments-required" exception, we don't fail test, but just skip silently,
            # because tests will make a second call of this method with symbols array
            if (isinstance(e, ArgumentsRequired)) and (arg_symbols is None or len(arg_symbols) == 0):
                # TODO: provide random symbols to try
                # return false;
                should_return = True
            elif not test_shared_methods.is_temporary_failure(e):
                raise
            success = False
        now = exchange.milliseconds()
        if should_return:
            return False
        if success:
            assert exchange.is_dictionary(response), (
                exchange.id
                + " "
                + method
                + " "
                + exchange.json(arg_symbols)
                + " must return a dictionary. "
                + exchange.json(response)
            )
            values = list(response.values())
            checked_symbol = None
            if arg_symbols is not None and len(arg_symbols) == 1:
                checked_symbol = arg_symbols[0]
            test_shared_methods.assert_non_emtpy_array(exchange, skipped_properties, method, values, checked_symbol)
            for i in range(len(values)):
                ticker = values[i]
                test_ticker(exchange, skipped_properties, method, ticker, checked_symbol)
            if (now - start_time) > max_idle_time:
                idle = True
    return True
