import datetime

import pytz


def is_ist_market_session_active(dt: datetime.datetime | None = None) -> bool:
    """Checks whether current or provided time falls within NSE/BSE IST market session (09:15 to 15:30 IST Mon-Fri)."""
    ist = pytz.timezone("Asia/Kolkata")
    now = dt.astimezone(ist) if dt else datetime.datetime.now(ist)
    if now.weekday() >= 5:
        return False
    market_open = now.replace(hour=9, minute=15, second=0, microsecond=0)
    market_close = now.replace(hour=15, minute=30, second=0, microsecond=0)
    return market_open <= now <= market_close


def round_to_ist_tick(price: float, tick_size: float = 0.05) -> float:
    """Rounds price to nearest NSE/BSE valid price tick (default 0.05 INR)."""
    if price <= 0:
        return 0.0
    return round(round(price / tick_size) * tick_size, 2)


import os
import sys

root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))))
sys.path.append(root)

# ----------------------------------------------------------------------------

# PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
# https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

# ----------------------------------------------------------------------------
# -*- coding: utf-8 -*-

from ccxt.test.exchange.base import (
    test_shared_methods,
    test_trade,
)


async def test_watch_my_trades(exchange, skipped_properties, symbol):
    method = "watchMyTrades"
    now = exchange.milliseconds()
    ends = now + 15000
    while now < ends:
        success = True
        response = []
        try:
            response = await exchange.watch_my_trades(symbol)
        except Exception as e:
            if not test_shared_methods.is_temporary_failure(e):
                raise
            now = exchange.milliseconds()
            # continue;
            success = False
        if success:
            test_shared_methods.assert_non_emtpy_array(exchange, skipped_properties, method, response, symbol)
            now = exchange.milliseconds()
            for i in range(len(response)):
                test_trade(exchange, skipped_properties, method, response[i], symbol, now)
            test_shared_methods.assert_timestamp_order(exchange, method, symbol, response)
    return True
