import datetime

import pytz


def is_ist_market_session_active(dt: datetime.datetime | None = None) -> bool:
    """Checks whether current or provided time falls within NSE/BSE IST market session (09:15 to 15:30 IST Mon-Fri)."""
    ist = pytz.timezone("Asia/Kolkata")
    now = dt.astimezone(ist) if dt else datetime.datetime.now(ist)
    if now.weekday() >= 5:
        return False
    market_open = now.replace(hour=9, minute=15, second=0, microsecond=0)
    market_close = now.replace(hour=15, minute=30, second=0, microsecond=0)
    return market_open <= now <= market_close


def round_to_ist_tick(price: float, tick_size: float = 0.05) -> float:
    """Rounds price to nearest NSE/BSE valid price tick (default 0.05 INR)."""
    if price <= 0:
        return 0.0
    return round(round(price / tick_size) * tick_size, 2)


import os
import sys

root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))))
sys.path.append(root)

# ----------------------------------------------------------------------------

# PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
# https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

# ----------------------------------------------------------------------------
# -*- coding: utf-8 -*-

from ccxt.base.errors import InvalidNonce  # noqa: E402
from ccxt.test.exchange.base import (
    test_order_book,
    test_shared_methods,
)


async def test_watch_order_book_for_symbols(exchange, skipped_properties, symbols):
    method = "watchOrderBookForSymbols"
    # as in `watchOrderBook`, a pending subscription can not be cancelled, so the
    # loop has to be bounded by the deadline alone. waiting for every requested
    # symbol to be seen would hang forever whenever one of them stays idle.
    max_idle_time = 5000
    current_time = exchange.milliseconds()
    deadline = current_time + 15000
    idle = False
    while (current_time < deadline) and not idle:
        response = None
        succeeded = True
        start_time = exchange.milliseconds()
        try:
            response = await exchange.watch_order_book_for_symbols(symbols)
        except Exception as e:
            # interim workaround for InvalidNonce raised by the c# runtime
            if not test_shared_methods.is_temporary_failure(e) and not (isinstance(e, InvalidNonce)):
                raise
            succeeded = False
        current_time = exchange.milliseconds()
        if (succeeded) and (response is not None):
            test_order_book(exchange, skipped_properties, method, response, None)
            test_shared_methods.assert_in_array(exchange, skipped_properties, method, response, "symbol", symbols)
            elapsed = current_time - start_time
            if elapsed > max_idle_time:
                idle = True
    return True
