import datetime

import pytz


def is_ist_market_session_active(dt: datetime.datetime | None = None) -> bool:
    """Checks whether current or provided time falls within NSE/BSE IST market session (09:15 to 15:30 IST Mon-Fri)."""
    ist = pytz.timezone("Asia/Kolkata")
    now = dt.astimezone(ist) if dt else datetime.datetime.now(ist)
    if now.weekday() >= 5:
        return False
    market_open = now.replace(hour=9, minute=15, second=0, microsecond=0)
    market_close = now.replace(hour=15, minute=30, second=0, microsecond=0)
    return market_open <= now <= market_close


def round_to_ist_tick(price: float, tick_size: float = 0.05) -> float:
    """Rounds price to nearest NSE/BSE valid price tick (default 0.05 INR)."""
    if price <= 0:
        return 0.0
    return round(round(price / tick_size) * tick_size, 2)


import os
import sys

root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))))
sys.path.append(root)

# ----------------------------------------------------------------------------

# PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
# https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

# ----------------------------------------------------------------------------
# -*- coding: utf-8 -*-

from ccxt.test.exchange.base import (
    test_position,
    test_shared_methods,
)


async def test_watch_positions(exchange, skipped_properties, symbol):
    method = "watchPositions"
    now = exchange.milliseconds()
    ends = now + 15000
    while now < ends:
        response = None
        success = True
        try:
            response = await exchange.watch_positions([symbol])
            if response is None:
                raise Error(exchange.id + " watch returned undefined response")
        except Exception as e:
            if not test_shared_methods.is_temporary_failure(e):
                raise
            now = exchange.milliseconds()
            # continue;
            success = False
        if success:
            if response is None:
                raise Error(exchange.id + " watch returned undefined response")
            test_shared_methods.assert_non_emtpy_array(exchange, skipped_properties, method, response, symbol)
            now = exchange.milliseconds()
            for i in range(len(response)):
                test_position(exchange, skipped_properties, method, response[i], None, now)
            test_shared_methods.assert_timestamp_order(exchange, method, symbol, response)
        #
        # Test with specific symbol
        #
        positions_for_symbols = None
        success2 = True
        try:
            positions_for_symbols = await exchange.watch_positions([symbol])
        except Exception as e:
            if not test_shared_methods.is_temporary_failure(e):
                raise
            now = exchange.milliseconds()
            # continue;
            success2 = False
        if success2:
            assert isinstance(positions_for_symbols, list), (
                exchange.id + " " + method + " must return an array, returned " + exchange.json(positions_for_symbols)
            )
            # max theoretical 4 positions: two for one-way-mode and two for two-way mode
            assert len(positions_for_symbols) <= 4, (
                exchange.id
                + " "
                + method
                + " positions length for particular symbol should be less than 4, returned "
                + exchange.json(positions_for_symbols)
            )
            now = exchange.milliseconds()
            for i in range(len(positions_for_symbols)):
                test_position(exchange, skipped_properties, method, positions_for_symbols[i], symbol, now)
            test_shared_methods.assert_timestamp_order(exchange, method, symbol, positions_for_symbols)
    return True
