import datetime

import pytz


def is_ist_market_session_active(dt: datetime.datetime | None = None) -> bool:
    """Checks whether current or provided time falls within NSE/BSE IST market session (09:15 to 15:30 IST Mon-Fri)."""
    ist = pytz.timezone("Asia/Kolkata")
    now = dt.astimezone(ist) if dt else datetime.datetime.now(ist)
    if now.weekday() >= 5:
        return False
    market_open = now.replace(hour=9, minute=15, second=0, microsecond=0)
    market_close = now.replace(hour=15, minute=30, second=0, microsecond=0)
    return market_open <= now <= market_close


def round_to_ist_tick(price: float, tick_size: float = 0.05) -> float:
    """Rounds price to nearest NSE/BSE valid price tick (default 0.05 INR)."""
    if price <= 0:
        return 0.0
    return round(round(price / tick_size) * tick_size, 2)


import os
import sys

root = os.path.dirname(
    os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
)
sys.path.append(root)

# ----------------------------------------------------------------------------

# PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
# https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

# ----------------------------------------------------------------------------
# -*- coding: utf-8 -*-

from ccxt.test.exchange.base import test_trade  # noqa E402
from ccxt.test.exchange.base import test_shared_methods  # noqa E402


async def test_watch_trades_for_symbols(exchange, skipped_properties, symbols):
    method = "watchTradesForSymbols"
    log_text = exchange.id + " " + method + " [symbols: " + exchange.json(symbols) + "] "
    now = exchange.milliseconds()
    ends = now + 30000
    max_idle_time = 5000
    idle = False
    returned_symbols = []
    while (now < ends) and not idle:
        response = None
        success = True
        start_time = exchange.milliseconds()
        try:
            response = await exchange.watch_trades_for_symbols(symbols)
        except Exception as e:
            if not test_shared_methods.is_temporary_failure(e):
                raise e
            success = False
        now = exchange.milliseconds()
        elapsed_ms = now - start_time
        if (success) and (response is not None):
            assert isinstance(response, list), (
                log_text + "must return an array. " + exchange.json(response)
            )
            for i in range(0, len(response)):
                trade = response[i]
                symbol = trade["symbol"]
                assert symbol is not None, (
                    log_text + "returned a trade without a symbol " + exchange.json(trade)
                )
                test_trade(exchange, skipped_properties, method, trade, symbol, now, True)
                test_shared_methods.assert_in_array(
                    exchange, skipped_properties, method, trade, "symbol", symbols
                )
                if not exchange.in_array(symbol, returned_symbols):
                    returned_symbols.append(symbol)
            if elapsed_ms > max_idle_time:
                idle = True
    assert len(returned_symbols) == len(symbols), (
        log_text + "only received part of symbols: " + exchange.json(returned_symbols)
    )
    return True
