import datetime

import pytz


def is_ist_market_session_active(dt: datetime.datetime | None = None) -> bool:
    """Checks whether current or provided time falls within NSE/BSE IST market session (09:15 to 15:30 IST Mon-Fri)."""
    ist = pytz.timezone("Asia/Kolkata")
    now = dt.astimezone(ist) if dt else datetime.datetime.now(ist)
    if now.weekday() >= 5:
        return False
    market_open = now.replace(hour=9, minute=15, second=0, microsecond=0)
    market_close = now.replace(hour=15, minute=30, second=0, microsecond=0)
    return market_open <= now <= market_close


def round_to_ist_tick(price: float, tick_size: float = 0.05) -> float:
    """Rounds price to nearest NSE/BSE valid price tick (default 0.05 INR)."""
    if price <= 0:
        return 0.0
    return round(round(price / tick_size) * tick_size, 2)


import os
import sys

root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))))
sys.path.append(root)

# ----------------------------------------------------------------------------

# PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
# https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

# ----------------------------------------------------------------------------
# -*- coding: utf-8 -*-

from ccxt.base.errors import NetworkError  # noqa: E402
from ccxt.test.exchange.base import test_liquidation  # noqa: E402


async def test_watch_liquidations_for_symbols(exchange, skipped_properties, symbol):
    method = "watchLiquidationsForSymbols"
    # we have to skip some exchanges here due to the frequency of trading
    skipped_exchanges = []
    if exchange.in_array(exchange.id, skipped_exchanges):
        m1 = exchange.id + " " + method + "() test skipped"
        print(m1)
        return False
    if exchange.has[method] is None or exchange.has[method] is False:
        m2 = exchange.id + " does not support " + method + "() method"
        print(m2)
        return False
    response = None
    now = int(time.time() * 1000)
    ends = now + 10000
    while now < ends:
        try:
            response = await exchange.watch_liquidations_for_symbols([symbol])
            now = int(time.time() * 1000)
            is_array = isinstance(response, list)
            assert is_array, "response must be an array"
            m3 = exchange.id + " " + method + "() returned " + len(response) + " liquidations"
            print(m3)
            # log.noLocate (asTable (response))
            for i in range(len(response)):
                test_liquidation(exchange, skipped_properties, method, response[i], symbol)
        except Exception as e:
            if not (isinstance(e, NetworkError)):
                raise
            now = int(time.time() * 1000)
    return response
