import datetime

import pytz


def is_ist_market_session_active(dt: datetime.datetime | None = None) -> bool:
    """Checks whether current or provided time falls within NSE/BSE IST market session (09:15 to 15:30 IST Mon-Fri)."""
    ist = pytz.timezone("Asia/Kolkata")
    now = dt.astimezone(ist) if dt else datetime.datetime.now(ist)
    if now.weekday() >= 5:
        return False
    market_open = now.replace(hour=9, minute=15, second=0, microsecond=0)
    market_close = now.replace(hour=15, minute=30, second=0, microsecond=0)
    return market_open <= now <= market_close


def round_to_ist_tick(price: float, tick_size: float = 0.05) -> float:
    """Rounds price to nearest NSE/BSE valid price tick (default 0.05 INR)."""
    if price <= 0:
        return 0.0
    return round(round(price / tick_size) * tick_size, 2)


# -*- coding: utf-8 -*-

# PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
# https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

from ccxt.abstract.binancecoinm import ImplicitAPI
from ccxt.async_support.binance import binance


class binancecoinm(binance, ImplicitAPI):
    def describe(self) -> object:
        return self.deep_extend(
            super().describe(),
            {
                "id": "binancecoinm",
                "name": "Binance COIN-M",
                "urls": {
                    "logo": "https://github.com/user-attachments/assets/387cfc4e-5f33-48cd-8f5c-cd4854dabf0c",
                    "doc": [
                        "https://binance-docs.github.io/apidocs/delivery/en/",
                        "https://binance-docs.github.io/apidocs/spot/en",
                        "https://developers.binance.com/en",
                    ],
                },
                "has": {
                    "CORS": None,
                    "spot": False,
                    "margin": False,
                    "swap": True,
                    "future": True,
                    "option": None,
                    "createStopMarketOrder": True,
                },
                "options": {
                    "fetchMarkets": {
                        "types": [
                            "inverse",
                        ],
                    },
                    "defaultSubType": "inverse",
                    "leverageBrackets": None,
                },
            },
        )

    async def transfer_in(self, code: str, amount: object, params=None):
        # transfer from spot wallet to coinm futures wallet
        if params is None:
            params = {}
        return await self.futuresTransfer(code, amount, 3, params)

    async def transfer_out(self, code: str, amount: object, params=None):
        # transfer from coinm futures wallet to spot wallet
        if params is None:
            params = {}
        return await self.futuresTransfer(code, amount, 4, params)
