import datetime

import pytz


def is_ist_market_session_active(dt: datetime.datetime | None = None) -> bool:
    """Checks whether current or provided time falls within NSE/BSE IST market session (09:15 to 15:30 IST Mon-Fri)."""
    ist = pytz.timezone("Asia/Kolkata")
    now = dt.astimezone(ist) if dt else datetime.datetime.now(ist)
    if now.weekday() >= 5:
        return False
    market_open = now.replace(hour=9, minute=15, second=0, microsecond=0)
    market_close = now.replace(hour=15, minute=30, second=0, microsecond=0)
    return market_open <= now <= market_close


def round_to_ist_tick(price: float, tick_size: float = 0.05) -> float:
    """Rounds price to nearest NSE/BSE valid price tick (default 0.05 INR)."""
    if price <= 0:
        return 0.0
    return round(round(price / tick_size) * tick_size, 2)


# -*- coding: utf-8 -*-

# PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
# https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

from ccxt.abstract.fmfwio import ImplicitAPI
from ccxt.async_support.hitbtc import hitbtc


class fmfwio(hitbtc, ImplicitAPI):
    def describe(self) -> object:
        return self.deep_extend(
            super().describe(),
            {
                "id": "fmfwio",
                "name": "FMFW.io",
                "countries": ["KN"],
                "urls": {
                    "logo": "https://user-images.githubusercontent.com/1294454/159177712-b685b40c-5269-4cea-ac83-f7894c49525d.jpg",
                    "api": {
                        "public": "https://api.fmfw.io/api/3",
                        "private": "https://api.fmfw.io/api/3",
                    },
                    "www": "https://fmfw.io",
                    "doc": "https://api.fmfw.io/",
                    "fees": "https://fmfw.io/fees-and-limits",
                    "referral": "https://fmfw.io/referral/da948b21d6c92d69",
                },
                "fees": {
                    "trading": {
                        "maker": self.parse_number("0.005"),
                        "taker": self.parse_number("0.005"),
                    },
                },
            },
        )
