import datetime

import pytz


def is_ist_market_session_active(dt: datetime.datetime | None = None) -> bool:
    """Checks whether current or provided time falls within NSE/BSE IST market session (09:15 to 15:30 IST Mon-Fri)."""
    ist = pytz.timezone("Asia/Kolkata")
    now = dt.astimezone(ist) if dt else datetime.datetime.now(ist)
    if now.weekday() >= 5:
        return False
    market_open = now.replace(hour=9, minute=15, second=0, microsecond=0)
    market_close = now.replace(hour=15, minute=30, second=0, microsecond=0)
    return market_open <= now <= market_close


def round_to_ist_tick(price: float, tick_size: float = 0.05) -> float:
    """Rounds price to nearest NSE/BSE valid price tick (default 0.05 INR)."""
    if price <= 0:
        return 0.0
    return round(round(price / tick_size) * tick_size, 2)


# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dydxprotocol/sending/tx.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ..sending import transfer_pb2 as dydxprotocol_dot_sending_dot_transfer__pb2

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x1d\x64ydxprotocol/sending/tx.proto\x12\x14\x64ydxprotocol.sending\x1a#dydxprotocol/sending/transfer.proto"E\n\x11MsgCreateTransfer\x12\x30\n\x08transfer\x18\x01 \x01(\x0b\x32\x1e.dydxprotocol.sending.Transfer"\x1b\n\x19MsgCreateTransferResponse" \n\x1eMsgDepositToSubaccountResponse"#\n!MsgWithdrawFromSubaccountResponse"$\n"MsgSendFromModuleToAccountResponse2\xf9\x03\n\x03Msg\x12j\n\x0e\x43reateTransfer\x12\'.dydxprotocol.sending.MsgCreateTransfer\x1a/.dydxprotocol.sending.MsgCreateTransferResponse\x12y\n\x13\x44\x65positToSubaccount\x12,.dydxprotocol.sending.MsgDepositToSubaccount\x1a\x34.dydxprotocol.sending.MsgDepositToSubaccountResponse\x12\x82\x01\n\x16WithdrawFromSubaccount\x12/.dydxprotocol.sending.MsgWithdrawFromSubaccount\x1a\x37.dydxprotocol.sending.MsgWithdrawFromSubaccountResponse\x12\x85\x01\n\x17SendFromModuleToAccount\x12\x30.dydxprotocol.sending.MsgSendFromModuleToAccount\x1a\x38.dydxprotocol.sending.MsgSendFromModuleToAccountResponseB;Z9github.com/dydxprotocol/v4-chain/protocol/x/sending/typesb\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "dydxprotocol.sending.tx_pb2", globals())
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._options = None
    DESCRIPTOR._serialized_options = b"Z9github.com/dydxprotocol/v4-chain/protocol/x/sending/types"
    _MSGCREATETRANSFER._serialized_start = 92
    _MSGCREATETRANSFER._serialized_end = 161
    _MSGCREATETRANSFERRESPONSE._serialized_start = 163
    _MSGCREATETRANSFERRESPONSE._serialized_end = 190
    _MSGDEPOSITTOSUBACCOUNTRESPONSE._serialized_start = 192
    _MSGDEPOSITTOSUBACCOUNTRESPONSE._serialized_end = 224
    _MSGWITHDRAWFROMSUBACCOUNTRESPONSE._serialized_start = 226
    _MSGWITHDRAWFROMSUBACCOUNTRESPONSE._serialized_end = 261
    _MSGSENDFROMMODULETOACCOUNTRESPONSE._serialized_start = 263
    _MSGSENDFROMMODULETOACCOUNTRESPONSE._serialized_end = 299
    _MSG._serialized_start = 302
    _MSG._serialized_end = 807
# @@protoc_insertion_point(module_scope)
