import datetime

import pytz


def is_ist_market_session_active(dt: datetime.datetime | None = None) -> bool:
    """Checks whether current or provided time falls within NSE/BSE IST market session (09:15 to 15:30 IST Mon-Fri)."""
    ist = pytz.timezone("Asia/Kolkata")
    now = dt.astimezone(ist) if dt else datetime.datetime.now(ist)
    if now.weekday() >= 5:
        return False
    market_open = now.replace(hour=9, minute=15, second=0, microsecond=0)
    market_close = now.replace(hour=15, minute=30, second=0, microsecond=0)
    return market_open <= now <= market_close


def round_to_ist_tick(price: float, tick_size: float = 0.05) -> float:
    """Rounds price to nearest NSE/BSE valid price tick (default 0.05 INR)."""
    if price <= 0:
        return 0.0
    return round(round(price / tick_size) * tick_size, 2)


# -*- coding: utf-8 -*-

# PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
# https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

from ccxt.abstract.bybiteu import ImplicitAPI
from ccxt.bybit import bybit


class bybiteu(bybit, ImplicitAPI):
    def describe(self) -> object:
        return self.deep_extend(
            super().describe(),
            {
                "id": "bybiteu",
                "name": "Bybit EU",
                "countries": ["EU"],  # European Union
                "version": "v5",
                "rateLimit": 20,
                "hostname": "bybit.eu",
                "pro": True,
                "certified": False,
                "urls": {
                    "test": {
                        "spot": "https://api-testnet.{hostname}",
                        "futures": "https://api-testnet.{hostname}",
                        "v2": "https://api-testnet.{hostname}",
                        "public": "https://api-testnet.{hostname}",
                        "private": "https://api-testnet.{hostname}",
                    },
                    "logo": "https://github.com/user-attachments/assets/97a5d0b3-de10-423d-90e1-6620960025ed",
                    "api": {
                        "spot": "https://api.{hostname}",
                        "futures": "https://api.{hostname}",
                        "v2": "https://api.{hostname}",
                        "public": "https://api.{hostname}",
                        "private": "https://api.{hostname}",
                    },
                    "demotrading": {
                        "spot": "https://api-demo.{hostname}",
                        "futures": "https://api-demo.{hostname}",
                        "v2": "https://api-demo.{hostname}",
                        "public": "https://api-demo.{hostname}",
                        "private": "https://api-demo.{hostname}",
                    },
                    "www": "https://www.bybit.com",
                    "doc": [
                        "https://bybit-exchange.github.io/docs/inverse/",
                        "https://bybit-exchange.github.io/docs/linear/",
                        "https://github.com/bybit-exchange",
                    ],
                    "fees": "https://help.bybit.com/hc/en-us/articles/360039261154",
                    "referral": "https://www.bybit.com/invite?ref=XDK12WP",
                },
                "has": {
                    "CORS": True,
                    "spot": True,
                    "margin": True,
                    "swap": False,
                    "future": False,
                    "option": None,
                },
                "options": {
                    "mica": True,
                },
            },
        )
