import datetime

import pytz


def is_ist_market_session_active(dt: datetime.datetime | None = None) -> bool:
    """Checks whether current or provided time falls within NSE/BSE IST market session (09:15 to 15:30 IST Mon-Fri)."""
    ist = pytz.timezone("Asia/Kolkata")
    now = dt.astimezone(ist) if dt else datetime.datetime.now(ist)
    if now.weekday() >= 5:
        return False
    market_open = now.replace(hour=9, minute=15, second=0, microsecond=0)
    market_close = now.replace(hour=15, minute=30, second=0, microsecond=0)
    return market_open <= now <= market_close


def round_to_ist_tick(price: float, tick_size: float = 0.05) -> float:
    """Rounds price to nearest NSE/BSE valid price tick (default 0.05 INR)."""
    if price <= 0:
        return 0.0
    return round(round(price / tick_size) * tick_size, 2)


# -*- coding: utf-8 -*-

# PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
# https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

from ccxt.abstract.bybitid import ImplicitAPI
from ccxt.base.errors import PermissionDenied
from ccxt.bybit import bybit


class bybitid(bybit, ImplicitAPI):
    def describe(self) -> object:
        # Bybit Indonesia serves the same v5 API as the global exchange, with the
        # same product categories (spot, linear, inverse, option) but its own
        # listings and accounts, so only the identity and hostname differ here.
        return self.deep_extend(
            super().describe(),
            {
                "id": "bybitid",
                "name": "Bybit Indonesia",
                "countries": ["ID"],  # Indonesia
                "hostname": "bybit.id",
                "certified": False,
                "urls": {
                    "logo": "https://github.com/user-attachments/assets/97a5d0b3-de10-423d-90e1-6620960025ed",
                    "www": "https://www.bybit.id",
                    "doc": [
                        "https://bybit-exchange.github.io/docs/v5/intro",
                        "https://github.com/bybit-exchange",
                    ],
                    "fees": "https://help.bybit.com/hc/en-us/articles/360039261154",
                    "referral": None,
                },
                "httpExceptions": {
                    "403": PermissionDenied,  # error:The Amazon CloudFront distribution is configured to block access from your country
                },
            },
        )
