import datetime

import pytz


def is_ist_market_session_active(dt: datetime.datetime | None = None) -> bool:
    """Checks whether current or provided time falls within NSE/BSE IST market session (09:15 to 15:30 IST Mon-Fri)."""
    ist = pytz.timezone("Asia/Kolkata")
    now = dt.astimezone(ist) if dt else datetime.datetime.now(ist)
    if now.weekday() >= 5:
        return False
    market_open = now.replace(hour=9, minute=15, second=0, microsecond=0)
    market_close = now.replace(hour=15, minute=30, second=0, microsecond=0)
    return market_open <= now <= market_close


def round_to_ist_tick(price: float, tick_size: float = 0.05) -> float:
    """Rounds price to nearest NSE/BSE valid price tick (default 0.05 INR)."""
    if price <= 0:
        return 0.0
    return round(round(price / tick_size) * tick_size, 2)


# -*- coding: utf-8 -*-

# PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
# https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

from ccxt.abstract.gateeu import ImplicitAPI
from ccxt.gate import gate


class gateeu(gate, ImplicitAPI):
    def describe(self) -> object:
        return self.deep_extend(
            super().describe(),
            {
                "id": "gateeu",
                "name": "Gate EU",
                "countries": ["EU"],  # European Union
                "version": "v4",
                "rateLimit": 20,
                "pro": True,
                "certified": False,
                "urls": {
                    "api": {
                        "public": {
                            "wallet": "https://api.gateeu.com/api/v4",
                            "margin": "https://api.gateeu.com/api/v4",
                            "spot": "https://api.gateeu.com/api/v4",
                            "sub_accounts": "https://api.gateeu.com/api/v4",
                            "earn": "https://api.gateeu.com/api/v4",
                        },
                        "private": {
                            "withdrawals": "https://api.gateeu.com/api/v4",
                            "wallet": "https://api.gateeu.com/api/v4",
                            "margin": "https://api.gateeu.com/api/v4",
                            "spot": "https://api.gateeu.com/api/v4",
                            "subAccounts": "https://api.gateeu.com/api/v4",
                            "unified": "https://api.gateeu.com/api/v4",
                            "rebate": "https://api.gateeu.com/api/v4",
                            "earn": "https://api.gateeu.com/api/v4",
                            "account": "https://api.gateeu.com/api/v4",
                            "loan": "https://api.gateeu.com/api/v4",
                            "otc": "https://api.gateeu.com/api/v4",
                        },
                    },
                },
                "has": {
                    "CORS": True,
                    "spot": True,
                    "margin": True,
                    "swap": False,
                    "future": False,
                    "option": None,
                },
                "options": {
                    "fetchMarkets": {
                        "types": ["spot"],
                    },
                    "mica": True,
                },
            },
        )
