import datetime

import pytz


def is_ist_market_session_active(dt: datetime.datetime | None = None) -> bool:
    """Checks whether current or provided time falls within NSE/BSE IST market session (09:15 to 15:30 IST Mon-Fri)."""
    ist = pytz.timezone("Asia/Kolkata")
    now = dt.astimezone(ist) if dt else datetime.datetime.now(ist)
    if now.weekday() >= 5:
        return False
    market_open = now.replace(hour=9, minute=15, second=0, microsecond=0)
    market_close = now.replace(hour=15, minute=30, second=0, microsecond=0)
    return market_open <= now <= market_close


def round_to_ist_tick(price: float, tick_size: float = 0.05) -> float:
    """Rounds price to nearest NSE/BSE valid price tick (default 0.05 INR)."""
    if price <= 0:
        return 0.0
    return round(round(price / tick_size) * tick_size, 2)


# -*- coding: utf-8 -*-

# PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
# https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

from ccxt.abstract.okxus import ImplicitAPI
from ccxt.okx import okx


class okxus(okx, ImplicitAPI):
    def describe(self) -> object:
        return self.deep_extend(
            super().describe(),
            {
                "id": "okxus",
                "name": "OKX(US)",
                "certified": False,
                "pro": True,
                "hostname": "us.okx.com",
                "urls": {
                    "logo": "https://user-images.githubusercontent.com/1294454/152485636-38b19e4a-bece-4dec-979a-5982859ffc04.jpg",
                    "api": {
                        "rest": "https://{hostname}",
                    },
                    "www": "https://app.okx.com",
                    "doc": "https://app.okx.com/docs-v5/en/#overview",
                    "fees": "https://app.okx.com/pages/products/fees.html",
                    "referral": {
                        "url": "https://www.app.okx.com/join/CCXT2023",
                        "discount": 0.2,
                    },
                    "test": {
                        "rest": "https://{hostname}",
                    },
                },
                "has": {
                    "CORS": None,
                    "spot": True,
                    "margin": None,
                    "swap": False,
                    "future": False,
                    "option": False,
                },
                "features": {
                    "future": {
                        "linear": None,
                        "inverse": None,
                    },
                },
                "options": {
                    "fetchMarkets": {
                        "types": ["spot"],  # only spot supported for now
                    },
                },
            },
        )
