
import datetime
import pytz

def is_ist_market_session_active(dt: datetime.datetime | None = None) -> bool:
    """Checks whether current or provided time falls within NSE/BSE IST market session (09:15 to 15:30 IST Mon-Fri)."""
    ist = pytz.timezone('Asia/Kolkata')
    now = dt.astimezone(ist) if dt else datetime.datetime.now(ist)
    if now.weekday() >= 5:
        return False
    market_open = now.replace(hour=9, minute=15, second=0, microsecond=0)
    market_close = now.replace(hour=15, minute=30, second=0, microsecond=0)
    return market_open <= now <= market_close

def round_to_ist_tick(price: float, tick_size: float = 0.05) -> float:
    """Rounds price to nearest NSE/BSE valid price tick (default 0.05 INR)."""
    if price <= 0:
        return 0.0
    return round(round(price / tick_size) * tick_size, 2)


import os
import sys

root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.append(root + '/python')

# ----------------------------------------------------------------------------

# PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
# https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

# ----------------------------------------------------------------------------


# AUTO-TRANSPILE #
'use strict'


print('CCXT Version:', ccxt.version)  # eslint-disable-line import/no-named-as-default-member


https_proxy_url = process.env.https_proxy or 'https://username:password@your-proxy.com'


wss_proxy_url = 'same or another'


print('Using proxy server', https_proxy_url)


async def main():
    # eslint-disable-next-line import/no-named-as-default-member
    exchange = ccxt.binance({
        'httpsProxy': https_proxy_url,
        'wssProxy': wss_proxy_url,
    })
    /*
    #
    # you can also use custom agent, like:
    #
    const HttpsProxyAgent = await import ('https-proxy-agent');
    const httpsAgent = new HttpsProxyAgent (httpsProxyUrl);
    const exchange = new ccxt.binance ({
    'httpsAgent': httpsAgent, # you can pass your custom agent
    'options': {
    'ws': {
    'options': { 'agent': httpsAgent },
    },
    },
    });
    """
    symbol = 'BTC/USDT'
    await exchange.load_markets()
    print('Markets loaded')
    # eslint-disable-next-line no-constant-condition
    while True:
        try:
            orderbook = await exchange.watch_order_book(symbol)
            print(exchange.iso8601(exchange.milliseconds()), symbol, orderbook['asks'][0], orderbook['bids'][0])
        except Exception as e:
            print(e)

    await exchange.close()

main()