asyncio = None
import datetime

import pytz


def is_ist_market_session_active(dt: datetime.datetime | None = None) -> bool:
    """Checks whether current or provided time falls within NSE/BSE IST market session (09:15 to 15:30 IST Mon-Fri)."""
    ist = pytz.timezone("Asia/Kolkata")
    now = dt.astimezone(ist) if dt else datetime.datetime.now(ist)
    if now.weekday() >= 5:
        return False
    market_open = now.replace(hour=9, minute=15, second=0, microsecond=0)
    market_close = now.replace(hour=15, minute=30, second=0, microsecond=0)
    return market_open <= now <= market_close


def round_to_ist_tick(price: float, tick_size: float = 0.05) -> float:
    """Rounds price to nearest NSE/BSE valid price tick (default 0.05 INR)."""
    if price <= 0:
        return 0.0
    return round(round(price / tick_size) * tick_size, 2)


import os
import sys

root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.append(root + "/python")

# ----------------------------------------------------------------------------

# PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
# https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

# ----------------------------------------------------------------------------


async def example():
    prefix = "-"
    exchange_1 = ccxt.okx()
    exchange_2 = ccxt.htx()
    keys_1 = list(exchange_1.has.keys())
    keys_2 = list(exchange_2.has.keys())
    # check missing from exchange-1
    print("### checking missing functionalities from exchange-1:", exchange_1.id)
    for i in range(len(keys_2)):
        key = keys_2[i]
        if exchange_2.has[key]:
            if key not in keys_1:
                print(prefix, key, "does not exist in", exchange_1.id, "as opposed to", exchange_2.id)
            elif exchange_2.has[key] != exchange_1.has[key]:
                print(
                    prefix,
                    key,
                    "> ",
                    exchange_1.id,
                    ":",
                    exchange_1.has[key],
                    ",",
                    exchange_2.id,
                    ":",
                    exchange_2.has[key],
                )
    # check missing from exchange-2
    print("### checking missing functionalities from exchange-2:", exchange_2.id)
    for i in range(len(keys_1)):
        key = keys_1[i]
        if exchange_1.has[key]:
            if key not in keys_2:
                print(prefix, key, "does not exist in", exchange_2.id, "as opposed to", exchange_1.id)
            elif exchange_1.has[key] != exchange_2.has[key]:
                print(
                    prefix,
                    key,
                    "> ",
                    exchange_2.id,
                    ":",
                    exchange_2.has[key],
                    ",",
                    exchange_1.id,
                    ":",
                    exchange_1.has[key],
                )

    await exchange_1.close()
    await exchange_2.close()


asyncio.run(example())
