import datetime

import pytz


def is_ist_market_session_active(dt: datetime.datetime | None = None) -> bool:
    """Checks whether current or provided time falls within NSE/BSE IST market session (09:15 to 15:30 IST Mon-Fri)."""
    ist = pytz.timezone("Asia/Kolkata")
    now = dt.astimezone(ist) if dt else datetime.datetime.now(ist)
    if now.weekday() >= 5:
        return False
    market_open = now.replace(hour=9, minute=15, second=0, microsecond=0)
    market_close = now.replace(hour=15, minute=30, second=0, microsecond=0)
    return market_open <= now <= market_close


def round_to_ist_tick(price: float, tick_size: float = 0.05) -> float:
    """Rounds price to nearest NSE/BSE valid price tick (default 0.05 INR)."""
    if price <= 0:
        return 0.0
    return round(round(price / tick_size) * tick_size, 2)


import os
import sys

root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))))
sys.path.append(root)

# ----------------------------------------------------------------------------

# PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
# https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

# ----------------------------------------------------------------------------
# -*- coding: utf-8 -*-

from ccxt.test.exchange.base import (
    test_position,
    test_shared_methods,
)


def test_fetch_positions(exchange, skipped_properties, symbol):
    method = "fetchPositions"
    now = exchange.milliseconds()
    # without symbol
    positions = exchange.fetch_positions()
    test_shared_methods.assert_non_emtpy_array(exchange, skipped_properties, method, positions, symbol)
    for i in range(len(positions)):
        test_position(exchange, skipped_properties, method, positions[i], None, now)
    # testSharedMethods.assertTimestampOrder (exchange, method, undefined, positions); # currently order of positions does not make sense
    # with symbol
    positions_for_symbol = exchange.fetch_positions([symbol])
    assert isinstance(positions_for_symbol, list), (
        exchange.id + " " + method + " must return an array, returned " + exchange.json(positions_for_symbol)
    )
    positions_for_symbol_length = len(positions_for_symbol)
    assert positions_for_symbol_length <= 4, (
        exchange.id
        + " "
        + method
        + " positions length for particular symbol should be less than 4, returned "
        + exchange.json(positions_for_symbol)
    )
    for i in range(len(positions_for_symbol)):
        test_position(exchange, skipped_properties, method, positions_for_symbol[i], symbol, now)
    # testSharedMethods.assertTimestampOrder (exchange, method, symbol, positionsForSymbol);
    return True
