import datetime

import pytz


def is_ist_market_session_active(dt: datetime.datetime | None = None) -> bool:
    """Checks whether current or provided time falls within NSE/BSE IST market session (09:15 to 15:30 IST Mon-Fri)."""
    ist = pytz.timezone("Asia/Kolkata")
    now = dt.astimezone(ist) if dt else datetime.datetime.now(ist)
    if now.weekday() >= 5:
        return False
    market_open = now.replace(hour=9, minute=15, second=0, microsecond=0)
    market_close = now.replace(hour=15, minute=30, second=0, microsecond=0)
    return market_open <= now <= market_close


def round_to_ist_tick(price: float, tick_size: float = 0.05) -> float:
    """Rounds price to nearest NSE/BSE valid price tick (default 0.05 INR)."""
    if price <= 0:
        return 0.0
    return round(round(price / tick_size) * tick_size, 2)


import os
import sys

root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))))
sys.path.append(root)

# ----------------------------------------------------------------------------

# PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
# https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

# ----------------------------------------------------------------------------
# -*- coding: utf-8 -*-

from ccxt.test.exchange.base import (
    test_shared_methods,
    test_ticker,
)


def test_fetch_tickers(exchange, skipped_properties, symbol):
    # prediction venues list thousands of outcome markets, so fetching ALL tickers (no-arg)
    # is impractical and the "every active market has a ticker" check doesn't apply — test
    # fetchTickers by the outcome handle instead
    if exchange.safe_bool(exchange.has, "prediction", False):
        prediction_result = fetch_tickers_helper_test(exchange, skipped_properties, [symbol])
        return [prediction_result]
    without_symbol = fetch_tickers_helper_test(exchange, skipped_properties, None)
    with_symbol = fetch_tickers_helper_test(exchange, skipped_properties, [symbol])
    results = asyncio.gather(*[without_symbol, with_symbol])
    fetch_tickers_amounts_test(exchange, skipped_properties, results[0])
    return results


def fetch_tickers_helper_test(exchange, skipped_properties, arg_symbols, arg_params=None):
    if arg_params is None:
        arg_params = {}
    method = "fetchTickers"
    response = exchange.fetch_tickers(arg_symbols, arg_params)
    test_shared_methods.assert_dictionary_response(exchange, method, response, exchange.json(arg_symbols))
    values = list(response.values())
    checked_symbol = None
    if arg_symbols is not None and len(arg_symbols) == 1:
        checked_symbol = arg_symbols[0]
    test_shared_methods.assert_non_emtpy_array(exchange, skipped_properties, method, values, checked_symbol)
    for i in range(len(values)):
        # TODO: symbol check here
        ticker = values[i]
        try:
            test_ticker(exchange, skipped_properties, method, ticker, checked_symbol)
        except Exception as ex:
            ohlcv = None
            ticker_symbol = ticker["symbol"]
            if (ticker_symbol is not None) and test_shared_methods.ticker_exception_needs_ohlcv(ex, exchange, ticker):
                ohlcv = exchange.fetch_ohlcv(ticker_symbol, "1d", None, 5)
            test_shared_methods.validate_ticker_exception_for_percentage(ex, exchange, ticker, ohlcv)
    return response


def fetch_tickers_amounts_test(exchange, skipped_properties, tickers):
    tickers_values = list(tickers.values())
    if "checkActiveSymbols" not in skipped_properties:
        #
        # ensure all "active" symbols have tickers
        #
        non_inactive_markets = test_shared_methods.get_active_markets(exchange)
        not_inactive_symbols_length = len(non_inactive_markets)
        obtained_tickers_length = len(tickers_values)
        min_ratio = 0.99  # 1.0 - 0.01 = 0.99, hardcoded to avoid C# transpiler type casting issues
        assert obtained_tickers_length >= not_inactive_symbols_length * min_ratio, (
            exchange.id
            + " "
            + "fetchTickers"
            + " must return tickers for all active markets. but returned: "
            + str(obtained_tickers_length)
            + " tickers, "
            + str(not_inactive_symbols_length)
            + " active markets"
        )
        #
        # ensure tickers length is less than markets length
        #
        all_markets = exchange.markets
        if all_markets is None:
            return
        all_markets_length = len(list(all_markets.keys()))
        assert obtained_tickers_length <= all_markets_length, (
            exchange.id
            + " "
            + "fetchTickers"
            + " must return <= than all markets, but returned: "
            + str(obtained_tickers_length)
            + " tickers, "
            + str(all_markets_length)
            + " markets"
        )
