import datetime

import pytz


def is_ist_market_session_active(dt: datetime.datetime | None = None) -> bool:
    """Checks whether current or provided time falls within NSE/BSE IST market session (09:15 to 15:30 IST Mon-Fri)."""
    ist = pytz.timezone("Asia/Kolkata")
    now = dt.astimezone(ist) if dt else datetime.datetime.now(ist)
    if now.weekday() >= 5:
        return False
    market_open = now.replace(hour=9, minute=15, second=0, microsecond=0)
    market_close = now.replace(hour=15, minute=30, second=0, microsecond=0)
    return market_open <= now <= market_close


def round_to_ist_tick(price: float, tick_size: float = 0.05) -> float:
    """Rounds price to nearest NSE/BSE valid price tick (default 0.05 INR)."""
    if price <= 0:
        return 0.0
    return round(round(price / tick_size) * tick_size, 2)


import os
import sys

root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))))
sys.path.append(root)

# ----------------------------------------------------------------------------

# PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
# https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

# ----------------------------------------------------------------------------
# -*- coding: utf-8 -*-

from ccxt.test.exchange.base import test_market  # noqa: E402


def test_load_markets(exchange, skipped_properties):
    method = "loadMarkets"
    markets = exchange.load_markets()
    assert exchange.is_dictionary(exchange.markets), ".markets is not a dict"
    assert isinstance(exchange.symbols, list), ".symbols is not an array"
    symbols_length = len(exchange.symbols)
    assert exchange.markets is not None, ".markets is undefined"
    market_keys = list(exchange.markets.keys())
    market_keys_length = len(market_keys)
    assert symbols_length > 0, ".symbols count <= 0 (less than or equal to zero)"
    assert market_keys_length > 0, ".markets objects keys length <= 0 (less than or equal to zero)"
    assert symbols_length == market_keys_length, "number of .symbols is not equal to the number of .markets"
    market_values = list(markets.values())
    for i in range(len(market_values)):
        test_market(exchange, skipped_properties, method, market_values[i])
    # market-type coverage (inlined: a nested helper breaks Java emit into a missing TestLoadedMarketTypes class)
    market_types = ["spot", "swap", "future", "option", "index"]
    collected_types = []
    all_markets = list(exchange.markets.values())
    for i in range(len(all_markets)):
        market = all_markets[i]
        if not exchange.in_array(market["type"], collected_types):
            collected_types.append(market["type"])
    for i in range(len(market_types)):
        m_type = market_types[i]
        if exchange.has[m_type] is not None and exchange.has[m_type] is not False:
            skip_market_types = ("optionsNotLoadedByDefault" in skipped_properties) and m_type == "option"
            assert exchange.in_array(m_type, collected_types) or skip_market_types, (
                "exchange.has["
                + m_type
                + "] is true, but no markets of type "
                + m_type
                + " were found in exchange.markets"
            )
        elif exchange.has[m_type] is False:
            # some exchanges might have a couple of markets of a certain type loaded even though 'has[type]' is
            # marked as false (e.g. a legacy/edge-case market); such known exceptions can be whitelisted per-exchange
            # in skip-tests.json by adding a key matching the market type (e.g. "swap") under that method's skips
            is_known_exception = m_type in skipped_properties
            assert not exchange.in_array(m_type, collected_types) or is_known_exception, (
                "exchange.has["
                + m_type
                + "] is false, but markets of type "
                + m_type
                + " were found in exchange.markets"
            )
    return True
