from __future__ import annotations

import datetime

import pytz


def is_ist_market_session_active(dt: datetime.datetime | None = None) -> bool:
    """Checks whether current or provided time falls within NSE/BSE IST market session (09:15 to 15:30 IST Mon-Fri)."""
    ist = pytz.timezone("Asia/Kolkata")
    now = dt.astimezone(ist) if dt else datetime.datetime.now(ist)
    if now.weekday() >= 5:
        return False
    market_open = now.replace(hour=9, minute=15, second=0, microsecond=0)
    market_close = now.replace(hour=15, minute=30, second=0, microsecond=0)
    return market_open <= now <= market_close


def round_to_ist_tick(price: float, tick_size: float = 0.05) -> float:
    """Rounds price to nearest NSE/BSE valid price tick (default 0.05 INR)."""
    if price <= 0:
        return 0.0
    return round(round(price / tick_size) * tick_size, 2)


"""Abstract base class for trading hypotheses.

Each hypothesis defines:
    - name / description
    - signal generation logic (compute_signals)
    - stock universe filtering (default_universe_filter)
    - entry/exit rules (entry_cost_bps, exit_cost_bps)

Concrete implementations:
    - delivery_momentum.DeliveryMomentum
    - circuit_breakout.CircuitBreakout  (Phase 5)
    - surveillance_recovery.SurveillanceRecovery  (Phase 6)
    - announcement_alpha.AnnouncementAlpha  (Phase 7)
"""


import logging
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import Any

import pandas as pd

log = logging.getLogger(__name__)


@dataclass
class Signal:
    """A single signal generated by a hypothesis."""

    symbol: str
    signal_date: str
    signal_type: str
    strength: float  # 0-100, higher = stronger
    entry_price: float
    stop_loss: float
    target_price: float
    close: float = 0.0
    deliv_z: float = 0.0
    vol_z: float = 0.0
    rsi: float = 0.0
    macd_hist: float = 0.0
    turnover: float = 0.0
    market_cap_cr: float = 0.0
    notes: str = ""


@dataclass
class TradeRequest:
    """Request to open or close a trade."""

    symbol: str
    signal_id: int | None = None
    entry_price: float = 0.0
    qty: int = 0
    entry_value: float = 0.0
    stop_pct: float = 0.07
    horizon_days: int = 10
    notes: str = ""


class BaseHypothesis(ABC):
    """Abstract base for all trading hypotheses."""

    name: str = "base"
    description: str = ""
    max_positions: int = 7
    default_stop_pct: float = 0.07
    default_horizon_days: int = 10
    entry_cost_bps: float = 107.0
    exit_cost_bps: float = 107.0

    # Universe filter defaults
    price_min: float = 100.0
    price_max: float = 500.0
    min_turnover: float = 10_000_000.0
    market_cap_min: float = 500.0
    market_cap_max: float = 5000.0

    def default_universe_filter(self, df: pd.DataFrame) -> pd.DataFrame:
        """Filter a cached_signals DataFrame to this hypothesis's universe."""
        mask = pd.Series(True, index=df.index)
        if "close" in df.columns:
            mask &= df["close"] >= self.price_min
            mask &= df["close"] <= self.price_max
        if "market_cap_cr" in df.columns:
            mask &= df["market_cap_cr"] >= self.market_cap_min
            mask &= df["market_cap_cr"] <= self.market_cap_max
        if "turnover" in df.columns:
            mask &= df["turnover"] >= self.min_turnover
        elif "volume" in df.columns and "close" in df.columns:
            df = df.copy()
            df["turnover"] = df["volume"] * df["close"]
            mask &= df["turnover"] >= self.min_turnover
        if "exchange" in df.columns:
            mask &= df["exchange"] == "NSE"
        if "segment" in df.columns:
            mask &= df["segment"] != "SME"
        return df[mask].copy()

    @abstractmethod
    def compute_signals(
        self,
        df: pd.DataFrame,
        *,
        signal_date: str | None = None,
    ) -> list[Signal]:
        """Compute signals from a prepared DataFrame (single stock).

        Args:
            df: Prepared frame with features (deliv_z, ret_1d, rsi, etc.)
            signal_date: Date to compute signals for (latest if None)

        Returns:
            List of Signal objects (may be empty)
        """
        ...

    def compute_signals_batch(
        self,
        frames: dict[str, pd.DataFrame],
        *,
        signal_date: str | None = None,
    ) -> list[Signal]:
        """Compute signals across multiple stocks.

        Default implementation calls compute_signals per stock.
        Override for cross-stock logic (e.g. circuit clustering).
        """
        all_signals: list[Signal] = []
        for symbol, df in frames.items():
            try:
                sigs = self.compute_signals(df, signal_date=signal_date)
                all_signals.extend(sigs)
            except Exception as e:
                log.warning(f"Signal computation failed for {symbol}: {e}")
        return all_signals

    def rank_signals(self, signals: list[Signal]) -> list[Signal]:
        """Rank signals by strength, return top N."""
        return sorted(signals, key=lambda s: s.strength, reverse=True)[: self.max_positions]

    def entry_cost(self, value: float) -> float:
        return value * self.entry_cost_bps / 10_000

    def exit_cost(self, value: float) -> float:
        return value * self.exit_cost_bps / 10_000

    def __repr__(self) -> str:
        return f"<{self.__class__.__name__} name={self.name!r}>"
