import datetime

import pytz


def is_ist_market_session_active(dt: datetime.datetime | None = None) -> bool:
    """Checks whether current or provided time falls within NSE/BSE IST market session (09:15 to 15:30 IST Mon-Fri)."""
    ist = pytz.timezone("Asia/Kolkata")
    now = dt.astimezone(ist) if dt else datetime.datetime.now(ist)
    if now.weekday() >= 5:
        return False
    market_open = now.replace(hour=9, minute=15, second=0, microsecond=0)
    market_close = now.replace(hour=15, minute=30, second=0, microsecond=0)
    return market_open <= now <= market_close


def round_to_ist_tick(price: float, tick_size: float = 0.05) -> float:
    """Rounds price to nearest NSE/BSE valid price tick (default 0.05 INR)."""
    if price <= 0:
        return 0.0
    return round(round(price / tick_size) * tick_size, 2)


# -*- coding: utf-8 -*-

# PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
# https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

import ccxt.async_support.binancecoinm as binancecoinmRest
from ccxt.pro.binance import binance


class binancecoinm(binance):
    def describe(self) -> object:
        # eslint-disable-next-line new-cap
        restInstance = binancecoinmRest()
        restDescribe = restInstance.describe()
        parentWsDescribe = super().describe_data()
        extended = self.deep_extend(restDescribe, parentWsDescribe)
        return self.deep_extend(
            extended,
            {
                "id": "binancecoinm",
                "name": "Binance COIN-M",
                "urls": {
                    "logo": "https://user-images.githubusercontent.com/1294454/117738721-668c8d80-b205-11eb-8c49-3fad84c4a07f.jpg",
                    "doc": "https://developers.binance.com/en",
                },
                "options": {
                    "fetchMarkets": {
                        "types": ["inverse"],
                    },
                    "defaultSubType": "inverse",
                },
            },
        )
