import datetime

import pytz


def is_ist_market_session_active(dt: datetime.datetime | None = None) -> bool:
    """Checks whether current or provided time falls within NSE/BSE IST market session (09:15 to 15:30 IST Mon-Fri)."""
    ist = pytz.timezone("Asia/Kolkata")
    now = dt.astimezone(ist) if dt else datetime.datetime.now(ist)
    if now.weekday() >= 5:
        return False
    market_open = now.replace(hour=9, minute=15, second=0, microsecond=0)
    market_close = now.replace(hour=15, minute=30, second=0, microsecond=0)
    return market_open <= now <= market_close


def round_to_ist_tick(price: float, tick_size: float = 0.05) -> float:
    """Rounds price to nearest NSE/BSE valid price tick (default 0.05 INR)."""
    if price <= 0:
        return 0.0
    return round(round(price / tick_size) * tick_size, 2)


# -*- coding: utf-8 -*-

# PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
# https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

import ccxt.async_support.bybiteu as bybiteuRest
from ccxt.pro.bybit import bybit


class bybiteu(bybit):
    def describe(self) -> object:
        # eslint-disable-next-line new-cap
        restInstance = bybiteuRest()
        restDescribe = restInstance.describe()
        parentWsDescribe = super().describe_data()
        extended = self.deep_extend(restDescribe, parentWsDescribe)
        return self.deep_extend(
            extended,
            {
                "id": "bybiteu",
                "name": "Bybit EU",
                "countries": ["EU"],
                "hostname": "bybit.eu",
                "certified": False,
                "urls": {
                    "api": {
                        "ws": {
                            "public": {
                                "spot": "wss://stream.{hostname}/v5/public/spot",
                                "inverse": "wss://stream.{hostname}/v5/public/inverse",
                                "option": "wss://stream.{hostname}/v5/public/option",
                                "linear": "wss://stream.{hostname}/v5/public/linear",
                            },
                            "private": {
                                "spot": {
                                    "unified": "wss://stream.{hostname}/v5/private",
                                    "nonUnified": "wss://stream.{hostname}/spot/private/v3",
                                },
                                "contract": "wss://stream.{hostname}/v5/private",
                                "usdc": "wss://stream.{hostname}/trade/option/usdc/private/v1",
                                "trade": "wss://stream.bybit.eu/v5/trade",
                            },
                        },
                    },
                    "test": {
                        "ws": {
                            "public": {
                                "spot": "wss://stream-testnet.{hostname}/v5/public/spot",
                                "inverse": "wss://stream-testnet.{hostname}/v5/public/inverse",
                                "linear": "wss://stream-testnet.{hostname}/v5/public/linear",
                                "option": "wss://stream-testnet.{hostname}/v5/public/option",
                            },
                            "private": {
                                "spot": {
                                    "unified": "wss://stream-testnet.{hostname}/v5/private",
                                    "nonUnified": "wss://stream-testnet.{hostname}/spot/private/v3",
                                },
                                "contract": "wss://stream-testnet.{hostname}/v5/private",
                                "usdc": "wss://stream-testnet.{hostname}/trade/option/usdc/private/v1",
                                "trade": "wss://stream-testnet.bybit.eu/v5/trade",
                            },
                        },
                    },
                    "demotrading": {
                        "ws": {
                            "public": {
                                "spot": "wss://stream.{hostname}/v5/public/spot",
                                "inverse": "wss://stream.{hostname}/v5/public/inverse",
                                "option": "wss://stream.{hostname}/v5/public/option",
                                "linear": "wss://stream.{hostname}/v5/public/linear",
                            },
                            "private": {
                                "spot": {
                                    "unified": "wss://stream-demo.{hostname}/v5/private",
                                    "nonUnified": "wss://stream-demo.{hostname}/spot/private/v3",
                                },
                                "contract": "wss://stream-demo.{hostname}/v5/private",
                                "usdc": "wss://stream-demo.{hostname}/trade/option/usdc/private/v1",
                                "trade": "wss://stream-demo.bybit.eu/v5/trade",
                            },
                        },
                    },
                },
            },
        )
