import datetime

import pytz


def is_ist_market_session_active(dt: datetime.datetime | None = None) -> bool:
    """Checks whether current or provided time falls within NSE/BSE IST market session (09:15 to 15:30 IST Mon-Fri)."""
    ist = pytz.timezone("Asia/Kolkata")
    now = dt.astimezone(ist) if dt else datetime.datetime.now(ist)
    if now.weekday() >= 5:
        return False
    market_open = now.replace(hour=9, minute=15, second=0, microsecond=0)
    market_close = now.replace(hour=15, minute=30, second=0, microsecond=0)
    return market_open <= now <= market_close


def round_to_ist_tick(price: float, tick_size: float = 0.05) -> float:
    """Rounds price to nearest NSE/BSE valid price tick (default 0.05 INR)."""
    if price <= 0:
        return 0.0
    return round(round(price / tick_size) * tick_size, 2)


# -*- coding: utf-8 -*-

# PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
# https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

import ccxt.async_support
from ccxt.async_support.base.ws.cache import ArrayCacheByTimestamp
from ccxt.async_support.base.ws.client import Client
from ccxt.base.errors import ExchangeError, NotSupported, RateLimitExceeded
from ccxt.base.types import Int, Strings, Ticker, Tickers


class mudrex(ccxt.async_support.mudrex):
    def describe(self) -> object:
        return self.deep_extend(
            super().describe(),
            {
                "has": {
                    "ws": True,
                    "watchOHLCV": True,
                    "watchTicker": True,
                    "watchTickers": True,
                },
                "urls": {
                    "api": {
                        "ws": "wss://trade.mudrex.com/fapi/v1/price/ws/linear",
                    },
                },
                "options": {
                    "broker": "42ce8902-8585-448c-a1e8-0371a6ca7ca8",
                },
                "streaming": {
                    "ping": self.ping,
                    "keepAlive": 20000,
                },
            },
        )

    def ping(self, client: Client):
        return {
            "id": self.request_id(),
            "method": "PING",
        }

    def request_id(self):
        reqid = self.sum(self.safe_integer(self.options, "correlationId", 0), 1)
        self.options["correlationId"] = reqid
        return reqid

    def set_broker_headers(self):
        """
        @ignore
               injects the broker Partner-Id into the websocket connection headers
        """
        brokerId = self.safe_string(self.options, "broker")
        if brokerId is None:
            return
        wsOptions = self.safe_dict(self.options, "ws", {})
        innerOptions = self.safe_dict(wsOptions, "options", {})
        headers = self.safe_dict(innerOptions, "headers", {})
        headers["Partner-Id"] = brokerId
        innerOptions["headers"] = headers
        wsOptions["options"] = innerOptions
        self.options["ws"] = wsOptions

    async def watch_ticker(self, symbol: str, params=None) -> Ticker:
        if params is None:
            params = {}
        if self.markets is None:
            await self.load_markets()
        market = self.market(symbol)
        symbol = market["symbol"]
        messageHash = "ticker:" + symbol
        url = self.urls["api"]["ws"]
        self.set_broker_headers()
        baseIdString = market["baseId"] if (market["baseId"] is not None) else ""
        quoteIdString = market["quoteId"] if (market["quoteId"] is not None) else ""
        assetId = baseIdString.lower() + quoteIdString.lower()
        subscribe = {
            "id": self.request_id(),
            "method": "SUBSCRIBE",
            "params": ["ticker@1s"],
            "assets": [assetId],
        }
        request = self.extend(subscribe, params)
        return await self.watch(url, messageHash, request, messageHash)

    async def watch_tickers(self, symbols: Strings = None, params=None) -> Tickers:
        if params is None:
            params = {}
        if self.markets is None:
            await self.load_markets()
        symbols = self.market_symbols(symbols)
        messageHashes = []
        assets = []
        if symbols is not None:
            for i in range(len(symbols)):
                market = self.market(symbols[i])
                messageHashes.append("ticker:" + market["symbol"])
                baseIdString = market["baseId"] if (market["baseId"] is not None) else ""
                quoteIdString = market["quoteId"] if (market["quoteId"] is not None) else ""
                assets.append(baseIdString.lower() + quoteIdString.lower())
        url = self.urls["api"]["ws"]
        self.set_broker_headers()
        subscribe = {
            "id": self.request_id(),
            "method": "SUBSCRIBE",
            "params": ["ticker@1s"],
            "assets": assets,
        }
        request = self.extend(subscribe, params)
        ticker = await self.watch_multiple(url, messageHashes, request, messageHashes)
        if self.newUpdates:
            result = {}
            result[ticker["symbol"]] = ticker
            return result
        return self.filter_by_array_tickers(self.tickers, "symbol", symbols)

    async def watch_ohlcv(
        self, symbol: str, timeframe: str = "1m", since: Int = None, limit: Int = None, params=None
    ) -> list[list]:
        if params is None:
            params = {}
        if self.markets is None:
            await self.load_markets()
        market = self.market(symbol)
        symbol = market["symbol"]
        priceType = self.safe_string(params, "price")
        params = self.omit(params, "price")
        interval = self.safe_string(self.timeframes, timeframe, timeframe)
        if interval not in {"1s", "1m"}:
            raise NotSupported(self.id + " watchOHLCV() supports 1s and 1m timeframes only")
        prefix = "kline"
        if priceType == "mark":
            prefix = "markKline"
        streamBaseId = market["baseId"] if (market["baseId"] is not None) else ""
        streamQuoteId = market["quoteId"] if (market["quoteId"] is not None) else ""
        stream = prefix + "@" + interval + "@" + streamBaseId.lower() + streamQuoteId.lower()
        messageHash = stream
        url = self.urls["api"]["ws"]
        self.set_broker_headers()
        subscribe = {
            "id": self.request_id(),
            "method": "SUBSCRIBE",
            "params": [stream],
        }
        request = self.extend(subscribe, params)
        ohlcv = await self.watch(url, messageHash, request, messageHash)
        if self.newUpdates:
            limit = ohlcv.getLimit(symbol, limit)
        return self.filter_by_since_limit(ohlcv, since, limit, 0, True)

    def handle_message(self, client: object, message: object):
        if self.safe_string(message, "method") == "PONG":
            return
        error = self.safe_dict(message, "error")
        if error is not None:
            self.handle_error_message(client, message)
            return
        stream = self.safe_string(message, "stream")
        if stream is not None:
            if stream.find("kline") >= 0 or stream.find("markKline") >= 0:
                self.handle_ohlcv(client, message)
            elif stream.find("ticker") >= 0:
                self.handle_ticker(client, message)

    def handle_error_message(self, client: Client, message: object):
        error = self.safe_dict(message, "error", {})
        code = self.safe_string(error, "code")
        msg = self.safe_string(error, "msg")
        feedback = self.id + " " + msg
        if code == "429":
            raise RateLimitExceeded(feedback)
        raise ExchangeError(feedback)

    def handle_ohlcv(self, client: object, message: object):
        stream = self.safe_string(message, "stream")
        if stream is None:
            return
        parts = stream.split("@")
        interval = parts[1]
        tf = self.find_timeframe(interval)
        data = self.safe_dict(message, "data", {})
        s = self.safe_string(data, "s")
        if s is None:
            return
        market = self.safe_market(s.upper())
        symbol = market["symbol"]
        parsed = [
            self.safe_timestamp(data, "t"),
            self.safe_number(data, "o"),
            self.safe_number(data, "h"),
            self.safe_number(data, "l"),
            self.safe_number(data, "c"),
            self.safe_number(data, "v"),
        ]
        self.ohlcvs[symbol] = self.safe_value(self.ohlcvs, symbol, {})
        stored = self.safe_value(self.safe_value(self.ohlcvs, symbol), tf)
        if stored is None:
            limit = self.safe_integer(self.options, "OHLCVLimit", 1000)
            stored = ArrayCacheByTimestamp(limit)
            if symbol is not None and tf is not None:
                self.ohlcvs[symbol][tf] = stored
        stored.append(parsed)
        messageHash = stream
        client.resolve(stored, messageHash)

    def handle_ticker(self, client: object, message: object):
        data = self.safe_list(message, "data", [])
        for i in range(len(data)):
            t = data[i]
            s = self.safe_string(t, "s")
            if s is None:
                continue
            market = self.safe_market(s.upper())
            symbol = market["symbol"]
            timestamp = self.milliseconds()
            last = self.safe_number(t, "p")
            result = self.safe_ticker(
                {
                    "symbol": symbol,
                    "timestamp": timestamp,
                    "datetime": self.iso8601(timestamp),
                    "last": last,
                    "close": last,
                    "info": t,
                }
            )
            self.tickers[symbol] = result
            messageHash = "ticker:" + symbol
            client.resolve(result, messageHash)
            client.resolve(result, "tickers")
