use std::collections::BTreeMap;
use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};

/// Finds the project .env path (next to Cargo.toml or in working dir)
pub fn env_path() -> PathBuf {
    // Check if .env exists in current directory
    let cwd = std::env::current_dir().unwrap_or_default();
    cwd.join(".env")
}

/// Writes key-value pairs to .env, preserving existing entries
/// Uses atomic write (write to .env.tmp, then rename)
pub fn save_keys(keys: &[(&str, &str)]) -> std::io::Result<()> {
    let path = env_path();
    let mut existing = load_existing(&path);

    // Merge new keys (overwrite if already present)
    for (k, v) in keys {
        if !v.trim().is_empty() {
            existing.insert(k.to_string(), v.to_string());
        }
    }

    // Write to temporary file first (atomic write)
    let tmp_path = path.with_extension("env.tmp");
    {
        let mut file = fs::File::create(&tmp_path)?;

        // Write header
        writeln!(file, "# RustForge Configuration")?;
        writeln!(file, "# Auto-generated by setup wizard")?;
        writeln!(
            file,
            "# Edit manually or re-run setup with: cargo run -p tui -- --setup"
        )?;
        writeln!(file)?;

        for (key, value) in &existing {
            writeln!(file, "{}={}", key, value)?;
        }

        file.sync_all()?; // Ensure flush to disk
    }

    // Atomic rename
    fs::rename(&tmp_path, &path)?;

    // Set secure permissions on Unix systems
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let perms = std::fs::Permissions::from_mode(0o600); // owner read/write only
        if let Err(e) = std::fs::set_permissions(&path, perms) {
            eprintln!("Warning: could not set secure .env permissions: {}", e);
        }
    }

    // Also inject into current process environment
    for (k, v) in keys {
        if !v.trim().is_empty() {
            std::env::set_var(k, v);
        }
    }

    Ok(())
}

fn load_existing(path: &Path) -> BTreeMap<String, String> {
    let mut map = BTreeMap::new();
    if let Ok(content) = fs::read_to_string(path) {
        for line in content.lines() {
            let line = line.trim();
            if line.is_empty() || line.starts_with('#') {
                continue;
            }
            if let Some((k, v)) = line.split_once('=') {
                map.insert(k.trim().to_string(), v.trim().to_string());
            }
        }
    }
    map
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    #[test]
    fn test_roundtrip_write_read() {
        let dir = TempDir::new().unwrap();
        let path = dir.path().join(".env");
        std::env::set_current_dir(dir.path()).unwrap();

        save_keys(&[
            ("FINNHUB_API_KEY", "test_key_123"),
            ("ALPACA_API_KEY", "AKID_456"),
        ])
        .unwrap();

        let loaded = load_existing(&path);
        assert_eq!(loaded.get("FINNHUB_API_KEY").unwrap(), "test_key_123");
        assert_eq!(loaded.get("ALPACA_API_KEY").unwrap(), "AKID_456");
    }
}
