name: Quant Stack SDLC Automation

on:
  workflow_dispatch:

jobs:
  sdlc_lifecycle_pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Exec
        run: |
          git init .
          git remote add origin "https://github.com{{ github.repository }}.git"
          git fetch --no-tags --prune --depth=1 origin "refs/heads/main"
          git checkout --progress --force "FETCH_HEAD"
          bash ./run_pipeline.sh
